### ISSUE TITLE
Getting following error in jenkins for publish selenium html reports

### ISSUE THREAD

**Issue by ranjith36** [prashant-ramcharan/courgette-jvm#1]
Publishing Selenium report...
Copying the reports.
parsing resultFile courgette-report/courgette.html/index.html
Unable to parse courgette-report/courgette.html/index.html: java.io.IOException: org.xml.sax.SAXParseException; systemId: file:/jenkins/jobs/***/builds/156/seleniumReports/courgette-report/courgette.html/index.html; lineNumber: 10; columnNumber: 5; The element type "link" must be terminated by the matching end-tag "</link>".
parsing resultFile reports/tests/index.html
Unable to parse reports/tests/index.html: java.io.IOException: org.xml.sax.SAXParseExceptionpublicId: -//W3C//DTD HTML 4.01//EN; systemId: http://www.w3.org/TR/html4/strict.dtd; lineNumber: 81; columnNumber: 5; The declaration for the entity "ContentType" must end with '>'.
Set result to FAILURE

**Comment by PrashantRiverIsland** [comment]
What's the Jenkins plugin name? Is it the cucumber reporting plugin?

**Comment by ranjith36** [comment]
It's Selenium html reports plugin!!

**Comment by prashant-ramcharan** [comment]
This library generates Cucumber reports only.

**courgette-report/courgette.html/index.html** is a Cucumber Report not a Selenium Report.

https://wiki.jenkins-ci.org/display/JENKINS/Cucumber+Reports+Plugin

You need to change your Jenkins publishising job to parse Selenium Html reports -- not Courgette / Cucumber Reports. 

Perhaps change the path to where your Selenium reports are written to?
