### ISSUE TITLE
Is it possible on runtime to obtain number/name of  fork  that currently is executing a test ?

### ISSUE THREAD

**Issue by yhraichonak** [prashant-ramcharan/courgette-jvm#101]
For example, I have 6 pre-configured test users and want to distribute autotests among them to be executed in 6 parallel forks (not affecting each other). I.e. one test user works in one fixed fork. How to identify Courgette-JVM forks on runtime?

**Comment by prashant-ramcharan** [comment]
No, this not possible to determine at runtime because Courgette creates new threads from within the invoked thread (i.e. _from the initial thread_)

Perhaps consider using Cucumber tags and hooks to determine test users at runtime. This way, your tests are less dependant on thread numbers etc..
