### ISSUE TITLE
Feature Files getting run multiple times.

### ISSUE THREAD

**Issue by evanliferock** [prashant-ramcharan/courgette-jvm#102]
Hi prashant-ramcharan. We (@yangermeister) are seeing Feature files run multiple times.
Here is our Annotation setup.
```java
@RunWith(Courgette.class)
@CourgetteOptions(
        threads = 3,
        runLevel = CourgetteRunLevel.FEATURE,
        showTestOutput = true,
        reportTargetDir = "build",
        cucumberOptions =
        @CucumberOptions(
                glue = "com.sap.automation",
                features = "src/test/resources/features",
                plugin = {
                        "pretty",
                        "html:build/cucumber-html-report",
                        "json:build/cucumber-reports/Cucumber.json",
                        "junit:build/cucumber-reports/Cucumber.xml"},
                monochrome = true
        )
)
```
When we call gradle to run the task is setting:
`environment "cucumber.options", "src/test/resources/features/standard_exp_admin --tags 'not @prod'"`
before running

`src/test/resources/features/standard_exp_admin` contains 9 feature files, two of which have the `@prod` tag.

The expected behavior is that 7 features should be run each once. However as you can see by the screenshot: 
<img width="1239" alt="Screen Shot 2019-03-14 at 1 25 10 PM" src="https://user-images.githubusercontent.com/11913985/54389195-c5254380-465c-11e9-8a08-44ad7f881fdc.png">
Each feature file is getting run 7 times. 

The number of times the features are run matches how many features there are. For example 10 feature files to run, then each one is run 10 times, resulting in 100 test runs. This happens both when run from jenkins and locally.

Might be related to the use of cucumber.options in the environment. A similar job uses SystemProps such as `cucumber.tags` and does not have this problem

**Comment by prashant-ramcharan** [comment]
Hello,

The Gradle task needs to set the following system property for the Courgette runner:
````gradle
-Dcucumber.tags="not @prod"

// or 

environment "cucumber.tags", "not @prod"

````

Do not set **cucumber.options** because Courgette does not use these to determine runtime options.

Please look here for more details: https://github.com/prashant-ramcharan/courgette-jvm#gradle-run-options

**Comment by prashant-ramcharan** [comment]
Please reopen issue if still a problem.
