### ISSUE TITLE
Courgette + Intellij idea test run results

### ISSUE THREAD

**Issue by akhmad-sadaiev-exa** [prashant-ramcharan/courgette-jvm#105]
After run some tests with Courgette runner in Intellij Idea, i have been faced with strange results in Run Intellij Tab. It marks all test failed, even some of them passed.

Do you met such behavior before?

**Comment by prashant-ramcharan** [comment]
Courgette does not / cannot update the results in the IDE given the nature of the test runner.

Please use the exit code from the build tool (Gradle or Maven) alongside the Courgette / Cucumber reports.
