### ISSUE TITLE
Runner class in Scala with multiple step definition packages

### ISSUE THREAD

**Issue by EugeneBy** [prashant-ramcharan/courgette-jvm#106]
Is there a way to include multiple package names in the ```glue``` option? I'm trying to use Courgette-jvm plugin with Scala and my runner class looks like this: 
```
import courgette.api.{CourgetteOptions, CourgetteRunLevel}
import courgette.api.junit.Courgette
import cucumber.api.CucumberOptions
import org.junit.experimental.categories.Category
import org.junit.runner.RunWith

@RunWith(classOf[Courgette])
@CourgetteOptions(
  threads = 6,
  runLevel = CourgetteRunLevel.SCENARIO,
  rerunFailedScenarios = false,
  rerunAttempts = 2,
  showTestOutput = true,
  reportTargetDir = "build",
  cucumberOptions = new CucumberOptions(
    features = Array("src/test/resources/features"),
    glue = Array("com.example.packageOne", "com.example.packageTwo", "com.example.packageThree"),
    tags = Array("not @Ignore"),
    plugin = Array("pretty",
      "json:build/cucumber-report/cucumber.json",
      "html:build/cucumber-report/cucumber.html",
      "junit:build/cucumber-report/cucumber.xml"),
    strict = true))
class ParallelTestExecutorWithRetry
```

I ran the tests from the IDE - since there is a known issue, where the tests in the IDE are always shown as "failure", I checked the html report and it was empty.

What is the correct way to assemble the runner class in Scala, when the features are spread across many files and the step definitions are spread across multiple files as well?

**Comment by prashant-ramcharan** [comment]
I pushed an Courgette example using Scala here: https://github.com/prashant-ramcharan/courgette-jvm-example/tree/courgette-example-scala

Clone the above branch and run https://github.com/prashant-ramcharan/courgette-jvm-example/blob/courgette-example-scala/src/test/scala/suites/ScenarioSuite.scala

You can use "**com.example**" as the step def glue so that all sub packages within "com.example" are included in the scan. Did you try this?

The tests in IDE would be marked as "**terminated**" not "failed" because Courgette does not / cannot update the status in the IDE given the nature of the runner.

<img width="324" alt="Screenshot 2019-03-27 at 23 18 56" src="https://user-images.githubusercontent.com/2563149/55118643-e9fec980-50e6-11e9-89dc-00bf4b6ceb00.png">

**Comment by EugeneBy** [comment]
> The tests in IDE would be marked as "terminated" not "failed" because Courgette does not / cannot update the status in the IDE given the nature of the runner.

Yep, the tests are displayed as terminated.

> You can use "com.example" as the step def glue so that all sub packages within "com.example" are included in the scan. Did you try this?

I tried that - the tests finished very quickly (which is suspicious) and the report was empty.
I suspect that the problem is caused by the fact that step definition classes extend a parent class, that has a companion object, which is a singleton. 
In order to make my test suite compatible with Courgette-jvm, I believe I need to get rid of singletons.

Another question that I have is:
Currently my project has 6 step definition classes and every step def class has a companion test runner class, which looks like this:

```scala
import cucumber.api.CucumberOptions
import cucumber.api.junit.Cucumber
import com.example.RegressionTest
import org.junit.experimental.categories.Category
import org.junit.runner.RunWith

@Category(Array(classOf[RegressionTest]))
@RunWith(classOf[Cucumber])
@CucumberOptions(tags = Array("not @Ignore"))
class TestSuiteOne
```

Would it be okay if I replace these 6 classes with 6 Courgette-jvm runner classes, that look like the original post?

**Comment by prashant-ramcharan** [comment]
> Would it be okay if I replace these 6 classes with 6 Courgette-jvm runner classes, that look like the original post?

You'd only need 1 Courgette runner but its difficult to say without seeing your project setup. Do you have a demo project that replicates the problem you facing?

**Comment by prashant-ramcharan** [comment]
Please re-open if needed.
