### ISSUE TITLE
Scripts are not running in Parallel I tried with sample project.

### ISSUE THREAD

**Issue by BalurQA** [prashant-ramcharan/courgette-jvm#109]
Hi @prashant-ramcharan,

I liked your implementation it is very cool, simple and best for parallel run.

I cloned https://github.com/prashant-ramcharan/courgette-jvm project and ran on my local system. I see scripts are not running in Parallel.

I am trying to run firefox tests in Parallel.

Below is the run command that I used to run the scripts.
```
gradlew runChromeTestsUsingTestNG -Dcourgette.threads=2 -Dcourgette.runLevel=FEATURE -Dcourgette.rerunFailedScenarios=false -Dcourgette.sh
owTestOutput=true -Dcourgette.reportTargetDir=build
```

am I doing something incorrect here. could you please assist.

Again do you have the maven version for the same. I want to implement it in my maven project.

Thanks,
Sam

**Comment by prashant-ramcharan** [comment]
Hi,

I take it you cloned this example project: https://github.com/prashant-ramcharan/courgette-jvm-selenium

1. You can run the Gradle task directly from the IDE.

2. Run the task from the terminal (_must be in root of project_)

````gradle
// if you using Linux
./gradlew runFirefoxTestsUsingTestNG

// if you using Windows
gradlew.bat runFirefoxTestsUsingTestNG
````

This also works with Maven. Take a look at the example project here: https://github.com/prashant-ramcharan/courgette-jvm-maven-example

**Comment by BalurQA** [comment]
Thank you @prashant-ramcharan. 

I looked into Maven example and scripts are running in Parallel.  

CourgetteOptions is not letting me to pass multiple tags. Is this expected behavior of implementation.

I am trying below with feature level approach. Will this work or any additional changes I have to do ?

` tags = {"@regression, @smoke", "not @excluded"}`


Thanks,
Sam

**Comment by prashant-ramcharan** [comment]
You can provide multiple tags:

````
tags = {"@regression or @smoke", "not @excluded"}
````

**Comment by BalurQA** [comment]
Thank you. @prashant-ramcharan.
