### ISSUE TITLE
When running tests across multiple feature files, each scenario is run as many times as threads

### ISSUE THREAD

**Issue by oscar-mullin** [prashant-ramcharan/courgette-jvm#11]
Given this scenario:

Feature file a.feature (containing: scenario 1 and scenario 2)
Feature file b.feature (containing: scenario 3 and scenario 4)

When I run with concurrency as FEATURE level and rerunFailed=FALSE, each test is run twice, so I end up with 8 executions.

So, each test is triggered once per thread. Do you have any idea why this may be happening?

This is the config I'm using:

@RunWith(Courgette.class)
@CourgetteOptions(
        threads = 10,
        runLevel = CourgetteRunLevel.FEATURE,
        rerunFailedScenarios = false,
        showTestOutput = true,
        cucumberOptions = @CucumberOptions(
                features = "src/test/resources/features",
                glue = "steps",
                plugin = {
                        "pretty",
                        "json:src/test-report/some_results.json",
                        "html:src/test-report/some_results.html"}
        ))
public class CourgetteRunner {
}

**Comment by prashant-ramcharan** [comment]
I **was not** able to reproduce this issue.

Can you confirm that you only have **2 features files** with a maximum of **4 scenarios in total** and no others?

With your scenario, there would only be 2 threads -- 1 for each feature file (_provided that you only have 2 feature files_)

What does the courgette / cucumber report indicate?

You can try with the [Courgette-JVM example project](https://github.com/prashant-ramcharan/courgette-jvm-example)

**Comment by oscar-mullin** [comment]
Hi! Thanks for the quick response.
Yes, I can confirm that:

![image](https://user-images.githubusercontent.com/25311174/30722597-82f8af3a-9f08-11e7-905d-a8dd1bddc99f.png)

And each has only one Scenario.
The report shows them duplicated.
These are frontend E2E test cases that are using the selenium grid to run, but anyway, the problem is that their execution is triggered twice

**Comment by oscar-mullin** [comment]
I figure it out. The problem was that I had also imported cucumber dependencies in gradle. After removing them and just leaving your library, it worked.

**Comment by oscar-mullin** [comment]
Thanks!
