### ISSUE TITLE
Jenkins fails and can't find feature files if specify folder, instead file in CourgetteRunner

### ISSUE THREAD

**Issue by akhmad-sadaiev-exa** [prashant-ramcharan/courgette-jvm#111]
Is it possible to run it in this way?

**Comment by prashant-ramcharan** [comment]
Are you using a relative path in your CourgetteRunner? (_please share you runner here_)

Whats makes Jenkins fail? Is it because it couldn't find / run the tests?

**Comment by prashant-ramcharan** [comment]
> Are you using a relative path in your CourgetteRunner? (_please share you runner here_)
> 
> Whats makes Jenkins fail? Is it because it couldn't find / run the tests?

**Comment by prashant-ramcharan** [comment]
> Is it possible to run it in this way?

Yes, you can run tests using Courgette in Jenkins.

**Comment by prashant-ramcharan** [comment]
Inactive issue - closing.
