### ISSUE TITLE
Whatt does it mean threads?

### ISSUE THREAD

**Issue by akhmad-sadaiev-exa** [prashant-ramcharan/courgette-jvm#113]
Hi, i have one question:

What does it mean thread in courgette? 
For example. if we will have threads=5, is it mean 5 different JVM procceses or 5 threads inside one JVM?

Thanks in advance for the answer

**Comment by prashant-ramcharan** [comment]
Hello,

1 Thread = 1 JVM Process.

In the context of your example, it would mean Courgette will create 5 separate JVM processes.

**Comment by akhmad-sadaiev-exa** [comment]
Thank you
