### ISSUE TITLE
Cucumber scenario not appending written strings

### ISSUE THREAD

**Issue by papsicle** [prashant-ramcharan/courgette-jvm#115]
Hi,

I used to only have Cucumber run setup and used the @Before and @After annotations to do some general dataSetup/cleanup around each tests. I also used the @After to append the exact query to rerun that exact failing scenario. This has been used to try to reproduce issues that appeared on automation environments. The code looks like:
```
@After()
public void tearDown(Scenario scenario) {
    if (scenario.isFailed()) {
        scenario.write(String.format("./gradlew clean test [...]");
    }
    // More data cleanup after
    [...]
}
```

This, in the Cucumber.xml report, showed up as
```
./gradlew clean test [...]

Given data setup ...................................................passed
When some action is performed............................failed
Then something happens......................................skipped
```

After replacing my Cucumber test run with a Courgette test run, this scenario.write() seems to no longer be doing anything. However, the tearDown method is clearly called since the data cleanup is properly executed.

Do you have any clue what could be causing this? Your help would be highly appreciated as this is a nice to have that we've gotten used too.

Thanks!

**Comment by prashant-ramcharan** [comment]
Hello,

Courgette does not change the behaviour of Cucumber so I'm not sure why this is causing an issue for you.

I was not able to reproduce this either. I tried with the Courgette example project and updated this line: https://github.com/prashant-ramcharan/courgette-jvm-example/blob/master/src/test/java/steps/TestSteps.java#L29

<img width="1420" alt="Screenshot 2019-05-22 at 19 43 51" src="https://user-images.githubusercontent.com/2563149/58200300-6cac9b00-7cca-11e9-9916-17f01470d63e.png">


<img width="1423" alt="Screenshot 2019-05-22 at 19 44 26" src="https://user-images.githubusercontent.com/2563149/58200305-6fa78b80-7cca-11e9-9377-5b4ea53dd1ac.png">

**Comment by papsicle** [comment]
I was actually looking for a way to get this information in the cucumber .xml export since that's what our previous tools what using.
However, I just discover the way to do that was actually to implement a custom JUnitFormatter and print that cucumber export file in a custom way (appending the line where it's needed).

Sorry to have bothered you with this, I didn't understand the framework properly.

Thanks for the fast response though!
