### ISSUE TITLE
Unable to download  courgette  jar from jcenter 

### ISSUE THREAD

**Issue by JeffGaly** [prashant-ramcharan/courgette-jvm#119]
Hi Prashant ,

Im unable to download the courgette jar from jcenter since i dont have an access from my client machine .If possible can you add in maven repo so that i can utilize and execute parallel execution .

So i utilized your jar by downloading it and added  in build path and declared  cucumber related jar  in dependencies to execute my parllel execution 

 compile 'io.cucumber:cucumber-java8:4.3.0'
  compile 'io.cucumber:cucumber-java:4.3.0'
  compile 'io.cucumber:cucumber-core:4.3.0'
 compile 'io.cucumber:cucumber-junit:4.3.0'

I felt due to this im unable to see the courgette report for all 4 features as it shows to only one feature .

My current gradle :

dependencies {

  testCompile 'junit:junit:4.12'
  compile 'org.seleniumhq.selenium:selenium-java:3.141.59'
  testCompile 'org.hamcrest:hamcrest-all:1.3'
compile 'io.cucumber:cucumber-java8:4.3.0'
compile 'io.cucumber:cucumber-java:4.3.0'
compile 'io.cucumber:cucumber-core:4.3.0'
 compile 'io.cucumber:cucumber-junit:4.3.0'
 compile fileTree(dir: 'jars', include: '*.jar')
// compile 'io.github.prashant-ramcharan:courgette-jvm:3.1.0'
}
 under jars i added your courgette jar .

**Comment by prashant-ramcharan** [comment]
The library is also available in Maven.

https://search.maven.org/artifact/io.github.prashant-ramcharan/courgette-jvm/3.3.0/jar
