### ISSUE TITLE
runner class to execute features /scenarios in sequence

### ISSUE THREAD

**Issue by JeffGaly** [prashant-ramcharan/courgette-jvm#120]
Hi Prashant,

Can you help in sharing the runner file for sequence execution ?

**Comment by prashant-ramcharan** [comment]
Hello,

The order in which features / scenarios are picked up is determined by Cucumber.

Do you want to know if you can execute parallel features / scenarios in order?

However, if you simply need to run one after the other, you can set the threads to 1 in the Courgette runner.

**Comment by JeffGaly** [comment]
thank you :)
