### ISSUE TITLE
how to fix createprocess error=206 the filename or extension is too long in java 8

### ISSUE THREAD

**Issue by devbrath** [prashant-ramcharan/courgette-jvm#122]
Hi,

I am facing this issue. I am using JAVA 8 with courgettejvmVersion="3.3.0". Is it not possible to fix while we still continue to use JAVA 8.
[206_Error.txt](https://github.com/prashant-ramcharan/courgette-jvm/files/3636020/206_Error.txt)

**Comment by prashant-ramcharan** [comment]
Hello,

This is a known limitation on Windows OS and Courgette is unable to workaround this.

You can however use Courgette with a later version of Java which would resolve this issue on Windows OS.

**Comment by prashant-ramcharan** [comment]
You can now use Courgette version 4.3.4 with the new Courgette option:

````java
        shortenJavaClassPath = true
````
