### ISSUE TITLE
Is it possible to update the cucumber version to the latest version (currently 4.7.2)

### ISSUE THREAD

**Issue by Watster69** [prashant-ramcharan/courgette-jvm#123]
I currently have a cucumber project setup and running well but I want to expand to parallel and I've come across courgette-jvm which works really well but to use it I'll be downgrading from 4.7.2 to 4.3.0 which is a big downgrade.

Do you have any plans to upgrade to the latest version?

**Comment by prashant-ramcharan** [comment]
Hello,

I am planning on upgrading to Cucumber 5 which why I didn’t upgrade the cucumber version in Courgette for while.

If however there is a need to use cucumber version  4.7.2, I’ll look into how much work is needed.

**Comment by Watster69** [comment]
To be honest I have literally found a solution to my problem which unfortunately doesn't include courgette. So I wouldn't worry about looking into it for my benefit anymore and I completely understand waiting until version 5. Thanks anyway.

My solution is purely gradle based. It does a dry run with any specified tags and using a custom formatter to write to a file the feature filepath and line number of all the scenarios and outlines which would be run based on the specified tags. This file is then stored as an array and then GParsPool.withPool iterates the scenarios array with the specified number of threads.
