### ISSUE TITLE
Can we run 2 different tags in parallel

### ISSUE THREAD

**Issue by LearningPur** [prashant-ramcharan/courgette-jvm#128]
First of all thank you so much for all your hard word to provide such a library thru which we can run cucumber feature and scenario in parallel. Really really appreciated for your help.

I am using your library in my project and it works like a charm. Thanks for that.

I have requirement to run multiple tags in parallel. Is it possible ?

Example : I want to run @Register_new_user and @Login_User 2 tags at same time instead of just passing 1 tag. 

I tried with but someone it simply not running anything when i pass multiple tag.

Thanks
Vinit

**Comment by prashant-ramcharan** [comment]
Hello,

You can indeed run multiple tags at the same time.

In your Courgette runner, simply update the tags to:

````java
tags = {"@Register_new_user or @Login_User"}
````

You can also provide these tags dynamically by setting the following system property:

````java
-Dcucumber.tags="@Register_new_user or @Login_User"
````

**Comment by LearningPur** [comment]
Thanks you so mch @prashant-ramcharan  for providing solution, i will definitely give it a try.
