### ISSUE TITLE
Not working with Java8 lambada expression. If i remove this "courgette-jvm" library from my pom.xml it works

### ISSUE THREAD

**Issue by LearningPur** [prashant-ramcharan/courgette-jvm#129]
Hi @prashant-ramcharan , After spending my 3 days finally i gave up and brining this to your attention so you can help find a solution.

If i do NOT keep this "courgette-jvm" library in my pom.xml it works without any issue. but with this library it just stop working my execution, can you please help to find a solution on this.

**Runner** 

![runner](https://user-images.githubusercontent.com/57417403/68407853-e38b0280-0149-11ea-8299-deb2cc2415bb.png)

**StepDef**

![stepdef](https://user-images.githubusercontent.com/57417403/68407870-eede2e00-0149-11ea-84aa-446d306adc73.png)

**Feature file** 

![featurefile](https://user-images.githubusercontent.com/57417403/68407899-fb628680-0149-11ea-9456-43ff5602166d.png)

**Pom.xml**

**FYI, I have excluded cucumber-java8 library that is coming from "courgette-jvm" but still not working**

 <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>1.8</java.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <selenide.version>5.2.2</selenide.version>
        <aspectj.version>1.8.10</aspectj.version>
        <cucumber.version>4.7.2</cucumber.version>
        <allure.version>1.4.16</allure.version>
        <allure-cucumber.version>1.6.3</allure-cucumber.version>
        <allure-maven.version>2.8</allure-maven.version>
        <slf4j.version>1.7.21</slf4j.version>
    </properties>

    <repositories>
        <repository>
            <id>jcenter</id>
            <url>https://jcenter.bintray.com/</url>
        </repository>
    </repositories>

    <dependencies>

        <dependency>
            <groupId>io.github.prashant-ramcharan</groupId>
            <artifactId>courgette-jvm</artifactId>
            <version>4.0.1-snapshot</version>

            <exclusions>

                

            </exclusions>

        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java8</artifactId>
            <version>${cucumber.version}</version>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-picocontainer</artifactId>
            <version>1.2.5</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-testng</artifactId>
            <version>${cucumber.version}</version>
        </dependency>

        <dependency>
            <groupId>com.codeborne</groupId>
            <artifactId>selenide</artifactId>
            <version>${selenide.version}</version>
        </dependency>

        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>3.7.1</version>
            <scope>compile</scope>
        </dependency>

    </dependencies>

**Full Log** 

Connected to the target VM, address: '127.0.0.1:58840', transport: 'socket'
Feature: New User Register

  @FootLocker
  Scenario: Footlocker Test                                       # src/test/resources/features/newUser.feature:4
    Given I am on homepage with url "https://www.footlocker.com/" # null

  @FootLocker
  Scenario: FinalScore Test                                        # src/test/resources/features/newUser.feature:9
    Given I am on homepage with url "https://www.final-score.com/" # null
    And I click on Sign In link                                    # null

Undefined scenarios:
src/test/resources/features/newUser.feature:4 # Footlocker Test
src/test/resources/features/newUser.feature:9 # FinalScore Test

2 Scenarios (2 undefined)
3 Steps (3 undefined)
0m0.107s

You can implement missing steps with the snippets below:

@Given("I am on homepage with url {string}")
public void i_am_on_homepage_with_url(String string) {
    // Write code here that turns the phrase above into concrete actions
    throw new io.cucumber.java.PendingException();
}

@Given("I am on homepage with url {string}")
public void i_am_on_homepage_with_url(String string) {
    // Write code here that turns the phrase above into concrete actions
    throw new io.cucumber.java.PendingException();
}

@Given("I click on Sign In link")
public void i_click_on_Sign_In_link() {
    // Write code here that turns the phrase above into concrete actions
    throw new io.cucumber.java.PendingException();
}

Disconnected from the target VM, address: '127.0.0.1:58840', transport: 'socket'

courgette.runtime.CourgetteTestFailureException: There were failing tests. Refer to the Courgette html report for more details.

===============================================
Default Suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================

Process finished with exit code 0

**Comment by prashant-ramcharan** [comment]
Hello,

1. Is there a reason why you excluding the Cucumber dependancies from Courgette?

2. What {cucumber.version} are you using?

**Comment by LearningPur** [comment]
Thanks for your quick reply @prashant-ramcharan 

Reason for excluding was to recognize feature steps and allow to navigate to stepdef thru short cut ctrl + click

If i go without excluding feature steps are not recognizing with latest cucumber version 5.0.0-RC1.

**Pom.xml**

![Screen Shot 2019-11-07 at 2 45 36 PM](https://user-images.githubusercontent.com/57417403/68426379-9fa9f480-016d-11ea-851f-0f11d866318e.png)

****StepDef** : As you can see i tried with both approach Java and Java8** 

![Screen Shot 2019-11-07 at 2 42 28 PM](https://user-images.githubusercontent.com/57417403/68426424-b6e8e200-016d-11ea-9e8b-3f64d564d1b3.png)

**Feature file : Steps are not recognized even though stepDef is available for specific step**

![Screen Shot 2019-11-07 at 2 42 37 PM](https://user-images.githubusercontent.com/57417403/68426489-e0097280-016d-11ea-8670-241890603600.png)

If i exclude the cucumber dependency coming from your library it DOES recognize the feature step but not working, error you can see in my 1st comment i shared.

Thanks
Vinit

**Comment by LearningPur** [comment]
@prashant-ramcharan  Thanks for you time again to reply back.

**_======= WITHOUT EXCLUDING ANY DEPENDANCIES =======_**

Please find attached below .zip file. With this you will be able to run both runners in runner package 1) MyRunner 2) CourgetteRunner. 

The only issue is Scenario Step is not getting recognized if you navigate to .feature file

[All_Dependencies_From_ Courgette.zip](https://github.com/prashant-ramcharan/courgette-jvm/files/3822471/All_Dependencies_From_.Courgette.zip)



**_=======EXCLUDING ALL CUCUMBER DEPENDANCIES =======_**

Please find attached below .zip file. With this you will be able to run MyRunner.java without any issue including .feature file scenario steps is getting recognized 

The only issue is when i run thru CourgetteRunner.java is throws an error.

[All_Cucumber_Dependencies_Excluded_From_ Courgette.zip](https://github.com/prashant-ramcharan/courgette-jvm/files/3822473/All_Cucumber_Dependencies_Excluded_From_.Courgette.zip)

**Comment by prashant-ramcharan** [comment]
Hello,

I tried with the project in **All_Dependencies_From_ Courgette.zip** and it works fine.

<img width="1379" alt="courgette_issue_129" src="https://user-images.githubusercontent.com/2563149/68494231-f682fd00-0245-11ea-828e-65a2730eb612.png">

**Comment by prashant-ramcharan** [comment]
It looks like you using a deprecated package.

Make sure you using the `io.cucumber.java8.En` package

````java
import io.cucumber.java8.En;

public class MyStepdefs implements En {
    // your Java 8 steps
}
`````

**Comment by LearningPur** [comment]
@prashant-ramcharan  It works for me as well that's what i have mentioned in my msg. Issue is if you open the .feature file (newUser.feature) you will come to know steps are grayed out and it says "No declaration found to go to" even though StepDef is available.

Please go to .feature file and see if steps are showing as implemented or not.

Thanks
Vinit

**Comment by prashant-ramcharan** [comment]
Okay now I understand :)

The IntelliJ plugin for the latest version of Cucumber is not ready so this is why steps cannot be found when you try to execute a feature file from the IDE. 

**This is not a Courgette issue** and you will notice that if you use Cucumber version 5.0.0-RC1  in your project you will face the same issue.

In the meantime, you can use **Courgette version 3.3.0**
