### ISSUE TITLE
Customized cucumber report with html tag doesn't reflect the same changes in " Courgette-JVM Html Report "

### ISSUE THREAD

**Issue by LearningPur** [prashant-ramcharan/courgette-jvm#130]
With html tag i have modified color for some text in default cucumber html report that shows as expected but when i open same report using " Courgette-JVM Html Report " that particular change doesn't reflect in there.

![Screen Shot 2019-11-11 at 12 08 03 PM](https://user-images.githubusercontent.com/57417403/68609982-4f3bdb00-047c-11ea-82e2-4a8d13447e7c.png)

**Default cucumber html report** 

![Screen Shot 2019-11-11 at 12 07 23 PM](https://user-images.githubusercontent.com/57417403/68610046-75fa1180-047c-11ea-80de-bf4af7b00959.png)

**Courgette-JVM Html Report**

![Screen Shot 2019-11-11 at 12 07 43 PM](https://user-images.githubusercontent.com/57417403/68610066-84e0c400-047c-11ea-8f64-c849de252f45.png)

Thanks
Vinit

**Comment by prashant-ramcharan** [comment]
Thanks for letting me know. I'll look into this.

**Comment by LearningPur** [comment]
Hi @prashant-ramcharan if possible can we please have this change asap as i am gonna submit my framework to the management for final review and since your library is really awesome and helped me a lot i just didn't want to let it go from this stupid management.

Thanks
Vinit

**Comment by prashant-ramcharan** [comment]
I can add support for this but it will be released in version 4.0.2-snapshot.

This will not work if you using version 3.3.0.

**Comment by LearningPur** [comment]
Oh i see, Yeah i remember there is an issue already logged with latest Cucumber version 5.0.0 RC where scenario steps are not getting recognized. In meantime can you please release 4.02 version i will give it a try if that works or not.

Thanks
Vinit

**Comment by prashant-ramcharan** [comment]
You can now try with **4.0.2-snapshot**

**Comment by LearningPur** [comment]
Wow, Your so fast. Thank you so much @prashant-ramcharan really really appreciated.

**Comment by LearningPur** [comment]
@prashant-ramcharan  I have upgraded to 4.0.2-snapshot and that has resolved html text issue. Thank you so much
