### ISSUE TITLE
Does the generated report has the success/failed screenshots linked in the report?

### ISSUE THREAD

**Issue by RArkasali** [prashant-ramcharan/courgette-jvm#133]
PN: This is not an issue, it's a query or question.

This library sounds pretty cool, and we are thinking to add to our selenium project. Please can you confirm that the output report has the screenshots tagged to the executed steps in the report.

For example:
1) Step1: ABC passed (on click should show the screenshot)
2) Step2: XYZ failed (on click should show the screenshot)

So that the browser screen error can be viewed. Kindly confirm.

**Comment by prashant-ramcharan** [comment]
Hello,

Yes, screenshots are included in the Courgette Html Report and are shown on steps.

You can use the example project to see what  the report would looks like: https://github.com/prashant-ramcharan/courgette-jvm-example

**Comment by RArkasali** [comment]
Thanks prashant, but it seems like your selenium project is not working for both the scenarios. The browser ran only one script i,e the stackoverflow it didn't ran the github in parallel to stackoverflow. Though the tags are same for both the scenarios. Please can you check and help with the fix.

**Comment by prashant-ramcharan** [comment]
If you run a single Courgette runner with multiple tags then you will have **1 report**. 

To archive what you need, you can:

1. Have single Courgette runner and run it multiple times with different run arguments

````java
// in your build.gradle
task regressionTests(type: Test) {
    include '**/RegressionTestSuite.class'
    outputs.upToDateWhen { false }
}

// run from the command line
gradle regressionTests -Dcourgette.reportTargetDir=build\scenarios1-report -Dcucumber.tags=@scenarios1

gradle regressionTests -Dcourgette.reportTargetDir=build\scenarios2-report -Dcucumber.tags=@scenarios2
````

2. Have multiple Courgette runners and run them all at once.
````java
@RunWith(Courgette.class)
@CourgetteOptions(
       // other opts
        reportTargetDir = "build\scenarios1-report",
        cucumberOptions = @CucumberOptions(
                tags = {"@scenarios1"},
        ))
public class RegressionScenario1 {
}

@RunWith(Courgette.class)
@CourgetteOptions(
       // other opts
        reportTargetDir = "build\scenarios2-report",
        cucumberOptions = @CucumberOptions(
                tags = {"@scenarios2"},
        ))
public class RegressionScenario2 {
}
````

And yes, you can and **should** run tests in docker containers.

**Comment by RArkasali** [comment]
That's great Prashant.
