### ISSUE TITLE
is it possible to append scenario failed screenshot using "base64" ?

### ISSUE THREAD

**Issue by LearningPur** [prashant-ramcharan/courgette-jvm#134]
Hi @prashant-ramcharan is it possible we can append failed screenshot in courgette-jvm html report using "base64" so even if saved .png file gets deleted it still remain and visible in html report?

I tried with below code but somehow it's not working. If you can please provide some solution. 

I have latest version of courgette-jvm which is 4.0.2

  String scrBase64 = ((TakesScreenshot) getSelenideDriver().getWebDriver()).getScreenshotAs(OutputType.BASE64);

 byte[] base64Val= Base64.decodeBase64(scrBase64);
 scenario.embed(base64Val, "data:image/png;base64,");

**Comment by prashant-ramcharan** [comment]
Try:
````java
 TakesScreenshot screenshot = ((TakesScreenshot) getSelenideDriver().getWebDriver());

 scenario.write(screenshot.getScreenshotAs(OutputType.BASE64));
````

**Comment by prashant-ramcharan** [comment]
This is not currently supported in Courgette but images are saved prior to creating the report.

**Comment by LearningPur** [comment]
Yes, i just now tried with the 2 line code you have provided above and it didn't work. PFB screenshot of it what i am seeing in report. 

![Screen Shot 2019-11-15 at 1 01 19 PM](https://user-images.githubusercontent.com/57417403/68968480-4282f400-07a8-11ea-8bcd-a9ccb45a136d.png)

Any other solution you can provide ?

**Comment by prashant-ramcharan** [comment]
The Courgette html builder does not currently embed base64 images in the report.

As a backup, if for some reason your images are deleted, you could always refer back to the Cucumber report which would have the base64 encoded image.

**Comment by prashant-ramcharan** [comment]
Actually, you could just embed the image to the report using text/html.

Example:

````java
    TakesScreenshot screenshot = (TakesScreenshot) driver;
            
    String base64Image = screenshot.getScreenshotAs(OutputType.BASE64);
    byte[] htmlImage = ("<img class=\"col-lg-12\" src=\"data:image/png;base64,"  + base64Image + "\">").getBytes();
    
    scenario.embed(htmlImage, "text/html");
````

**Comment by LearningPur** [comment]
Let me try this.

**Comment by LearningPur** [comment]
Cool, it works like a charm. Thank you so much @prashant-ramcharan  you rock. Appreciated for all your hard work. Hats off to you bro.
