### ISSUE TITLE
Is it possible to attach courgette-report.html report with jenkins build 

### ISSUE THREAD

**Issue by LearningPur** [prashant-ramcharan/courgette-jvm#135]
Hi @prashant-ramcharan can i attach **courgette-report.html** report with jenkins build at the end of execution so it can be viewed from jenkins only.

Thanks
Vinit

**Comment by prashant-ramcharan** [comment]
Yes, you can use the following Jenkins plugin:

https://wiki.jenkins.io/display/JENKINS/HTML+Publisher+Plugin
