### ISSUE TITLE
Can we customize courgette html report using some config file or something ?

### ISSUE THREAD

**Issue by LearningPur** [prashant-ramcharan/courgette-jvm#136]
Hi @prashant-ramcharan is there a way we can customize courgette html report using some config file or something ?

Like an example if you heard of an html report "Extent Report" that provides .xml file thru which we can add report name, company logo etc. Can we do same for courgette html report ?

I need to add Custom report name like "FootLocker Automation Report" with company logo.

Thanks
Vinit

**Comment by prashant-ramcharan** [comment]
No, there are no plans to support this.

**Comment by LearningPur** [comment]
Okay thanks

**Comment by prashant-ramcharan** [comment]
You are welcome to raise a PR though.

**Comment by LearningPur** [comment]
Alright, will try

**Comment by LearningPur** [comment]
@prashant-ramcharan is it possible at least to change report header text and add log in courgette html report ?

![Screen Shot 2019-11-15 at 2 37 31 PM](https://user-images.githubusercontent.com/57417403/68974175-b1b31500-07b5-11ea-8796-92d9d667127e.png)

**Comment by prashant-ramcharan** [comment]
I suggest you write your own custom html report to meet your requirements.

Courgette uses the data from the cucumber json report so you could write your own report to consume this data as well.
