### ISSUE TITLE
with latest courgette-jvm version 4.0.2 and running test in parallel with specific tag from jenkins runs all scenario from feature file

### ISSUE THREAD

**Issue by LearningPur** [prashant-ramcharan/courgette-jvm#138]
Hi @prashant-ramcharan  Today i discovered very weird issue.

Running test in parallel with tag in local runs **as expected** like an example if i run below maven command. It opens 2 browser in parallel and run 2 scenario as tag @Debug_New_Single_User linked with 2 scenarios

mvn clean test -Drunner.name=CourgetteRunner.java -Dcourgette.threads=2 -Dcourgette.runLevel=SCENARIO -Dcucumber.tags="@Debug_New_Single_User"

But when i run same maven command from jenkins **_"IT EXECUTE ALL SCENARIOS WHICH ARE IN FEATURE FILE"_**. Here feature file i am talking about is having 10 scenarios and those all runs in parallel instead of specific tag i want to run which is "@Debug_New_Single_User"

![Screen Shot 2019-11-18 at 11 49 00 AM](https://user-images.githubusercontent.com/57417403/69076585-6d17bb80-09f9-11ea-9408-f9772e4520f0.png)

In runner i have commented those lines which i am passing thru argument 

![Screen Shot 2019-11-18 at 11 50 41 AM](https://user-images.githubusercontent.com/57417403/69076706-a3553b00-09f9-11ea-9a11-bec001245272.png)

And this is what i have in my pom.xml file under build tag

<build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.21.0</version>
              
                <configuration>
        
                    <includes>  
                        
                        <include>${runner.name}</include>  

                    </includes>

                </configuration>
            </plugin>
        </plugins>
    </build>

**Comment by prashant-ramcharan** [comment]
Move all the system properties from MAVEN_OPTS to the Goals and options field in Jenkins.

````
clean test -Drunner.name ...
````

**Comment by LearningPur** [comment]
Yes, it's working now thanks @prashant-ramcharan
