### ISSUE TITLE
Courgette Html report with broken experience after uploading with jenkins build using "Publish Html report" plugin

### ISSUE THREAD

**Issue by LearningPur** [prashant-ramcharan/courgette-jvm#139]
Hi @prashant-ramcharan I have attached Courgette Html report with my jenkins build using "Publish Html report" plugin and i am seeing broken experience as below

1) Graph is missing
2) On click on Scenario to get result nothing happens (it doesn't open test result)

![Screen Shot 2019-11-18 at 3 17 16 PM](https://user-images.githubusercontent.com/57417403/69094939-f12c6c00-0a16-11ea-81f8-212c85ba3f33.png)

![Screen Shot 2019-11-18 at 3 17 30 PM](https://user-images.githubusercontent.com/57417403/69095029-1faa4700-0a17-11ea-9a55-6a5f4e64fc24.png)

**Comment by prashant-ramcharan** [comment]
Hello,

Unfortunately, this is not related to Courgette and I'm unable to resolve issues with Jenkins plugins which I've not created.

Please only raise issues directly related to Courgette. 

Thanks

**Comment by prashant-ramcharan** [comment]
Perhaps take a look at https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy#ConfiguringContentSecurityPolicy-HTMLPublisherPlugin

**Comment by LearningPur** [comment]
Sorry, i thought if that works in local it should also work in Jenkins. Sorry if i made a mistake creating an issue for this.

**Comment by prashant-ramcharan** [comment]
It's most likely a configuration issue in your Jenkins that is not allowing JavaScript. Looks related to this https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy

**Comment by LearningPur** [comment]
Sorry man if i am keep bothering you and unnecessary raising an issue where i should not but you know what i really like this library Courgette

**Comment by LearningPur** [comment]
Thanks @prashant-ramcharan  i will see if that helps to resolved an issue. Thanks for your time though.
