### ISSUE TITLE
courgette html report that display Before and After hooks with full folder structure and path where frameworks is located at.

### ISSUE THREAD

**Issue by LearningPur** [prashant-ramcharan/courgette-jvm#140]
@prashant-ramcharan  First of all i am sorry if this is not related to courgette please forgive me. 
Also this might not be an issue if so please consider it as just an question which i need a help for.

In screenshot below if you look at it below, it display Before and After hooks with path, can we modify it to just display Before and After hooks. Our management doesn't want us to share this kind of information in any report.

![Screen Shot 2019-11-19 at 2 50 25 PM](https://user-images.githubusercontent.com/57417403/69186201-b5a8a500-0add-11ea-8d66-4d53d2c0fb6e.png)

**Comment by prashant-ramcharan** [comment]
This data is set by Cucumber and not Courgette. 

Please take a look at the `cucumber.json` in your project. Courgette simply uses the data that Cucumber provides.

<img width="654" alt="Screenshot 2019-11-19 at 21 47 59" src="https://user-images.githubusercontent.com/2563149/69189466-5450f800-0b16-11ea-99e9-797e8e90565b.png">

**Comment by prashant-ramcharan** [comment]
This issue might be fixed when Cucumber releases version 5.0.0 at which point I will upgrade the dependancy within Courgette.

**Comment by LearningPur** [comment]
Is there a way we can modify that .json data before Courgette html report using it to display in the form of UI ? If you can please share some idea that will be great.

Thanks

**Comment by prashant-ramcharan** [comment]
I will remove the file path.. most likely next week though.

**Comment by LearningPur** [comment]
Thank you so much @prashant-ramcharan that will really helpful.

My question is still not been answered if you can please ? Will courgette html report gets created (index.html) once report.json file available inside courgette-report/data folder ?

Reason i am asking is there are some other json keys i want to modify and display it in html report.

What i am thinking is once all all feature files gets executed @AfterSuite will gets triggered since i am using TestNG and inside that i can write code to modify report.json before index.html gets created so that changes can take place in html report.

Thanks & Regards.

**Comment by prashant-ramcharan** [comment]
Hello,

No, you cannot. 

The way that it works is that once all tests are complete, the multi threaded reports (_which was created during the parallel test execution_) are parsed and combined into a single report / file. At this point, the Courgette html report is also created based on the data that's included in the combined cucumber.json report.

https://github.com/prashant-ramcharan/courgette-jvm/blob/master/src/main/java/courgette/api/junit/Courgette.java#L49-L50

So you cannot update the json report which technically wouldn't exist whilst your tests are executing.

Hope that answer your question.

**Comment by LearningPur** [comment]
Thanks for explaining in detail. Appreciated. 

In that case i will wait until you release this change in your next version.

**Comment by prashant-ramcharan** [comment]
Had some time to do a release, so you can now use Courgette `4.0.3-snapshot`

**Comment by LearningPur** [comment]
Thank you so much dude. You are really pretty quick. Appreciated from my bottom of heart. Thanks a ton.

Thanks

**Comment by LearningPur** [comment]
I have upgraded Courgette with 4.0.3 and after that it works like a charm @prashant-ramcharan thanks for your time to make this change.

I also like this which was not in prior version. On click on feature it expand to scenario level. Thanks much to introduce this.

![Screen Shot 2019-11-21 at 9 58 59 AM](https://user-images.githubusercontent.com/57417403/69354463-c2480d00-0c45-11ea-8206-def6be79a8ac.png)

**_Since you made this change can you please allow to change header label and to add company logo, please forgive me if i am asking stupid question but if that allows then i will get credit (ultimately that credit all goes to you) here in this company and it will become standard for all our rest of 278 projects and on that all this report will become mandatory._**

**Comment by prashant-ramcharan** [comment]
> I also like this which i didn't know running as FEATURE it will create group. On click of feature it expand to scenario level. Thanks much.

I did not make this change now, it's been like this from the first time the Courgette html report was introduced.

**Comment by LearningPur** [comment]
Thanks @prashant-ramcharan 

Can you answer this if it you can please.

**_Since you made this change can you please allow to change header label and to add company logo, please forgive me if i am asking stupid question but if that allows then i will get credit (ultimately that credit all goes to you) here in this company and it will become standard for all our rest of 278 projects and on that all this report will become mandatory._**

**Comment by prashant-ramcharan** [comment]
Unfortunately, there's no scope of doing this at the moment. 

Courgette was created to parallelise tests on a feature and scenario level and this is the core feature of the library. I created the Courgette html report to better visualise the results returned by Cucumber, that's all. It was not meant to be customisable.

I think we'd probably need to extract the Courgette html report into it's own library so that we can support a richer set of features like yours but I don't have any plans (_or enough time_) to do this at present.

**Comment by LearningPur** [comment]
Thanks much @prashant-ramcharan for your time and replying back.

I totally understand how busy you will be. The reason i asked you that question was when i had demo with my management last week and when i showcase this reporting they were amazed looking at this and only change that asked was to add their company name with Logo and i said i will see that is possible. If this doesn't work out they might won't let me processed with this reporting as there is no company name and logo. 

Anyway thanks for your time again. Appreciated.

**Comment by prashant-ramcharan** [comment]
Sounds like you company wants a bespoke report and not one that is open source.

>Anyway thanks for your time again. Appreciated.
No problem

**Comment by LearningPur** [comment]
No, it's not that. They are in very much favor of open source only. In fact, All our automation tool we have in house are open source. Just that they want their name and logo on report so they can preset it to out side party when it times and they don't question.

Thanks
