### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: io/cucumber/core/snippets/SnippetType

### ISSUE THREAD

**Issue by mjm987mj** [prashant-ramcharan/courgette-jvm#143]
Hi,

When trying to execute my runners I get the following exception:

Exception in thread "main" java.lang.NoClassDefFoundError: io/cucumber/core/snippets/SnippetType

I tried adding the cucumber core as a separate dependency (eventhough it is been packaged with yours) but still no luck.

Could you help me with this?

Thanks in advance,

Mrk

**Comment by prashant-ramcharan** [comment]
Hello,

What version of Courgette are you using?

**Comment by mjm987mj** [comment]
I’m using the latest which comes packaged with cucumber 5 RC 1. I’ll try with one version earlier to see what happens.

Thanks!

**Comment by prashant-ramcharan** [comment]
If you have any declared cucumber dependancy in you `build.gradle` or `pom.xml` then please remove it and try again.
