### ISSUE TITLE
Question for "courgette-jvm-selenium" sample project

### ISSUE THREAD

**Issue by LearningPur** [prashant-ramcharan/courgette-jvm#144]
Hi @prashant-ramcharan in one of your sample project "courgette-jvm-selenium" thru which we can run test in parallel on 2 different browser. In that project you have used "gradlew" with shell script to run test on 2 different browser. Since i am having framework based on Maven can you please provide a script or solution that i can use to run same cucumber scenario on 2 different browser Chrome and Firefox in parallel.

**Comment by prashant-ramcharan** [comment]
Please use Google or StackOverflow to find out how to run bash scripts from maven.

This should help: https://stackoverflow.com/questions/8433652/is-it-possible-to-run-a-bash-script-from-maven/8433726

I kindly ask that Courgette only issues be raised here.

**Comment by LearningPur** [comment]
Okay Thanks @prashant-ramcharan  and sorry to raise this issue here. I thought raising it to here will be quicker reply from your side.

**Comment by prashant-ramcharan** [comment]
Sure, no problem. 

If your question is Courgette related, I’d be happy to help but this a more general “how to” question on maven and running shell scripts.
