### ISSUE TITLE
Why doesn't this work copy jar package to project instead of download form maven repository

### ISSUE THREAD

**Issue by shellphxiao** [prashant-ramcharan/courgette-jvm#147]
since my server has some network issues, I want to manually download the jar package from maven and set it to my project, After that, when I ran my project, it does not work, these class can not be found, Could you pls tell me what can I do, very thanks!!!
![image](https://user-images.githubusercontent.com/42022737/70038954-0fd45a80-15f4-11ea-9685-a51b233375a0.png)
![image](https://user-images.githubusercontent.com/42022737/70039070-3befdb80-15f4-11ea-9600-0e3fa24ba340.png)

I did this
`<dependency>
            <groupId>io.github.prashant-ramcharan</groupId>
            <artifactId>courgette-jvm</artifactId>
            <version>3.1.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/src/test/resources/courgette-jvm-3.1.0.jar</systemPath>
        </dependency>`

and removed this
<dependency>
            <groupId>io.github.prashant-ramcharan</groupId>
            <artifactId>courgette-jvm</artifactId>
            <version>3.1.0</version>
        </dependency>

**Comment by prashant-ramcharan** [comment]
Hello,

When you just declare the Courgette dependancy in your pom.xml then all transitive dependancies are downloaded too but as you now just downloading in the Courgette jar file then you'd need to include the following dependancies in your pom file too.
You should add the below dependancies to your pom.xml.

````
cucumber-core 4.2.0
cucumber-java 4.2.0
cucumber-java8 4.2.0
cucumber-junit 4.2.0
jackson-databind 2.8.8
````

**Comment by shellphxiao** [comment]
Thank you very much, It works.
