### ISSUE TITLE
Why surfire reports generate on suite level after run courgette runner?

### ISSUE THREAD

**Issue by ReyyanArik** [prashant-ramcharan/courgette-jvm#148]
Hello,
I wanna use Allure report with courgette. But allure-report or surefire-report created by Suite Level after run CourgetteRunner class by manually or run by command below.
I am using TestNG and maven. And here is my command:

mvn clean test -Dcucumber.options="--tags '@C395278 or @C395290' --plugin io.qameta.allure.cucumber2jvm.AllureCucumber2Jvm"

After running this command, I expect that surefire report to show scenarios which contains these tags. But report contains only "parallelRun" suite and does not show scenarios like courgette report.

Here is allure-reports screenshot:
<img width="1667" alt="Screen Shot 2019-12-10 at 09 59 55" src="https://user-images.githubusercontent.com/8184343/70504131-20c22600-1b36-11ea-972d-11b9d4b85bf4.png">

Here is courgette-report:
<img width="1636" alt="Screen Shot 2019-12-10 at 10 17 48" src="https://user-images.githubusercontent.com/8184343/70504255-68e14880-1b36-11ea-9735-d67ade6ab223.png">

What should I do in order for Allure-report or Surefire-report to be generated like courgette-report?

**Comment by prashant-ramcharan** [comment]
Hello,

The way the TestNG Courgette runner works is that `parrallelRun` test is needed to start all other tests in the suite.

https://github.com/prashant-ramcharan/courgette-jvm/blob/master/src/main/java/courgette/api/testng/TestNGCourgette.java#L41

So to your IDE this is the only test it thinks gets run. This is why the allure-report shows just the 1 test.

Unfortunately, there's no way around this within Courgette.

**Comment by ReyyanArik** [comment]
I Understood @prashant-ramcharan thank you :ok_hand:
