### ISSUE TITLE
Getting thread count

### ISSUE THREAD

**Issue by ubobur95** [prashant-ramcharan/courgette-jvm#149]
Is there a way to get thread count on runtime?

**Comment by prashant-ramcharan** [comment]
Not unless you set the system property `courgette.threads` at runtime in which case you get the value using `System.getProperty`

What the use case for needing to know the thread count at runtime?

**Comment by ubobur95** [comment]
I use this for mobile automation. It helps out to know the thread count and maybe even change on runtime. To run automation on emulators or simulators, there are limited numbers of devices.

**Comment by ubobur95** [comment]
I am able to use it even without it. It was just a question. thanks
