### ISSUE TITLE
-Dcourgette.vmoptions="-Xms256m -Xmx512m"

### ISSUE THREAD

**Issue by neo81-83** [prashant-ramcharan/courgette-jvm#153]
Does this mean that each of the individual threads will run with the above configuration OR whether all of the threads will have to accommodate within min. and max. values allotted?

**Comment by prashant-ramcharan** [comment]
Each thread would use these values.

**Comment by neo81-83** [comment]
Thanks @prashant-ramcharan for the clarification.
