### ISSUE TITLE
I am facing issue by using 'or' condition in courgette runner.

### ISSUE THREAD

**Issue by Suruchi-mindstix** [prashant-ramcharan/courgette-jvm#154]
tags = {"@search, @login"},

None of the test case is getting executed.

**Comment by prashant-ramcharan** [comment]
Try

````java
tags = { "@search or @login" }
````

**Comment by Suruchi-mindstix** [comment]
Thanks alot prashant, I tried the same as you have mentioned. But it did not work. Please suggest other solution.

**Comment by prashant-ramcharan** [comment]
Unfortunately this is outside Courgette. 

Cucumber loads the features based on the tags that are specified so this seems like you have project configuration issue.

https://github.com/cucumber/cucumber/blob/master/tag-expressions/README.md

Please share a demo project and il take look.

**Comment by Suruchi-mindstix** [comment]
@RunWith(Courgette.class)
@CourgetteOptions(
	    runLevel = CourgetteRunLevel.SCENARIO,
	    showTestOutput = true,
	    rerunFailedScenarios = false,
	    threads = 2,
	    cucumberOptions = @CucumberOptions(
	    		  features = {featurefile address},
	    		tags = { "@search or @login" }
	    		  dryRun = false,
	    		  strict = true,
	    		  monochrome=true,
	    		  glue = {"package name"},
	    		 
	    		))

I have two feature files, tagged one as @login and other as @search

**Comment by prashant-ramcharan** [comment]
The runner looks fine. Do you have the same issue with this: https://github.com/prashant-ramcharan/courgette-jvm-example

**Comment by prashant-ramcharan** [comment]
If each feature only has one or the other tag then you should use:

````java
tags = { "@search and @login" }
````

**Comment by prashant-ramcharan** [comment]
If each feature only has one or the other tag then you should use:

````java
tags = { "@search and @login" }
````

**Comment by prashant-ramcharan** [comment]
https://github.com/prashant-ramcharan/courgette-jvm/issues/45
