### ISSUE TITLE
 initializationError FAILED

### ISSUE THREAD

**Issue by lakshmanp21** [prashant-ramcharan/courgette-jvm#156]
java -version
java version "12.0.2" 2019-07-16
Java(TM) SE Runtime Environment (build 12.0.2+10)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)

runTestsParallel cannot pick tests from feature file

@RunWith(Courgette::class)
@CourgetteOptions(
        threads = 2,
        runLevel = CourgetteRunLevel.FEATURE,
        rerunFailedScenarios = false,
        showTestOutput = true,
        reportTargetDir = "build",
        cucumberOptions = courgette.api.CucumberOptions(
                features = ["src/test/resources/"],
                glue = ["com.xxxx.xxxx_erp.stepdefs", "src/test/resources/"],
                tags = ["@system"],
                plugin = ["pretty", "html:build/reports/html", "json:build/reports/json/report.json"],
                strict = true
        )
)

> Task :runTestsParallel FAILED
com.xxxx.xxxx_erp.RunErpTests > initializationError FAILED
    courgette.runtime.CourgetteException
        Caused by: java.io.FileNotFoundException
1 test completed, 1 failed
FAILURE: Build failed with an exception.

**Comment by lakshmanp21** [comment]
after looking at online searching, came to know `runTestsParallel` task is not supported in Windows machine, any workaround for this please ?

**Comment by prashant-ramcharan** [comment]
Hello @lakshmanp21 

Can you share a demo project that I can reproduce this issue?
