### ISSUE TITLE
ExtentSparkReporter change needs to make in Courgette

### ISSUE THREAD

**Issue by LearningPur** [prashant-ramcharan/courgette-jvm#157]
@prashant-ramcharan  I am creating this issue regarding the thread you are aware of which opened in extentreport. 

As per your comment in that thread **"Please wait for an updated version of Courgette as this will use the ExtentSparkReporter."** you can keep this issue open until you merge that change. 

https://github.com/extent-framework/extentreports-java/issues/120

**Comment by prashant-ramcharan** [comment]
@LearningPur This is now released in 4.3.0.

You can pull it down from jCenter in the mean time whilst I upload it to Maven Central.

**Comment by prashant-ramcharan** [comment]
You can simply do this now:

````java
getScenario.write("Scenario failed so capturing a screenshot");
            
TakesScreenshot screenshot = (TakesScreenshot) WebDriverRunner.getWebDriver();
byte[] base64Image = screenshot.getScreenshotAs(OutputType.BYTES);
            
getScenario.embed(base64Image, "image/png");
````

<img width="1368" alt="Screenshot 2020-02-07 at 22 55 13" src="https://user-images.githubusercontent.com/2563149/74071851-efae8680-49fc-11ea-827d-27db1af58f73.png">

**Comment by LearningPur** [comment]
Thanks much @prashant-ramcharan for releasing it too quick. 

Anything we need to change in Runner.java class apart from adding this extent report plugin ?

Thanks
Victor

**Comment by prashant-ramcharan** [comment]
Nothing to change in runner. Simply update the Courgette version and make changes to your code as noted here https://github.com/prashant-ramcharan/courgette-jvm/issues/157#issuecomment-583651301

**Comment by LearningPur** [comment]
cool, thanks much @prashant-ramcharan and again really appreciated for all your help. You really made my day Today.
