### ISSUE TITLE
Request : to update extent reports cucumber adapter version from 1.0.7 to latest 1.0.10 to generate only 1 report

### ISSUE THREAD

**Issue by LearningPur** [prashant-ramcharan/courgette-jvm#159]
Hi @prashant-ramcharan , Sorry to again bother you. I have logged an issue to extent report 

https://github.com/extent-framework/extentreports-cucumber4-adapter/issues/40

because with version 1.0.7 it creates 3 html files 1) dashboard.html 2) tag.html 3) index.html and when the time to send this report to someone it is forcefully required to send all these 3 .html files so anshoo requested to update version 1.0.10 that has latest change which will create only index.html.

I tried to exclude "extentreports-cucumber4-adapter" that is coming from "courgette" library, PFB screenshot of it but it seems heavy lifting part of generating extent report done by you "courgette" library when i run the code it throws "java.lang.NoClassDefFoundError: com/aventstack/extentreports/ExtentReporter".

![Screen Shot 2020-02-11 at 11 22 47 AM](https://user-images.githubusercontent.com/57417403/74261653-23b9ce00-4cc1-11ea-86b5-5cc856ee87e8.png)

![Screen Shot 2020-02-11 at 11 24 20 AM](https://user-images.githubusercontent.com/57417403/74261665-287e8200-4cc1-11ea-96ed-bcd0205255f2.png)

Can you please upgrade the version from 1.0.7 to 1.0.10.

**Comment by prashant-ramcharan** [comment]
Hi @LearningPur 

I will take a look.

**Comment by LearningPur** [comment]
Thanks much @prashant-ramcharan  as always your reply back so quick, Appreciated. 

Thanks
Victor

**Comment by prashant-ramcharan** [comment]
Hello @LearningPur 

You can now use Courgette version 4.3.1

**Comment by LearningPur** [comment]
So quick, Thanks much @prashant-ramcharan  It worked.

**Comment by prashant-ramcharan** [comment]
No worries. 

I will work on removing the adaptor and use the extent report dependancy directly and will try to fix the report timestamps.

No ETA on this at the moment though.
