### ISSUE TITLE
CourgetteRunner throws exception when no features/scenarios match the provided tag

### ISSUE THREAD

**Issue by epenap** [prashant-ramcharan/courgette-jvm#16]
The behavior of the default CucumberRunner is to return success when no features/scenarios are run for the provided tags; however, the CourgetteRunner throws an IllegalArgumentException when no scenarios/features match the provided tags and causes the test run to fail.

Specifically, the problem is in the following line in the CourgetteRunner run() method:

`final ExecutorService executor = Executors.newFixedThreadPool(optimizedThreadCount());`

In this case, the optimizedThreadCount() method is returning 0 Threads, which causes the exception.

Ideally the ExecutorService would only be initialized if there are tests that need to be run (e.g. there are features/scenarios that match the provided tags)

**Comment by prashant-ramcharan** [comment]
This exception is only thrown when the tests are executed via the Gradle task. You will notice that the error is not thrown when executing the runner directly (i.e. the Java class)

In any case, this is a simple fix -- thanks for letting me know.
