### ISSUE TITLE
Question Not an Issue (Please feel free to ignore if you want) : How to read feature name from feature file during runtime

### ISSUE THREAD

**Issue by LearningPur** [prashant-ramcharan/courgette-jvm#161]
Hi @prashant-ramcharan  Since Courgette library is reading feature name from feature file during runtime just curious if you can please share the solution how did you make it work. 

In my framework i have BrowserStack integrated and when i run "courgetteRunner.java" test runs on browserstack but i want to create a build based on FeatureName in browserstack so need a solution on how to read featurename from feature file during runtime. 

I know this is NOT related to courgette library at all and i accept that but i asked this question to stackoverrlow as well as cucumber-jvm github issue portal but it seems no one has time to reply so I thought if you can at least help here on this.

Please feel free if you don't want to answer at all.

**Comment by prashant-ramcharan** [comment]
In your test steps / hook, you can do something like this:

````java
    @Before
    public void before(Scenario scenario) {
        String featureName = scenario.getId(); // extract the Feature name from here
        String scenarioName = scenario.getName();
    }
````

**Comment by LearningPur** [comment]
Thanks @prashant-ramcharan For replying back.

This one i thought of it initially and tried but someone for me it returns feature file path instead of feature name.

I googled it and found this solution works with info.cucumber version but not io.cucumber.

PFB screenshot of it

![Screen Shot 2020-02-12 at 2 44 39 PM](https://user-images.githubusercontent.com/57417403/74375733-7ae59e80-4da6-11ea-88d2-0c452b98ea6f.png)

**Comment by prashant-ramcharan** [comment]
````java
    @Before
    public void before(Scenario scenario) {
    Parser<GherkinDocument> parser = new Parser<>(new AstBuilder());

    TokenMatcher matcher = new TokenMatcher();

    // this will give you access to the feature
    Feature feature = parser.parse(new FileReader(scenario.getUri().getPath()), matcher).getFeature();

    }

````

**Comment by LearningPur** [comment]
Hi @prashant-ramcharan Thanks for your quick reply.

I tried with the solution you have provided but it throws me "Null pointer exception" PFB screenshot

![Screen Shot 2020-02-12 at 10 04 02 PM](https://user-images.githubusercontent.com/57417403/74400562-e437d280-4de3-11ea-9e1d-80ad21884011.png)

When i look for what it returns with this line "scenario.getUri().getPath();" then i found it is Null that, PFB screenshot.

![Screen Shot 2020-02-12 at 10 07 26 PM](https://user-images.githubusercontent.com/57417403/74400652-34169980-4de4-11ea-8fa9-4c0fccfdab4d.png)

Thanks
Victor

**Comment by LearningPur** [comment]
Thanks @prashant-ramcharan It worked. Thanks for your help, Appreciated.
