### ISSUE TITLE
The filename or extension is too long is error throwing when having more dependencies

### ISSUE THREAD

**Issue by vignesmuruges** [prashant-ramcharan/courgette-jvm#163]
I am working in a large project with many dependencies while integrating courgette with this project i am experiencing this problem error is throwing in CourgetteFeatureRunner class . Kinldy provide a solution for me

**Comment by prashant-ramcharan** [comment]
Can you please provide more information?

1. What is the exact error message?
2. What version of Courgette at you using?
3. What version of Java are you using?
4. What OS are you using?
5. How long are the filenames (character length)?

**Comment by vignesmuruges** [comment]
1. The Exact Error Message is 
Cannot run program "java": CreateProcess error=206, The filename or extension is too long
2.I am using the version 3.3.3
3. Java version is 1.8
4.OS is Windows 10 pro
5. the file name length in characters will be 14158 and I had added 97 different jars

I had fix it in my local like in the class CourgetteFeatureRunner.java the method getClassPath() returns the string of added dependencies, this is of the length 14158. So I had write a method which will copy all the respective jars into a temp folder and add the path of that temp folder to the getClassPath() method. It is working fine for me . 

package csps.courgette.runtime;


import org.apache.commons.io.FileUtils;

import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.net.URLClassLoader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

import static courgette.runtime.utils.SystemPropertyUtils.splitAndAddPropertyToList;

public class CourgetteFeatureRunner {
    private Map<String, List<String>> runnerArgs;
    private Boolean output;

    public CourgetteFeatureRunner(Map<String, List<String>> runnerArgs, Boolean output) {
        this.runnerArgs = runnerArgs;
        this.output = output;
    }

    public int run() {
        Process process = null;
        try {
            final ProcessBuilder builder = new csps.courgette.runtime.CourgetteFeatureRunner.Builder().buildProcess();
            process = builder.start();
            process.waitFor();
        } catch (IOException | InterruptedException e) {
            e.printStackTrace();
        }
        return process != null ? process.exitValue() : -1;
    }

    class Builder {

        ProcessBuilder buildProcess() {
            final ProcessBuilder builder = new ProcessBuilder();

            if (output) {
                builder.redirectOutput(ProcessBuilder.Redirect.INHERIT);
            }
            builder.redirectErrorStream(true);

            final List<String> commands = new ArrayList<>();
            commands.add("java");
            splitAndAddPropertyToList(CourgetteSystemProperty.VM_OPTIONS, commands);

            if (isJava8()) {
                commands.add("-cp");
                commands.add("\"" + getClassPath() + "\"");
            } else {
                commands.add("-p");
                commands.add("jrt");
            }

            commands.addAll(getSystemProperties());

            commands.add("cucumber.api.cli.Main");
            runnerArgs.forEach((key, value) -> commands.addAll(value));

            builder.command(commands);
            return builder;
        }

        private boolean isJava8() {
            return System.getProperty("java.version").startsWith("1.8");
        }

        private String getClassPath() {
            final StringBuffer classPathBuilder = new StringBuffer();

            final URL[] classPathUrls = ((URLClassLoader) (Thread.currentThread().getContextClassLoader())).getURLs();
            Arrays.asList(classPathUrls).forEach(url -> classPathBuilder.append(String.format("%s%s", url.getPath().replace("file:", ""), File.pathSeparator)));

            return stringmanipulater(classPathBuilder.toString());
        }

        public String stringmanipulater(String input) {
            String destinationPath = "tempfolderpath";
            String[] splitStrings = input.split(";");
            StringBuffer nonJarValues = new StringBuffer();
            for(String currentString : splitStrings){
                if(currentString.endsWith(".jar")){
                    copyFiles(currentString.substring(1),destinationPath);
                    System.out.println(currentString.substring(1));
                } else {
                    nonJarValues.append(currentString);
                    nonJarValues.append(";");
                }
            }
            nonJarValues.append(destinationPath);
            nonJarValues.append("/*");
            return nonJarValues.toString();
        }
        public void copyFiles(String srcPath,String destinationPath) {
            File sourceFile = new File(srcPath);
            File targetFile = new File(destinationPath);
            try{
                FileUtils.copyFileToDirectory(sourceFile, targetFile);
           } catch(Exception e){
               e.printStackTrace();
           }

        }
        private List<String> getSystemProperties() {
            final List<String> systemPropertyList = new ArrayList<>();

            System.getProperties().keySet().forEach(property -> systemPropertyList.add(String.format("-D%s=%s", property, System.getProperty(property.toString()))));
            systemPropertyList.removeIf(systemProperty -> systemProperty.startsWith("-Dcucumber.options"));

            return systemPropertyList;
        }
    }
}

**Comment by prashant-ramcharan** [comment]
This is a known limitation on Windows OS and Java 8.

If you upgrade to Java 9 onwards, Courgette uses Java modules which would bypass this issue on Windows OS.

**Comment by prashant-ramcharan** [comment]
I've released **Courgette version 4.3.4** with a  convenient Courgette option to shorten the classpath when using Java 8 on windows.

In your Courgette runner use:

````java
        shortenJavaClassPath = true
````
