### ISSUE TITLE
Is "courgette-jvm" capable of running same cucumber scenario on different browser example chrome and firefox in parallel using maven

### ISSUE THREAD

**Issue by LearningPur** [prashant-ramcharan/courgette-jvm#165]
Hi @prashant-ramcharan 

Using your library can same cucumber scenario (Example "Valid Login test") on different browser (Example Chrome and FireFox) in parallel using Maven ?

In our company we want to run our automation test on multiple browser in parallel instead of running them one after another browser like once Chrome finished executing next FireFox. We want to run same test in parallel on both browser chrome and firefox. 

Thanks
Victor

**Comment by prashant-ramcharan** [comment]
This is not related to Courgette but yes, you can run the tests on different browsers.

The easiest way is to execute the runner multiple times with different run parameters.

Within you framework, make the browser selection configurable and pass in the option at runtime.

Example:
````
** Run 1 **
mvn test .... -Dbrowser=chrome

** Run 2 **
mvn test ... -Dbrowser=firefox
````
