### ISSUE TITLE
Question: Update cucumber dependency o something newer?

### ISSUE THREAD

**Issue by bill2605** [prashant-ramcharan/courgette-jvm#170]
Hey!
was wondering if there was a way to update project from cucumber 5.0.1-rc1 to something newer?

thx

**Comment by prashant-ramcharan** [comment]
Hey, 

I will look into updating to the latest version however there are a lot of breaking changes though.

Is there a specific feature that you missing in the current version `5.0.1-rc1` ?

**Comment by bill2605** [comment]
Well it just that my projects use cucumber-spring on top of your library so for things to be in sync i need to be mindful of the cucumber version you are using and seeing as we're ar 5.5.x i think , i was wondering why you picked 5.0.0-RC1

**Comment by prashant-ramcharan** [comment]
Hi @bill2605 

I've now released Courgette version `4.4.0` which has the latest Cucumber version `5.5.0`

Commit here: b315ccc

**Comment by bill2605** [comment]
cheers lad!!
