### ISSUE TITLE
Request to upgrade extent report library with version "4.1.4" that includes some known issues that i reported to extent report 

### ISSUE THREAD

**Issue by LearningPur** [prashant-ramcharan/courgette-jvm#175]
HI @prashant-ramcharan Long back 20 days ago i logged some required known issues to extent report Anshoo guy developer and he recently have replied on those all bugs i have logged and released in version  **"4.1.4"** Would you please mind to upgrade "4.1.3" version with "4.1.4" and release new "courgette-jvm" version ?

These are the 3 bugs i logged to extent report

https://github.com/extent-framework/extentreports-java/issues/126
https://github.com/extent-framework/extentreports-java/issues/125
https://github.com/extent-framework/extentreports-java/issues/127

Thanks
Victor

**Comment by prashant-ramcharan** [comment]
Hi @LearningPur 

I was just about to release a new version... I will see if I can add this in too.

**Comment by prashant-ramcharan** [comment]
This change is now in Courgette version `4.5.0`

**Comment by prashant-ramcharan** [comment]
@LearningPur 

With regards to this issue: extent-framework/extentreports-java#126

Please open a separate **Courgette issue** for this.

**Comment by LearningPur** [comment]
Thank you so much @prashant-ramcharan  for your quick change and releasing it too soon. 

**With regards to this issue: extent-framework/extentreports-java#126 .  :** Here is the below ticket i have logged 

https://github.com/prashant-ramcharan/courgette-jvm/issues/178
