### ISSUE TITLE
ExtentSparkReporter : When 1 cucumber step failed rest steps after failed step coming as Pass instead of Skip

### ISSUE THREAD

**Issue by LearningPur** [prashant-ramcharan/courgette-jvm#178]
Hi @prashant-ramcharan   I have integrated ExtentSparkReporter and after the execution i found when 1 cucumber step failed rest steps after failed step coming as Pass instead of it should have been SKIPPED. 

PFB screenshot of it

![Screen Shot 2020-04-11 at 10 46 57 PM](https://user-images.githubusercontent.com/57417403/79060052-5e4ed100-7c46-11ea-9e75-79dc4f3d2737.png)

**Comment by prashant-ramcharan** [comment]
This is now released in Courgette version `4.6.0`
