### ISSUE TITLE
Running automation suite as "Regression" at the end of execution it throws this weird error and that stop generating html report  courgette.html and extentreport.html

### ISSUE THREAD

**Issue by LearningPur** [prashant-ramcharan/courgette-jvm#179]
Hi @prashant-ramcharan  I need your help if you are an aware of this unknown weird error that gets in at the end of execution while running automation suite as regression and that stop generating html report at the end.

Due to this it prevents to look at the failed scenarios because reports is not getting created due to this error.

I tried my all best to find out the root cause spent almost 2 days but no luck and finally ended up reaching out to you.

![Screen Shot 2020-04-12 at 3 56 07 PM](https://user-images.githubusercontent.com/57417403/79079793-dbc22200-7cd6-11ea-9939-06e4a935ca01.png)

**Comment by prashant-ramcharan** [comment]
Can you share the `cucumber.json`

**Comment by prashant-ramcharan** [comment]
I'm assuming you trying to save a `image/png;base64` image in your framework?

I will be releasing a new version of Courgette which includes a single bundled Courgette Html Report with base64 images embedded by default.

This might resolve your issue.

**Comment by LearningPur** [comment]
Yes @prashant-ramcharan  i am using image/png;base64 to save an image in report because that's what our requirement is.

This is really a blocker to present final html report to the end user because it is not getting created due to this error.

Please find below cucumber.json file in zip folder 

[cucumber dot json.zip](https://github.com/prashant-ramcharan/courgette-jvm/files/4467683/cucumber.dot.json.zip)

That will be great and hopefully it will resolve this issue when you will be releasing new version of Courgette which includes a single bundled Courgette Html Report with base64 images embedded by default.

**Comment by prashant-ramcharan** [comment]
This is now released in Courgette version `4.6.0`

**Comment by prashant-ramcharan** [comment]
Embed your screenshots as normal.

````java
scenario.embed(screenshot.getScreenshotAs(OutputType.BYTES), "image/png", "some-image-name");
````

**Comment by LearningPur** [comment]
Thank you so much @prashant-ramcharan  you are really a life saver to me. I will definitely give it a try with this new version and will let you know how did it to go. Really really really really really really appreciated for all your help so far. I wish i would get a chance in life to meet you some where in the corner of world 

Thanks
Vinit

**Comment by LearningPur** [comment]
@prashant-ramcharan  It seems to be working without any issue so far i will keep an eye on our production auto triggered build if any failure will let you know but so far it looks good. Thanks for that.

Regarding this ticket that i raised to extent report i have been told that "Expand and Collapsed" is coming by default (Last comment from Anshoo in below ticket). Is there something that you need to add in framework in order to make it "Expand and Collapsed" scenarios ?

https://github.com/extent-framework/extentreports-java/issues/127

Thanks
Vinit

**Comment by prashant-ramcharan** [comment]
I will take a look but I cant commit to when I will do a next release.
