### ISSUE TITLE
How to disable TestNG reporting?

### ISSUE THREAD

**Issue by neo81-83** [prashant-ramcharan/courgette-jvm#181]
Hi Prashant,

I hope you are doing well. How to disable default TestNG reporting? It is causing issues with execution at the end while trying to create reports. See the below post for reference.

https://stackoverflow.com/questions/28041967/java-turn-off-testngs-default-reporters-programmatically

**Comment by prashant-ramcharan** [comment]
Hi @neo81-83 

Yes, I think it makes sense to disable the TestNG reporting within Courgette.

I will look into disabling this.

**Comment by prashant-ramcharan** [comment]
Hi @neo81-83 

I had a look and I don't see any TestNG reports being generated. What exactly is the issue?

After your run Courgette where are these TestNG reports saved to?

**Comment by neo81-83** [comment]
hey prashant, it is getting generated under target/surefire-reports.

**Comment by prashant-ramcharan** [comment]
Oh right, you using Maven. Let me check. Thanks

**Comment by prashant-ramcharan** [comment]
The maven surefire plugin creates these reports so theres not much I can do in Courgette to prevent this.

However, you could configure the `reportsDirectory` to somewhere like `/tmp` so that surefire saves the report there.

````maven
           <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M4</version>
                <configuration>
                    <reportsDirectory>/tmp</reportsDirectory>
                </configuration>
            </plugin>
````
