### ISSUE TITLE
Regarding Grouping extent report cucumber scenarios 

### ISSUE THREAD

**Issue by LearningPur** [prashant-ramcharan/courgette-jvm#182]
Hi @prashant-ramcharan I logged below defect to Extent report and as per developer that is default comes with extent report version 4.1.4. 

Can you please take a look at it why it is not grouping cucumber scenarios in extent report. I mean is there something that you need to account for in courgette framework.

https://github.com/extent-framework/extentreports-java/issues/127

I tried with Courgette-jvm version which is most recent and recently been released "4.6.0" but with that i am not seeing this grouping in extent report 

Thanks
Vinit

**Comment by prashant-ramcharan** [comment]
Hi @LearningPur ,

Yes, this will have to be a change within Courgette. 

I will look into changing this in the next release.

**Comment by LearningPur** [comment]
Thanks much a lot. Will wait for that change. Appreciated

Thanks
Vinit

**Comment by prashant-ramcharan** [comment]
@LearningPur This is now released in version `4.6.1`

**Comment by LearningPur** [comment]
It's working. Thanks much @prashant-ramcharan 

![Screen Shot 2020-04-16 at 12 41 33 PM](https://user-images.githubusercontent.com/57417403/79488680-bb98a880-7fdf-11ea-9aef-03134eb6a0d6.png)
