### ISSUE TITLE
Memory usage high

### ISSUE THREAD

**Issue by neo81-83** [prashant-ramcharan/courgette-jvm#184]
Hello again,

I have been running 40 tests in parallel, to my surprise I noticed that my Jenkins node (128 GB RAM and 32 vCPUs) is spiking to 90%. I tried using the VM options -Dcourgette.vmoptions='-Xms768m -Xmx1024m' from command line but doesn't seem to effect anything.

Can you check at your end if something is wrong OR do I need to increase the heap size?

**Comment by prashant-ramcharan** [comment]
Hello,

1. How resource heavy is each test? Does it open up a browser, establish connection to a DB etc?
2. How did you pass the `Dcourgette.vmoptions` to the Jenkins job?
3. Did you check if any of Jenkins plugins are causing the high memory usage? 
4. Have you checked if a similar issue is reported here: https://issues.jenkins-ci.org/browse/JENKINS-61592?jql=labels%20%3D%20memory-leak

Thanks.

**Comment by neo81-83** [comment]
See my answers below:
1. Just opens a browser on the remote VMs. Hub is on a different VM than the Jenkins node. No connection to any DBs.
2. From command line `mvn clean verify -Dcourgette.vmoptions='-Xms768m -Xmx1024m'`.
3. Using groovy pipeline script, no Jenkins plugins.
4. Looked at them, issues are still open.

**Comment by prashant-ramcharan** [comment]
As you are using Maven surefire plugin, can you try adding the `argLine` and `systemProperties` to the plugin like below? 

In the example below, I've set higher `argLine ` -X values compared to `courgette.vmoptions`. 

The reason for this is surefire will fork the VM for the Courgette runner and it's this fork that should have higher memory settings. (_You should tweak this value as required_)

Courgette will use the `courgette.vmoptions` for each thread it starts.

````xml
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.0.0-M4</version>
        <configuration>
          <argLine>-Xms2048m -Xmx4096m</argLine>
          <systemProperties>
            <property>
              <name>courgette.vmoptions</name>
              <value>-Xms768m -Xmx1024m</value>
            </property>
          </systemProperties>
        </configuration>
      </plugin>
````

**Comment by prashant-ramcharan** [comment]
There’s nothing from Courgette side that’s changed so perhaps try the above or tweak the thread count.

**Comment by prashant-ramcharan** [comment]
Please re-open if you find a cause in Courgette. Thanks
