### ISSUE TITLE
Question - Selenium Grid Usage

### ISSUE THREAD

**Issue by bill2605** [prashant-ramcharan/courgette-jvm#185]
Hey there!

More a question than an issue;
have you experimented with a selenium grid test execution setup? i know this library support parallel execution for scenarios or features, however how well would this fare if say i wanted to run parallel scenarios each running on 3 devices (ios, android, web)? I would be curious to know how your parallelization does conflict with a grid // config or if they would be working hand in hand .

Cheers mate!

**Comment by prashant-ramcharan** [comment]
Hey!

You can simply run your Courgette runner 3 times with each run taking in different test parameters. 

You should set up your test framework to configure the test parameters at runtime.

Example using Gradle in a shell script:

**multi_run_script.sh**
```gradle
// runTest is the task defined in your build.gradle
gradle runTest -Ddevice=ios &
gradle runTest -Ddevice=android &
gradle runTest -Ddevice=web &
wait
```

Then run the script.
````
./multi_run_script.sh
````

**Comment by bill2605** [comment]
OK ok ok follow up question...
upon doing some research, it seems like grid allows me to run one test case "simultaneously" on 3 separate browsers.
ie
Grid
test: Login into site X
runs for: chrome, firefox, safari
total runs: 3

The way im currently using your library is by passing the browserType as a runtime parameter
so the idea you suggested of a script makes sense however you would still be running as follow:
run test for chrome, then run test for firefox, then run test for safari.

I'm trying to see/understand if there are any benefits in running grid with the added support provided by your library.

Also from your suggestion, i should be getting 3 separate/different reports correct?

**Comment by prashant-ramcharan** [comment]
> you would still be running as follow:
run test for chrome, then run test for firefox, then run test for safari

No, **all 3** would run at the **same time** because each call to gradle would run in the background.

You can take a look here: https://github.com/prashant-ramcharan/courgette-jvm-selenium

> Also from your suggestion, i should be getting 3 separate/different reports correct?

Yes, you would get 3 separate reports however you need to pass in the`courgette.reportTargetDir` at runtime.
```gradle
gradle runTest -Ddevice=ios -Dcourgette.reportTargetDir=build/ios &
gradle runTest -Ddevice=android -Dcourgette.reportTargetDir=build/android &
gradle runTest -Ddevice=web -Dcourgette.reportTargetDir=build/web &
wait
```

_Note.. please upgrade to the latest version of Courgette as this creates a single Courgette html report._

**Comment by bill2605** [comment]
thanks for the pointers! 
One last question not so much related to this topic but something that has been on my todo list for a bit. Would there be a way to have a way to edit or set the report name? 
Say i wanted the report to be named PROJECT_NAME rather than 'Courgette Report'.
My immediate go-to is to update the html file via script or have a finally clause somewhere to modify the html file from java.. however i do find it to be less elegant of a solution. Unless you already support this in code? 🤔 🤔

**Comment by prashant-ramcharan** [comment]
No, this is not currently supported but as you are the second person who'd asked this, I will look into adding support for this

**Comment by bill2605** [comment]
Alright thanks lad! I shall close this question!

**Comment by bill2605** [comment]
this mad lad!!!
Hats off to you! 💯 💯

**Comment by bill2605** [comment]
Small follow up:

Given the snippet below:

`@RunWith(Courgette.class)
@CourgetteOptions(
	reportTitle =  "LOOLLL",
	threads = 2,
	runLevel = CourgetteRunLevel.SCENARIO,
	rerunFailedScenarios = true,
	showTestOutput = true,
	cucumberOptions = @CucumberOptions(
           ...
	)
)`

Is there a way to have the reportTitle set based on a value from the application.properties file?

So far trying to reference via "${project.name}" throws exception from your string.replace() call when substituting "id:reportTitle"... 🤔

**Comment by prashant-ramcharan** [comment]
Are you using maven or gradle to run the tests?

**Comment by prashant-ramcharan** [comment]
You can pass in the reportTitle at runtime using the system property:

````
-Dcourgette.reportTitle=Amazing Report
````
