### ISSUE TITLE
Spring/Springboot support

### ISSUE THREAD

**Issue by shrjoshi** [prashant-ramcharan/courgette-jvm#187]
This is more of a question and not an issue.
Does courgette-jvm work with spring framework, specifically Spring tests ?
I tried to use it but spring Dependency injection does not seem to work when using Crougette.class in hook.

Any reference example with spring would be really helpful.

Thanks

**Comment by prashant-ramcharan** [comment]
Are you referring to whether you can use Cucumber spring? https://github.com/cucumber/cucumber-jvm/tree/master/spring

If so, then yes you can use Courgette to run Cucumber tests (_that uses Spring_).

You just need to ensure you have the cucumber spring dependency on your classpath

````
compile group: 'io.cucumber', name: 'cucumber-spring', version: '5.6.0'
````

**Comment by shrjoshi** [comment]
If I use Cucumber.class in my hook file, Spring Dependency Injection works but if i use @RunWith(Courgette.class) it does not work.

**Comment by prashant-ramcharan** [comment]
I've created an Courgette with Cucumber spring example project here:

https://github.com/prashant-ramcharan/courgette-jvm-spring-example

Simply run this as a JUnit test: https://github.com/prashant-ramcharan/courgette-jvm-spring-example/blob/master/src/test/java/runner/CourgetteRunner.java

Or run it using gradle:
````gradle
gradle runTest
````
