### ISSUE TITLE
This is not an issue at all just an question : Third party library 

### ISSUE THREAD

**Issue by LearningPur** [prashant-ramcharan/courgette-jvm#188]
HI @prashant-ramcharan  I need your help to answer this stupid question i have been asked in company i am working in as an Automation Engineer. 

**The question is : What if tomorrow this guy (@prashant-ramcharan) dis-continue this library.**

If you remember me i am using your library since last almost 2 months and from my bottom of heart i wanna say that you have your library saved me a lot and i am thanking a tons of time for that, really appreciated. 

Today the framework i am working on for 1 of the new project i have been assigned that has completed and under demo with manager and management and this stupid question i have been asked with an intention to stop using this library since it's third party.

**If you can please help me prepare an answer on this that will be great because they don't know the power of this library how powerful it is and what all benefits it brought and reduced the code.**

Just because of politics in company specially those guys whose working in company more than 3 years they don't like this work just because they don't have proper answer.

**I really wanna save framework that i built on using this library if you can please help prepare an answer.**

Thanks Much for all your hard work you put in building library and made it available to the people like me.

**Comment by prashant-ramcharan** [comment]
Hi @LearningPur ,

I'm glad you find Courgette useful in your projects.

I'm assuming you use other 3rd party libraries so I'm not sure how else to advise.

To only answer I can provide is that Courgette is an open source project and you and your team can contribute to the library at any time.

**Comment by vab2048** [comment]
Are there any plans to have Courgette supported as an official cucumber project in the future?
