### ISSUE TITLE
Report Portal plugin updates

### ISSUE THREAD

**Issue by yuliya-rahina** [prashant-ramcharan/courgette-jvm#190]
Hello Prashant Ramcharan,
I am using courgette-jvm library and reporting on the Report Portal. It is a great library with clear documentation. As for the Report Portal tool is actively updated, it will be really great if you are possible to add some updates for it:
1. Add the ability to send rp.tags (from reportportal.properties)
2. Add the ability to send images for the report (Report Portal supports images attaching for tests flow)
3. Add ability to send real tests execution time (because now this time is calculated as a sum of each test execution time)
4. Add the ability to separate tests in the different folders (per each feature file) on the Report Portal 

Best regards,
Yuliya

**Comment by prashant-ramcharan** [comment]
Hi @yuliya-rahina 

The Courgette Report Portal plugin is very simplistic and does not integrate with the Report Portal API as the tests run. This means you will not get real time events show in portal whilst your test runs.

**_How does it currently work?_**
At the end of the test run, Courgette takes the Cucumber JUnit xml report, zips it and then uploads it to the report portal server. 

https://reportportal.io/docs/Import-data-to

The Courgette Report Portal plugin has limited functionality and this functionality is based on and limited by the JUnit xml import features in Report Portal.

**Comment by prashant-ramcharan** [comment]
Hi @yuliya-rahina 

Just a quick update:

You can now send `rp.tags` using Courgette version `5.2.0`

**Comment by prashant-ramcharan** [comment]
@yuliya-rahina all of the requested report portal updates are now available in version 5.11.0
