### ISSUE TITLE
Odd issue where steps are not being picked up after switching to courgette

### ISSUE THREAD

**Issue by delrey1** [prashant-ramcharan/courgette-jvm#191]
Hi,

Hope you may be able to help out. I'm trying to implement courgette into a new project. Our current test runner looks like
```
	@CucumberOptions(
			features={"src/test/resources/Features"},
	        glue={"com.ui.stepdefinitions"},
	        //this is the change
	        tags= {"@tag"},
	        plugin = {"com.cucumber.listener.ExtentCucumberFormatter"})
	
	public class TestRunner{	  ...
```

and the new test runner with CourgetteOptions looks like

```
@Test
@CourgetteOptions(
        threads = 1,
        runLevel = CourgetteRunLevel.FEATURE,
        rerunFailedScenarios = true,
        showTestOutput = true,
        reportTargetDir = "build",
        cucumberOptions = @CucumberOptions(
                features = "src/test/resources/features",
                glue = "com.ui.stepdefinitions",
                tags = {"@tag"},
                plugin = {
                        "pretty",
                        "json:build/cucumber-report/cucumber.json",
                        "html:build/cucumber-report/cucumber.html"},
                strict = true
        ))
public class CourgetteRunner extends TestNGCourgette {
}
```

However when running the Courgette TestRunner we get the following in the console
```
1 Scenarios (1 undefined)
16 Steps (16 undefined)
0m0.719s


You can implement missing steps with the snippets below:

Given("...
```

I have tried seeing what happens when implementing those steps and it does work if using lambdas, but the current project does not use it and not in a position to transfer it over

Your example on https://github.com/prashant-ramcharan/courgette-jvm-example also doesn't use lambdas so unsure what the issue may be?

Our POM has a bunch of dependencies, but the only one related to Selenium (That I can see) are
```
<dependency>
            <groupId>io.github.prashant-ramcharan</groupId>
            <artifactId>courgette-jvm</artifactId>
            <version>4.6.2</version>
        </dependency>
 <dependency>
            <groupId>com.vimalselvam</groupId>
            <artifactId>cucumber-extentsreport</artifactId>
            <version>1.1.1</version>
        </dependency>
<dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.141.59</version>
        </dependency>
```
Step Definition files are also in the correct package
```
package com.ui.stepdefinitions;

import cucumber.api.java.en.And;
import cucumber.api.java.en.Given;
import cucumber.api.java.en.Then;
import cucumber.api.java.en.When;

public class POSteps extends BaseStepClass {
	
	@Given(...
```

I've seen online that those steps are only generated if there is a cucumber-java8 dependency present but I don't see why it wouldn't pick up the steps in the other format?

**Comment by prashant-ramcharan** [comment]
Hi @delrey1,

Are you trying to run the tests from the IDE test runner or from Maven?

If from the IDE then ensure the run configurations are correct.

I will add a branch to the courgette example project with lambda step defs so you can take a look.

**Comment by prashant-ramcharan** [comment]
@delrey1 - you can the following branch that has lambda step defs: 

https://github.com/prashant-ramcharan/courgette-jvm-example/tree/courgette-example-lambda-step-defs

**Comment by prashant-ramcharan** [comment]
I think I misunderstood your question.. you saying that the regular (non lambda) step defs are not being picked up.

Can you try removing this dependency?

````
 <dependency>
            <groupId>com.vimalselvam</groupId>
            <artifactId>cucumber-extentsreport</artifactId>
            <version>1.1.1</version>
  </dependency>
````
This library looks to be using Cucumber version `1.2.5` which may be causing the issue.

**Comment by delrey1** [comment]
Thank you so much! That dependency was causing the issue, removing it resolved the problem. Completely missed it
