### ISSUE TITLE
Error text messages are not displayed by wrapping

### ISSUE THREAD

**Issue by jiawade** [prashant-ramcharan/courgette-jvm#193]
@prashant-ramcharan  can we show the exception errors by wrapping in extent report? it's difficult to debug the error messages, thanks
![image](https://user-images.githubusercontent.com/66766526/84348874-b1aeb280-abe8-11ea-995b-3a0e34eb0139.png)

**Comment by prashant-ramcharan** [comment]
@jiawade 

These error messages are captured by Cucumber in the `cucumber.json` / `cucumber.xml` reports. 

Courgette re-uses the data contained in these reports to build the extent report so all the information you see in the extent report comes form the Cucumber report.

Courgette does not have any additional stacktrace information other than those contained within the Cucumber reports.

**Comment by shellphxiao** [comment]
@prashant-ramcharan many thanks
