### ISSUE TITLE
Unable to run the tests in Jenkins

### ISSUE THREAD

**Issue by harsharg** [prashant-ramcharan/courgette-jvm#194]
The tests run fine locally, but when running in Jenkins, the tests are  getting failed.It's a multi module maven project , getting below error and the tests are not executed.Please advice.

Error:

INFO] Running null
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.032 s <<< FAILURE! - in null
[ERROR] Time elapsed: 0.002 s  <<< ERROR!
courgette.runtime.CourgetteTestFailureException: Please refer to Courgette / Cucumber report for more info.

Runner file:
@RunWith(Courgette.class)
@CourgetteOptions( 
        threads = 1,
        runLevel = CourgetteRunLevel.SCENARIO,
        rerunFailedScenarios = false,
        rerunAttempts = 1,
        showTestOutput = true,
        reportTargetDir = "build",
        cucumberOptions = @CucumberOptions(
         	    tags =  {"@smokeTest"},
         		features = {"src/test/resources/features"},
        		glue = {"steps"},
                monochrome = true,
                dryRun = false,
                plugin = {"pretty",
                        "json:build/cucumber-report/cucumber.json",
                        "html:build/cucumber-report/cucumber.html",
                        "junit:build/cucumber-report/cucumber.xml"}))

POM:

 <repositories>
        <repository>
        <id>jcenter</id>
        <url>https://jcenter.bintray.com/</url>
        </repository>
     </repositories>

	<dependencies>
		
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>3.14.0</version>
		</dependency>

		
		<dependency>
			<groupId>io.github.prashant-ramcharan</groupId>
			<artifactId>courgette-jvm</artifactId>
			<version>4.6.2</version>
		</dependency>
		

<build>
	   <plugins>
	              
         	<plugin>
	            <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.0</version>
                  <configuration>
                    <includes>
                        <include>**/runners/SeleniumTest.class</include>
                    </includes>
                </configuration>
             <dependencies>
                    <dependency>
                        <groupId>org.apache.maven.surefire</groupId>
                        <artifactId>surefire-junit47</artifactId>
                        <version>2.22.0</version>
                    </dependency>
                </dependencies>
            </plugin>

**Comment by harsharg** [comment]
Hi Prasanth,
Please let me know if you need additional info, adding the folder structure

![image](https://user-images.githubusercontent.com/9514771/84589840-cef7b100-ae74-11ea-9b2f-d43857bc9083.png)

**Comment by harsharg** [comment]
@prashant-ramcharan 

Tried multiple ways, still seeing same issue, the test starts but fails to execute in Jenkins.


Runner:
![image](https://user-images.githubusercontent.com/9514771/84605093-f6cf2f00-aedd-11ea-8816-068d0e5fbd4d.png)


Jenkins console:

![image](https://user-images.githubusercontent.com/9514771/84605099-09496880-aede-11ea-8c4d-b5f59460037c.png)

**Comment by prashant-ramcharan** [comment]
Hello,

It looks like the Courgette runner is being pick up.

Can you provide the cucumber.json ?

**Comment by harsharg** [comment]
I noticed that the cucumber.json is pointing to the execution on 13th June, it's not showing the latest execution
[cucumber.txt](https://github.com/prashant-ramcharan/courgette-jvm/files/4777354/cucumber.txt)
.PFA

**Comment by prashant-ramcharan** [comment]
The issue seems to be with your tests + Jenkins setup. 

Looking at the `cucumber.json` you provided, there is a `org.openqa.selenium.WebDriverException` causing the error.

This error is not related to Courgette so please first make sure that you can run your tests successfully in Jenkins without Courgette.

**Comment by harsharg** [comment]
Sure, will do, wanted to check if using this dependency will cause any issues

<dependency>
			<groupId>net.masterthought</groupId>
			<artifactId>cucumber-reporting</artifactId>
			<version>4.10.0</version>
</dependency>

**Comment by prashant-ramcharan** [comment]
The issue is not with Courgette because your tests does execute.

In your Jenkins build a `CourgetteTestFailureException` is raised which means Courgette successfully executed the tests but there was failures / errors with the tests. You will have to resolve those failures / errors first.

Hope this helps.

**Comment by harsharg** [comment]
I tried  to run the tests without courgette and was able to execute them in Jenkins.Please advice.

Runner:
@RunWith(Cucumber.class) 
@CucumberOptions (features="src/test/resources/features",
tags = "@smokeTest", 
glue = "steps",//For instance, once cucumber runs I want to add 
//plugin = {"pretty", "html:target/cucumber-htmlreport","json:target/cucumber-report.json"}
monochrome = true,
dryRun = false,
strict=false,
plugin= {"pretty","json:target/cucumber-report/cucumber.json","html:target/cucumber-htmlreport","junit:target/cucumber-report/cucumber.xml"}
)

**Comment by prashant-ramcharan** [comment]
Unfortunately, I cannot advise any further because the error in your Jenkins build is not related to a Courgette error.

`courgette.runtime.CourgetteTestFailureException: Please refer to Courgette / Cucumber report for more info` 

This means that Courgette ran your tests but there were **failures in your tests**. This Courgette exception is not the cause of your issue.

Does your run fine locally with Courgette?

**Comment by harsharg** [comment]
Yes, it works fine locally. The error in jenkins occurs when executing before hooks.

![image](https://user-images.githubusercontent.com/9514771/84715318-695e0e80-afb3-11ea-8fde-915ce872d007.png)

**Comment by prashant-ramcharan** [comment]
It looks like an issue on your Jenkins agent.

Perhaps you can try the following:

1. Try cleaning up your Jenkins workspace.
2. Try purging the .m2 repository on you Jenkins agent by running the following maven command
`mvn dependency:purge-local-repository`
