### ISSUE TITLE
After upgrading courgetee-jvm from 4.6.2 to 5.0.0 reading feature file name during runtime throwing an error

### ISSUE THREAD

**Issue by LearningPur** [prashant-ramcharan/courgette-jvm#197]
Hi @prashant-ramcharan  I am using your library since last 1 year and i am loving it. Recently i have upgraded version from 4.6.2 to 5.0.0 and i noticed few line of code that i have written to read feature file name during runtime is now throwing an error, Can you please help finding a solution.

Here are 3 line of code i had to read feature file name during runtime that used to work for version 4.6.2

   **Parser<GherkinDocument> parser = new Parser<>(new AstBuilder());
   TokenMatcher matcher = new TokenMatcher();
   Feature feature = parser.parse(new FileReader(scenario.getUri().toString().split(":")[1] ), matcher).getFeature();
   String featureFileName = feature.getName();**

Thanks
Vinit

**Comment by prashant-ramcharan** [comment]
Thanks @LearningPur, I will take a look.

**Comment by prashant-ramcharan** [comment]
You can use this:

````java
Resource resource = new Resources.UriResource(Path.of(scenario.getUri()));

FeatureParser featureParser = new FeatureParser(UUID::randomUUID);

Optional<String> featureName = featureParser.parseResource(resource).get().getName();
````

**Comment by prashant-ramcharan** [comment]
You can use this:

````java
        Resource resource = new Resource() {
            @Override
            public URI getUri() {
                return scenario.getUri();
            }

            @Override
            public InputStream getInputStream() throws IOException {
                return Files.newInputStream(Path.of(scenario.getUri()));
            }
        };

        FeatureParser featureParser = new FeatureParser(UUID::randomUUID);

        Optional<String> featureName = featureParser.parseResource(resource).get().getName();

````

**Comment by LearningPur** [comment]
Thanks much @prashant-ramcharan it worked, the good thing i like about using your library is your always reply on time and also keep library updated with latest changes out there. Thanks much. Very much appreciated.
