### ISSUE TITLE
The Gradle build is still green even I got some failed Cuke scenarios

### ISSUE THREAD

**Issue by karthees05** [prashant-ramcharan/courgette-jvm#198]
Hi,
I am using this jvm and not using the customised report.
The Parallel run is fine in SCENARIO level.
After build is over I got some failed cuke scenarios but the job colour is still in Green and the traditional cuke report page is showing a scenario failed.
Could you please tell me whether its my config issue or something else.

Thanks
Karthee

**Comment by prashant-ramcharan** [comment]
Hi,

Where is the job colour green, is it in your continuous integration tool? If so, you need a step to ensure the `exit code` is checked after the test run. This will determine weather the build is green / red in your CI tool.

What `exit code` is shown in the gradle build after the test run? An `exit code` other than 0 usually means the build failed.

**Comment by soumyarao82** [comment]
@prashant-ramcharan I have the same issue. If there is a failed scenarios in Cucumber report, Jenkins job still shows green. It is always returning status code 0

**Comment by soumyarao82** [comment]
We have not used ignoreExitValue and ignoreFailures in build.gradle at all

**Comment by soumyarao82** [comment]
The same was working fine before running the tests in parallel. That time, I could see failed Jenkins Job when any scenario failed. Only after I started running the tests in parallel this started happening.

**Comment by prashant-ramcharan** [comment]
Can you provide the output of the gradle build?

If you run the gradle task locally with a test failure, what gradle exit code is returned?

If you run the example project, what exit code do you get?


https://github.com/prashant-ramcharan/courgette-jvm-example/blob/master/build.gradle#L31

**Comment by prashant-ramcharan** [comment]
Courgette does not run differently in Jenkins so if the same gradle task fails locally but passes in Jenkins the its most likely an issue with the way your Jenkins job is configured.

I ran the gradle task and it fails the build as expected.

![Screenshot 2020-08-19 at 11 27 49](https://user-images.githubusercontent.com/2563149/90624070-4ba96180-e20f-11ea-9c8b-48fb02865d60.png)

**Comment by soumyarao82** [comment]
Thanks Prashant, let me check at my end and revert

**Comment by soumyarao82** [comment]
Hello Prashant,

I tried few different things. To use Courgette, I had to change the runner class as you have detailed.  This helped to run the tests in parallel but once I have added this, this is ignoring cuke  Failures in build and reporting a success always. It reports a build failure only when junit tests fail.

I reverted the runner class to what it was before, and I see Build Failure when the cuke tests fails as expected.

Before:
@RunWith(Cucumber.class)


After: 
@RunWith(Courgette.class)
@CourgetteOptions{
}

**Comment by soumyarao82** [comment]
even in my local also it shows build success when the cuke test fails

**Comment by prashant-ramcharan** [comment]
Hello,

I'm not sure how else to advise on this because this works fine for me locally and in CI. 

There hasn't been any other reports to suggest otherwise too.

In order for me to assist further, please provide a demo project for me replicate this issue locally.

**Comment by prashant-ramcharan** [comment]
@karthees05 @soumyarao82 

Below are failing and passing build in Jenkins. Your issue is likely due to a misconfiguration in your CI pipeline or project setup.

**Failing Build**

![screencapture-0-0-0-0-32771-job-courgette-jvm-7-console-2020-08-25-11_52_01](https://user-images.githubusercontent.com/2563149/91165910-71c87900-e6c9-11ea-850d-ba9afad67a1c.png)


**Passing Build**

![Screenshot 2020-08-25 at 11 47 38](https://user-images.githubusercontent.com/2563149/91165646-eea72300-e6c8-11ea-9002-2417b726d119.png)

**Comment by prashant-ramcharan** [comment]
Kindly re-open this issue if you find that it's related to Courgette.

**Comment by soumyarao82** [comment]
Hi Prashant,

Just wanted to update you that, I managed to resolve the issue. After enabling the Courgette in runner class, I had to also change few things in the Jenkins config. Post-build Actions --> Publish JUnit test result report --> Test report XMLs
