### ISSUE TITLE
Courgette options not recognising the cucumber tags

### ISSUE THREAD

**Issue by Techtipsandbites** [prashant-ramcharan/courgette-jvm#200]
Hi Prashanth,
Couldu u please advise regarding the following:::
I have added courgette jvm in build.gradle .
But when I run the runner,Courgette options is not recognisng the cucumber tags and steps are not picked up 
I have upgrades from cucumber 2 to cucumber 6 
And courgette jvm dependency too 

So if i include courgette-jvm ,I no need to include cucumber-jvm???

Please advise 
Thanks

**Comment by prashant-ramcharan** [comment]
Hi @Techtipsandbites 

You do not need to include the `cucumber-jvm` dependency in your build.gradle. You just need to have the `cougette-jvm` dependency.

How are you providing the cucumber tags from gradle?

An example would be:

````gradle
gradle someTaskName -Dcucumber.tags="@smoke"
````

You can see the example project here: https://github.com/prashant-ramcharan/courgette-jvm-example

**Comment by prashant-ramcharan** [comment]
Inactive issue - closing.
