### ISSUE TITLE
How to attach video or record video and save it 

### ISSUE THREAD

**Issue by LearningPur** [prashant-ramcharan/courgette-jvm#202]
Hi @prashant-ramcharan  Is it possible to record the test video and attach it to "courgette-report" or "extent report" ?

**Comment by prashant-ramcharan** [comment]
Hi @LearningPur 

This is not currently possible and unlikely to be supported in Courgette. 

I assume you want to record the browser session from Selenium. Unfortunately Selenium does not support recording videos using its APIs so it's not currently possible to save a video during execution.

Courgette needs a way to reference a video URL and Cucumber does not support capturing / embedding videos so it's not currently possible to embed a video in the Courgette report.
