### ISSUE TITLE
Courgette-report is not getting generated properly

### ISSUE THREAD

**Issue by ashwinsgm** [prashant-ramcharan/courgette-jvm#203]
Hi Team

Cucumber report and extent report is getting generated, but Courgette jvm report is not getting generated properly. I have attached the screenshot and runner file. Is there anything we are missing in the report file. Build tool used is gradle. Do I need to add any dependencies for report to get generated.  
**Courgette-version**:: courgette-jvm:5.0.0
**cucumber-jvm**:6.5.0
![snip1](https://user-images.githubusercontent.com/41612300/91310023-fcdf6700-e7ce-11ea-9298-51b057a0bd0e.PNG)

Here is Courgette Runner file I am using 

package com.ford.auto.testRunners;

import org.junit.runner.RunWith;

import courgette.api.CourgetteOptions;
import courgette.api.junit.Courgette;
//import io.cucumber.junit.CucumberOptions;
import courgette.api.CourgetteRunLevel;
import courgette.api.CucumberOptions;

@RunWith(Courgette.class)
@CourgetteOptions(
        threads = 4,
        runLevel = CourgetteRunLevel.SCENARIO,
        rerunFailedScenarios = false,
        rerunAttempts = 1,
        showTestOutput = true,
        reportTitle = "Courgette-JVM Example",
        reportTargetDir = "build",
        		plugin = { "extentreports" },
        cucumberOptions = 
        @CucumberOptions(
        		glue = "com.example.stepDefinitions", 
        		plugin = {"pretty","json:build/cucumber-report/cucumber.json",
                        "html:build/cucumber-report/cucumber.html",
                        "junit:build/cucumber-report/cucumber.xml" }, 
        		features = "src/test/resources/feature")
)
public class CourgetteJunitRunner {
}

**Comment by prashant-ramcharan** [comment]
Hello @ashwinsgm 

Are you connected to the internet when opening the report? The javascript and css files are loaded using a CDN so it's likely these files are not being loaded when the report is opened.

Could you please attach your Courgette html report file here?

**Comment by ashwinsgm** [comment]
I have connected to the internet. But i am connecting from the office network and 
I tried disconnecting from VPN as well. Works Same. Attached the files
[index.zip](https://github.com/prashant-ramcharan/courgette-jvm/files/5135280/index.zip)

**Comment by prashant-ramcharan** [comment]
Hi, 

Courgette version **4.6.0 upwards**  uses a CDN to deliver the CSS and Javascript files which in a single html Courgette report.

The report that you attached suggests that you using a different version of Courgette as the CSS and Javascript files (below) should not be relative to the `index.html`

![Screenshot 2020-08-27 at 10 29 21](https://user-images.githubusercontent.com/2563149/91423268-3ad09f80-e850-11ea-860b-b82f81542a1b.png)

Can you confirm the version that you using?

You can also try with the example project here: https://github.com/prashant-ramcharan/courgette-jvm-example

**Comment by ashwinsgm** [comment]
I am using the latest version 5.0.0

**Comment by prashant-ramcharan** [comment]
This is not possible as the CDN is explicitly added in the `index.html`

https://github.com/prashant-ramcharan/courgette-jvm/blob/master/src/main/resources/report/index.html#L199-L212

Does the report load up fine using the [example project](https://github.com/prashant-ramcharan/courgette-jvm-example)

**Comment by ashwinsgm** [comment]
Report is getting loaded with example project

**Comment by prashant-ramcharan** [comment]
You just need to have the **Courgette dependancy** in your `build.gradle` as this will automatically pull down the Cucumber dependancies for you.

The Cucumber version is managed by Courgette so you do not need to specify any Cucumber dependencies in your project.

For example, the latest version of Courgette `5.1.0` (_as at the time of this comment_) uses Cucumber version `6.6.0` You **do not** need to specify the cucumber dependency in your project.

Did you try refreshing your project dependencies to check this is not a caching issue?

To assist further, please provide a project (github link or zipped) that I can replicate this issue.

**Comment by prashant-ramcharan** [comment]
@ashwinsgm  

I will be releasing a new version shortly to remove the CDN and embed the CSS and JS directly in the report. This should resolve any caching issues which is causing your report to not load the CSS and JS files.

**Comment by prashant-ramcharan** [comment]
@ashwinsgm You can now try Courgette version `5.2.1` which should resolve caching issues.

**Comment by aravindkesavarapu** [comment]
Hi prashant,

I am also facing same issue. Css and js was not loading even though I added html publisher in Jenkins.



And some times html file was also not generating.

Extent html report - working
Courgette html report - not working

Courgette jvm version - latest

**Comment by prashant-ramcharan** [comment]
Hello,

Does the CSS  and JS just not load in **Jenkins**  or is it locally too?

Can your Jenkins server access the following URL:

https://cdn.jsdelivr.net/gh/prashant-ramcharan/courgette-jvm/src/main/resources/report/css/chartjs.min.css
