### ISSUE TITLE
If  a scenario run failed in feature, both courgette report and extent-report will hide passed scenarios and show rerun failed scenario only

### ISSUE THREAD

**Issue by jiawade** [prashant-ramcharan/courgette-jvm#206]
hi, @prashant-ramcharan 
I found an issue, if set the rerunFailedScenarios = true and rerunAttempts=1 and runLevel = CourgetteRunLevel.FEATURE
[courgette-jvm-spring-example-master.zip](https://github.com/prashant-ramcharan/courgette-jvm/files/5154654/courgette-jvm-spring-example-master.zip)

this is the project file, the Feature2.feature has failed scenario

**Comment by prashant-ramcharan** [comment]
Hi,

I just tried with the attached project and it works fine for me. 



**Courgette Report**

![screencapture-localhost-63342-courgette-jvm-spring-example-master-build-courgette-report-index-html-2020-09-01-10_17_43](https://user-images.githubusercontent.com/2563149/91831918-94fca680-ec3c-11ea-903f-295a5567d4ca.png)

**Extent Report**

![screencapture-localhost-63342-courgette-jvm-spring-example-master-build-courgette-extentreports-index-html-2020-09-01-10_17_55](https://user-images.githubusercontent.com/2563149/91831935-9cbc4b00-ec3c-11ea-83b1-8e86087cdc24.png)

**Cucumber Report**

![screencapture-localhost-63342-courgette-jvm-spring-example-master-build-cucumber-report-cucumber-html-2020-09-01-10_20_05](https://user-images.githubusercontent.com/2563149/91832020-bd84a080-ec3c-11ea-943e-5618fda63eb8.png)

**Comment by prashant-ramcharan** [comment]
Hi, 

This is a known issue and limitation.
https://github.com/prashant-ramcharan/courgette-jvm/blob/master/README.md#limitations-and-known-issues

I may have mistakenly removed it from the README but I've just added it back.

**Comment by shellphxiao** [comment]
Aha...I see
thanks for your reply.

**Comment by prashant-ramcharan** [comment]
@shellphxiao Just to update this issue:

I've now addressed this limitation so this should not be an issue from Courgette version `5.6.0`.

You can now use `CourgetteRunLevel.FEATURE ` and `rerunFailedScenarios = true` without any report data being overidden from the reports.
