### ISSUE TITLE
courgette-jvm version 5.2.0

### ISSUE THREAD

**Issue by LearningPur** [prashant-ramcharan/courgette-jvm#207]
Hi @prashant-ramcharan  I just upgraded from 5.0.0 to 5.2.0 version and started seeing this issue in report

**Extent Report**

![Extent Report](https://user-images.githubusercontent.com/57417403/91908864-d491b580-ec71-11ea-8dc3-873828e3fff6.png)

**courgette report**

When i try to see the result of 'Fail" test it display as expected 

When i try to see the result of "Pass" test it doesn't display anything and black out the screen, Please find below screenshot with api fail 404

![Screen Shot 2020-09-01 at 4 38 58 PM](https://user-images.githubusercontent.com/57417403/91909039-1c184180-ec72-11ea-8404-537003ca7c09.png)

![Screen Shot 2020-09-01 at 4 42 41 PM](https://user-images.githubusercontent.com/57417403/91909076-2e927b00-ec72-11ea-9ed1-1444d4ef4d7c.png)

**Comment by prashant-ramcharan** [comment]
Hi,

I just tried and cannot reproduce the extent report issue. Furthermore, no changes were made to this plugin in the recent versions.

<img width="1440" alt="Screenshot 2020-09-01 at 22 59 58" src="https://user-images.githubusercontent.com/2563149/91910476-ffe2c780-eca6-11ea-8056-30816af51622.png">

With regards to the Courgette report issue, it looks like a caching issue. Can you try clearing your browser cache or opening the Courgette report in **private mode**?

If you visit this https://cdn.jsdelivr.net/gh/prashant-ramcharan/courgette-jvm/src/main/resources/report/js/bootstrap.min.js , does it show `Bootstrap v4.0.0-beta` ?

**Comment by LearningPur** [comment]
It's now working @prashant-ramcharan may be i had some caching issue.

**Comment by prashant-ramcharan** [comment]
@LearningPur  I will be releasing a new version to remove the CDN and embed the CSS and JS in the report. 

This should resolve caching issues and make the report more portable when viewing without an internet connection.

**Comment by prashant-ramcharan** [comment]
CDN is now removed in version `5.2.1`. This should resolve caching issues going forward.
