### ISSUE TITLE
Cucumber-JVM report

### ISSUE THREAD

**Issue by aniketksh** [prashant-ramcharan/courgette-jvm#21]
Hi,
I am using Courgette Runner to execute my cucumber script in gradle. I am facing some issue with courgette report. Tabs on html report are not clickable.

Thank you.

**Comment by prashant-ramcharan** [comment]
Hi, it’s not meant to be clickable. You can filter the failures and reruns using the search input box.

All results are filtered based on the search input which can be anything such as searching for a scenario name or feature name or just failures.

**Comment by aniketksh** [comment]
Hi,
Thanks for quick response. I thought it meant to be clickable. Is there any other reporting tools which uses .json file to create pretty html report?

Thanks.

**Comment by prashant-ramcharan** [comment]
You can try https://www.npmjs.com/package/cucumber-html-report
