### ISSUE TITLE
extent-report only show icon not show picture

### ISSUE THREAD

**Issue by jiawade** [prashant-ramcharan/courgette-jvm#211]
hi @prashant-ramcharan 
may I ask you a question? I'm using cucumber native annotation to integrate with extent-report, but after the extent report is generated only show icon not show picture in extent-report. I know the failed screenshot can be embedded in the Courgette and cucumber native report as base64.  details as below, could you please do me a favor? thanks.
![1](https://user-images.githubusercontent.com/66766526/92300438-4aa55d80-ef8d-11ea-96cf-2651e32b0a53.png)
![2](https://user-images.githubusercontent.com/66766526/92300439-4ed17b00-ef8d-11ea-8692-abd51d69bccd.png)
![3](https://user-images.githubusercontent.com/66766526/92300440-51cc6b80-ef8d-11ea-8f1f-cefe65e5110a.png)

**Comment by prashant-ramcharan** [comment]
Hi,

Are you using the Courgette Extent Reports Plugin with your Courgette runner? If so, Courgette will create the Extent Report for you with embedded base64 images etc.

All you need to do is update your **Courgette runner**

````

**Comment by jiawade** [comment]
thanks！！
