### ISSUE TITLE
Request to group scenario inside feature when parallel=Scenario in courgette-report html report

### ISSUE THREAD

**Issue by LearningPur** [prashant-ramcharan/courgette-jvm#212]
Hi @prashant-ramcharan , As you might know i am using your library since almost a 1 year and in our company automated test cases are growing day by day. Today we have about 500 test cases. 

**_in courgette-report html report_** what i noticed is since we have about 500 test cases and we mostly run them in parallel using Scenario that will be great if you can group test cases inside their feature name so that way we will not required to go thru lot of pagination. 

Example 

![Screen Shot 2020-09-17 at 11 48 16 AM](https://user-images.githubusercontent.com/57417403/93501938-b23ba100-f8db-11ea-8322-a61018f35f17.png)

**Comment by prashant-ramcharan** [comment]
Hi @LearningPur 

This sounds feasible enough and will look into implementing it in the next release.

**Comment by LearningPur** [comment]
Thank you so much for considering it

**Comment by prashant-ramcharan** [comment]
@LearningPur This is now released in version `5.4.0`
