### ISSUE TITLE
Cucumber Reports from courgette jvm

### ISSUE THREAD

**Issue by madhu29071984** [prashant-ramcharan/courgette-jvm#217]
Is it possible to generate cucumber report for parallel texting in gradle  by using courgette jvm

**Comment by prashant-ramcharan** [comment]
Yes, please take a look at the example project here: https://github.com/prashant-ramcharan/courgette-jvm-example

**Comment by madhu29071984** [comment]
Thank you for the reply.  I tried using the latest version 5.5.0 and observed it generates the courgette jvm report and not able to see the cucumber jvm report

**Comment by prashant-ramcharan** [comment]
The cucumber report will be saved in the location specified in the cucumber options.

https://github.com/prashant-ramcharan/courgette-jvm-example/blob/master/src/test/java/suites/junit/ScenarioSuite.java#L26

````
html:build/cucumber-report/cucumber.html
````

The above means the report will be saved to the `build/cucumber-report` directory
