### ISSUE TITLE
Add tag to disable specified scenario run parallel if using runLevel = CourgetteRunLevel.SCENARIO

### ISSUE THREAD

**Issue by hjh188** [prashant-ramcharan/courgette-jvm#218]
Set runLevel to runLevel = CourgetteRunLevel.SCENARIO. All the scenario run in parallel. My requirement, add tag something like '@parallel_disable' for specified scenario, so that this kind of scenario run in sequence.

**Comment by prashant-ramcharan** [comment]
Courgette loads cucumber tests based on the `CourgetteRunLevel`. This happens before the test run which means it's not possible to mutate the run level during execution.

 Have you considered creating another Courgette runner using `CourgetteRunLevel.FEATURE` just for tests tagged with `@parallel_disable`? This will ensure that all scenarios within each feature are run in sequence.

**Comment by hjh188** [comment]
@prashant-ramcharan thanks for your quick response. I have this requirement because some of my project test scenario probably not support run in parallel. So i need to put this kind of scenario run in sequence. However, if i set runLevel to CourgetteRunLevel.FEATURE, as you know, the report override limitation. So i use scenario parallel run. But hope some of scenario if i given a specified tag, can run in sequence.

I try your suggestion with two runner, i didn't see the report from the two runner in one report. Anything i miss here?

**Comment by prashant-ramcharan** [comment]
@hjh188 If you use 2 runners, you will get 2 separate reports not 1 unfortunately.

I will fix the report override limitation when using `CourgetteRunLevel.FEATURE`

**Comment by prashant-ramcharan** [comment]
@hjh188 

I've now fixed the report override limitation so you can use `CourgetteRunLevel.FEATURE` and `rerunFailedScenarios = true`

Please use version `5.6.0`

**Comment by hjh188** [comment]
Thanks @prashant-ramcharan for your quick support. Just have a try on 5.6.0 for the rerunFailedScenarios feature in FEATURE Level, it works, really cool.
