### ISSUE TITLE
When we use previous version , it was pointing to the js file which is referred in the html file. i hope that being deleted due 5.8.0.

### ISSUE THREAD

**Issue by sowmyasm90** [prashant-ramcharan/courgette-jvm#227]
When we use previous version , it was pointing to the js file which is referred in the html file. i hope that being deleted due 5.8.0.

**Comment by prashant-ramcharan** [comment]
Yes, those `js` and `css` files had security vulnerabilities so needed to be removed from the repo / jar file.

Please use version `5.8.0`

**Comment by sowmyasm90** [comment]
thank you @prashant-ramcharan
