### ISSUE TITLE
is there any way that i can update report portal properties at run time

### ISSUE THREAD

**Issue by sowmyasm90** [prashant-ramcharan/courgette-jvm#228]
is there any way that i can update report portal properties at run time  for launch name and Test suite name based on smoke runner or the regression runner

**Comment by prashant-ramcharan** [comment]
You can pass system properties at runtime.

````
-Drp.testsuite=abc -Drp.launch=abc
````

**Comment by sowmyasm90** [comment]
thank you @prashant-ramcharan
