### ISSUE TITLE
Courgette reports not loading properly

### ISSUE THREAD

**Issue by chmccue** [prashant-ramcharan/courgette-jvm#229]
Recently I have been experiencing issues with the Courgette reports not loading properly (missing HTML styling). It appears there are errors with certain page files loading. I did not make any changes to the core code. Please see screen shot for details.

<img width="1289" alt="Screen Shot 2020-11-30 at 9 37 19 AM" src="https://user-images.githubusercontent.com/1563080/100646898-8aad7f80-32f3-11eb-9d88-4a6388ba4d81.png">

**Comment by prashant-ramcharan** [comment]
These `js` and `css` files had to be removed due to 4 critical security vulnerabilities. 

Please use Courgette version `5.8.0`

**Comment by chmccue** [comment]
Thanks, I see the update to Courgette version 5.8.0 fixed it, however I started encountering some other issues unrelated to your framework due to the Cucumber updates that will require additional investigation. For the time being I will have to use Extent Reports.
