### ISSUE TITLE
Getting "java.io.IOException: Cannot run program java : Create process error=206, The filename or extension is too long" exception 

### ISSUE THREAD

**Issue by karthees05** [prashant-ramcharan/courgette-jvm#230]
Hi,

I am using your latest version of courgette-jvm 5.8.0 for our parallel run.
And I am trying to implement open SSH logic to connect Unix boxes and run the scenarios locally from windows machine.
I am able to run the scenarios without this jvm but when I use this getting the below exception and for both the cases I running Gradle command to execute the tests.

Exception which I am getting is ,

Getting "java.io.IOException: Cannot run program java : Create process error=206, The filename or extension is too long" exception 

Do we have any solution for this.

Thanks,
Karthee

**Comment by prashant-ramcharan** [comment]
Hello,

You can try shortening your classpath on Windows: https://github.com/prashant-ramcharan/courgette-jvm/issues/81#issuecomment-670952436

**Comment by kawalbhatia** [comment]
Hi Prashant, 
Still getting the same issue . I am using Maven to build and run the test. When i execute the runner file through testng.xml without courgette option, it works well. However with Courgette option, it is giving this issue.Please suggest some solution here.

**Comment by prashant-ramcharan** [comment]
**Update**: There is a workaround for this in Courgette version `5.9.2` that accepts a `custom class path`.

See example project here: https://github.com/prashant-ramcharan/courgette-jvm-classpath-example
