### ISSUE TITLE
Courgette Report

### ISSUE THREAD

**Issue by madhu29071984** [prashant-ramcharan/courgette-jvm#231]
Hi Prashant - How to make Courgette report as an emailable report when we trigger job in Jenkins

**Comment by prashant-ramcharan** [comment]
Hi @madhu29071984 

You can use the email extension Jenkins plugin: https://www.jenkins.io/doc/pipeline/steps/email-ext/

In you Jenkins pipeline:

````
emailext attachmentsPattern: 'courgette-report/index.html',
     body: "Add some info here",
     recipientProviders: [developers(), requestor()],
     subject: "Jenkins Tests - Courgette Report"
````

**Comment by madhu29071984** [comment]
Hi Prashant-  My project is free style one. Already email extension plugin is  installed. I made the  below config:

![IMG20201208105554.jpg](https://user-images.githubusercontent.com/63944846/101443997-94af2e00-3944-11eb-9705-cbac7b4364b4.jpg)

![IMG20201208105814.jpg](https://user-images.githubusercontent.com/63944846/101444021-9ed12c80-3944-11eb-8dca-43b408d6dddf.jpg)

![IMG20201208105701.jpg](https://user-images.githubusercontent.com/63944846/101444033-a7296780-3944-11eb-91b8-003ddd4dcd22.jpg)

![IMG20201208105642.jpg](https://user-images.githubusercontent.com/63944846/101444054-b01a3900-3944-11eb-9878-c7a5d9749666.jpg)

After making this change email itself is not getting triggered. Before that I was getting email for both sucess and failure buildsCan you please check and let me know

**Comment by prashant-ramcharan** [comment]
Hello,

As this is not a Courgette issue, I'm not able to advise further.

You should be able to find a solution on StackOverflow if you search "email html report from Jenkins"
