### ISSUE TITLE
Push Test failure screenshot to Report portal

### ISSUE THREAD

**Issue by AsiJKR** [prashant-ramcharan/courgette-jvm#232]
Hi Prashant,

Not an issue, but a question. Can we push our failed test screenshots to the report portal as attachments of the test? So far I see stack trace only. I can see the image present in courgette-report in local. Any advice on this would be helpful. Using the below snippet for taking sc

**private void embedScreenShotToScenario(Scenario scenario) {
        final byte[] screenshot = ((TakesScreenshot)driver)
                .getScreenshotAs(OutputType.BYTES);
        scenario.attach(screenshot, "image/png","screenshot");
    }**

**Comment by prashant-ramcharan** [comment]
Hi @AsiJKR 

The report portal Courgette plugin is limited in functionality in that it uses the report portal `import functionality` to publish test results after test execution. It does not call any report portal APIs during test execution.

https://reportportal.io/docs/Import-data-to

This means Courgette is restricted by the functionality / features defined in  above API.

**Comment by prashant-ramcharan** [comment]
**Update**: Courgette `5.11.0` now supports real time test reporting to Report Portal and includes attachments.
