### ISSUE TITLE
Getting java.lang.NullPointerException at CourgetteNdJsonCreator.java

### ISSUE THREAD

**Issue by BalajiSingh** [prashant-ramcharan/courgette-jvm#233]
![image](https://user-images.githubusercontent.com/17991839/102640334-50abfc80-4180-11eb-9906-9fe45ab1e986.png)

Hi,

I am getting the the above exception may i know what might be the reason though i have included all the dependencies and runner class as written in your forum.

**Comment by prashant-ramcharan** [comment]
Hello,

* What version of Courgette are you using?
* Do you see this exception on every run?
* Are you able to reproduce it with the example project? https://github.com/prashant-ramcharan/courgette-jvm-example

**Comment by BalajiSingh** [comment]
I am using the below version  which is 5.8.0

    testCompile 'io.github.prashant-ramcharan:courgette-jvm:5.8.0'
    testCompile 'io.github.prashant-ramcharan:webdriver-binary-downloader:1.2.2'

Even I am getting this below issue
java.util.NoSuchElementException at Optional.java:135

**Comment by BalajiSingh** [comment]
Can we please connect some time during this week. I am facing two issues which i need to fix it to ensure parallel execution works fine.

My Contact no: 8884479959

**Comment by BalajiSingh** [comment]
Full Details Stack trace for "java.util.NoSuchElementExceptionat Optional.java " is below 

java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at courgette.runtime.CourgetteNdJsonCreator.createTestRunStarted(CourgetteNdJsonCreator.java:199)
	at courgette.runtime.CourgetteNdJsonCreator.mutateMessages(CourgetteNdJsonCreator.java:92)
	at courgette.runtime.CourgetteNdJsonCreator.getScenarioMessages(CourgetteNdJsonCreator.java:88)
	at courgette.runtime.CourgetteNdJsonCreator.createScenarioMessages(CourgetteNdJsonCreator.java:55)
	at courgette.runtime.CourgetteReporter.createMessages(CourgetteReporter.java:123)
	at courgette.runtime.CourgetteReporter.<init>(CourgetteReporter.java:33)
	at courgette.runtime.CourgetteRunner.createCucumberReport(CourgetteRunner.java:166)
	at courgette.api.testng.TestNGCourgette.parallelRun(TestNGCourgette.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:141)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:90)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)

**Comment by prashant-ramcharan** [comment]
To assist further, please provide a GitHub link or attach a demo project that I can replicate this issue with.

**Comment by BalajiSingh** [comment]
HI Prashant,
Below my git repo where i have uploaded my code.
https://github.com/BalajiSingh/Parallel_Testing.git

JDK Version used : 1.8

**Comment by prashant-ramcharan** [comment]
@BalajiSingh  Your project is not configured correctly.

In your `build.gradle`:

As you are using Java 8 - **remove this line**

````
 systemProperties.remove("java.endorsed.dirs")
````

**Remove the Cucumber dependencies** (Courgette is using version 6.9.0 and you are using version 4.8.0)

_Courgette will automatically include the Cucumber deps_

````
testImplementation  "io.cucumber:cucumber-gherkin:${gherkinVersion}"
testImplementation  "io.cucumber:cucumber-java:${cucumberVersion}"
testImplementation  "io.cucumber:cucumber-jvm:${cucumberVersion}"
testImplementation  "io.cucumber:cucumber-core:${cucumberVersion}"
testImplementation  "io.cucumber:cucumber-testng:${cucumberVersion}"
compile group: 'io.cucumber', name: 'cucumber-core', version: '4.8.0'
````

As you using Cucumber dependencies in `src\main`, you should **change this to `compile`** instead of `testCompile`

````
compile 'io.github.prashant-ramcharan:courgette-jvm:5.8.0'
````

**Comment by BalajiSingh** [comment]
Thanks Prashant. I will do the necessary changes as you said and i will revert back to you.

**Comment by BalajiSingh** [comment]
HI Prashant,

I have removed all the cucumber deps , removed the statement "systemProperties.remove("java.endorsed.dirs")"  and used the "compile 'io.github.prashant-ramcharan:courgette-jvm:5.8.0' " but still  am facing the same issue though updating the changes and having updated the build.gradle file.

Below is updated  build.gradle file
=======================


		plugins { 
			      id 'java'
			      id 'maven-publish' 
			      id 'java-library'  
			      id 'groovy'   
			      id 'eclipse'  
			     // id 'io.qameta.allure' version '2.8.1'
			   }
		
		
		
	//	compileJava {
		//    sourceCompatibility = 1.8
		  //  targetCompatibility = 1.8
	//	}
		
		repositories {
		    jcenter()
		    mavenCentral()
		}
		def cucumberVersion = '4.8.0'
		def gherkinVersion  = '5.1.0'
		def hamcrestVersion = '1.3'
		
		def testngVersion = '6.14.3'
		def cucumber4adapterVersion = '1.0.11'
		
		def Log4jVersion = '1.2.17'
		def slf4jVersion = '1.7.5'
		
		def restassuredVersion = '3.3.0'
		def jsonsimpleVersion = '1.1.1'
		
		def appiumjavaClientVersion = '7.3.0'
		
		def allurePluginVersion = '2.8.1'
		def allurecucumber4jvmVersion = '2.13.0'
		def codeborneselenideVersion = '5.3.1'
		
		def apacheJMeterVersion = '2.2'
		def jdkIntClassesVersion = '4.5'
		def azureSDKVersion = '1.36.3'
		def azureClientAuthVersion = '1.0.0-beta1'
		def azureStorageClientSDKVersion = '8.6.5'
		def azureBlobStorageVersion = '12.0.0'
		def azureCommonStorageVersion = '12.9.0-beta.2'
		def fasterXMLJacksonCoreVersion = '2.2.3'
		def fasterXMLJacksonAnnotationsVersion = '2.1.2'
		def commonsCodecVersion = '1.6'
		def commonsLoggingVersion = '1.1.3'
		def dom4jVersion = '2.1.3'
		def orgJSONVersion = '20140107'
		def orgJSONSimpleVersion = '1.1.1'
		def okioVersion = '1.13.0'
		def apachePOIVersion = '3.9'
		def unirestVersion = '1.4.7'
		def xmlBeansVersion = '2.3.0'
		
		dependencies {
		    compile group: 'org.testng', name: 'testng', version: '6.13.1'
		    compile group: 'org.seleniumhq.selenium', name: 'selenium-chrome-driver', version: '4.0.0-alpha-3'
		    compile group: 'org.seleniumhq.selenium', name: 'selenium-firefox-driver', version: '3.11.0'
		
		    compile 'io.github.prashant-ramcharan:courgette-jvm:5.8.0'
		    compile 'io.github.prashant-ramcharan:webdriver-binary-downloader:1.2.2'
		
		   	
		    //Cucumber Adapter Extent Reports
		    //testImplementation  'com.aventstack:extentreports:4.0.9'   // Do not use this when you are using Cucumber Adapter Extent reports. Not Required when Adapter used
		    testImplementation  "com.aventstack:extentreports-cucumber4-adapter:${cucumber4adapterVersion}"
		
		    //Log4j Logs
		    implementation "log4j:log4j:${Log4jVersion}"  //Do not change from implementation to testImplementation otherwise  PropertyConfigurator and Logger will throw errors
		
		    //Rest Assured Apis
		    testImplementation "io.rest-assured:rest-assured:${restassuredVersion}"
		    testImplementation "com.googlecode.json-simple:json-simple:${jsonsimpleVersion}"
		    testImplementation 'org.json:json:20180813'
		
		    //Selenium Apis
		   compile group: 'org.seleniumhq.selenium', name: 'selenium-server', version: '3.141.59'
		//    implementation 'com.paulhammant:ngwebdriver:1.1.4'
		    implementation 'org.seleniumhq.selenium:selenium-java:3.141.59'
		    compile group: 'org.seleniumhq.selenium', name: 'selenium-htmlunit-driver', version: '2.52.0'
		    //Allure Reports
		    testImplementation "io.qameta.allure:allure-cucumber4-jvm:${allurecucumber4jvmVersion}"
		    implementation "io.qameta.allure:allure-selenide:${allurecucumber4jvmVersion}"
		    implementation "com.codeborne:selenide:${codeborneselenideVersion}"
		
		    //Appium
		    implementation "io.appium:java-client:${appiumjavaClientVersion}"
		
		    //Azure
		    //Azure SDK
		    compile group: 'com.microsoft.azure', name: 'azure', version: azureSDKVersion
		    //Azure Client Authentication
		    testCompile group: 'com.microsoft.azure', name: 'azure-client-authentication', version: azureClientAuthVersion
		    //Azure Storage Client SDK
		    compile group: 'com.microsoft.azure', name: 'azure-storage', version: azureStorageClientSDKVersion
		    //Azure Blob Storage
		    compile group: 'com.azure', name: 'azure-storage-blob', version: azureBlobStorageVersion
		    //Azure Common Storage
		    compile group: 'com.azure', name: 'azure-storage-common', version: azureCommonStorageVersion
		
		    //FasterXML (Jackson)
		    //Jackson Core
		    compile group: 'com.fasterxml.jackson.core', name: 'jackson-core', version: fasterXMLJacksonCoreVersion
		    //Jackson Annotations
		    compile group: 'com.fasterxml.jackson.core', name: 'jackson-annotations', version: fasterXMLJacksonAnnotationsVersion
		
		    //Commons
		    //Commons Codec
		    compile group: 'commons-codec', name: 'commons-codec', version: commonsCodecVersion
		    //Commons Logging
		    compile group: 'commons-logging', name: 'commons-logging', version: commonsLoggingVersion
		
		    //Dom4j
		    compile group: 'org.dom4j', name: 'dom4j', version: dom4jVersion
		
		    //JSON
		    compile group: 'org.json', name: 'json', version: orgJSONVersion
		    compile group: 'com.googlecode.json-simple', name: 'json-simple', version: orgJSONSimpleVersion
		
		    //Okio
		    compile group: 'com.squareup.okio', name: 'okio', version: okioVersion
		
		    //ApachePOI
		    //POI
		    compile group: 'org.apache.poi', name: 'poi', version: apachePOIVersion
		    //POI OOXML
		    compile group: 'org.apache.poi', name: 'poi-ooxml', version: apachePOIVersion
		    //POI OOXML Schemas
		    compile group: 'org.apache.poi', name: 'poi-ooxml-schemas', version: apachePOIVersion
		
		    //Unirest
		    compile group: 'com.mashape.unirest', name: 'unirest-java', version: unirestVersion
		
		    //XMLBeans
		    compile group: 'org.apache.xmlbeans', name: 'xmlbeans', version: xmlBeansVersion
		
		    //Netty Jar is important
		    compile group: 'io.netty', name: 'netty-all', version: '4.1.31.Final'
		
		    //AspectJweaver
		    runtime group: 'org.aspectj', name: 'aspectjweaver', version: '1.9.6'
		
		    compile group: 'com.browserstack', name: 'browserstack-integration', version: '1.0.0'
		    compile group: 'com.browserstack', name: 'browserstack-local-java', version: '0.3.0'
		
		    compile group: 'org.mongodb', name: 'mongo-java-driver', version: '3.12.7'
		
		    //SqlServer
		    // https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc
		    compile group: 'com.microsoft.sqlserver', name: 'mssql-jdbc', version: '7.2.1.jre8'
		
		    // External Jar files
		    // compile fileTree(dir: 'java_lib', include: ['*.jar'])
		
		
		  
		    compile fileTree(dir: 'libs', include: 'testng-6.14.3.jar')   //This should be last statement
		
		
		}
		
		
		
		
		/* TestNG Specific Tasks
		----------------------------------------------------
		*/
		task runTest(type: Test) {
		 //   dependsOn compileJava, assemble, testClasses
		    useTestNG()
		
		    systemProperty("browser", "chrome")
		
		    include '**/lib/testng-6.14.3.jar'
		    include '**/suites/testng/ChromeTestSuite.class'
		    outputs.upToDateWhen { false }
		}
		
		task runFirefoxTestsUsingTestNG(type: Test) {
		    useTestNG()
		
		    systemProperty("browser", "firefox")
		
		    include '**/suites/testng/FirefoxTestSuite.class'
		    outputs.upToDateWhen { false }
		}

**Comment by prashant-ramcharan** [comment]
I was able to run your project without issues after doing the changes I referred to above.

As mentioned, please use the examples projects as a reference to setting up your project correctly.

**Comment by BalajiSingh** [comment]
![image](https://user-images.githubusercontent.com/17991839/103101161-4edcb000-463c-11eb-8d95-2a9ad14d6f61.png)

**Comment by prashant-ramcharan** [comment]
I was able to run your project without issues (_although the tests did fail_)

**View Courgette Report here**:  [Courgette Report.zip](https://github.com/prashant-ramcharan/courgette-jvm/files/5740273/Courgette.Report.zip)

https://reports.cucumber.io/reports/fcf15c30-ec8b-4c4d-b534-f35ab96f6e57

Please make sure your Java version is correct and environment is setup correctly.

**I'm unable to support any further to fix your project**. 

Please use the example projects as a reference to resolve your issue on your machine.

**Comment by BalajiSingh** [comment]
Hi Prashant,

I would definitely call it as in issue here. I think this exception has to be handled up correctly. I have done the setup correctly from my side hence able to run all other projects successfully.

The NoSuchElement exception raised in this case is totally different than the one of Selenium. As you can see, it's part of java.util package, not org.openqa.selenium.NoSuchElementException. The function from the Optional that is returning this exception is most probably this: public T get() { if (value == null) { throw new NoSuchElementException("No value present"); } return value; }.

Having said that  I believe this exception should be handled from your side .

And it is more clear that from above snapshot or pic which summarizes the issue.

**Comment by BalajiSingh** [comment]
May I know the what version of the JDK and setup you have. Looks bit wired when it is working for you then it should also work for me.

**Comment by prashant-ramcharan** [comment]
I will handle the null pointer exception but this will still not fix your issue. 

The tests are not running your machine so when it try’s to create the report, it fails with the NPE because there’s no data to create the report with.

I suggest you use Cucumber parallel functionality in the mean time..

https://cucumber.io/docs/guides/parallel-execution/

**Comment by prashant-ramcharan** [comment]
> May I know the what version of the JDK and setup you have. Looks bit wired when it is working for you then it should also work for me.

The Java version is shown in the Courgette report!

**Comment by prashant-ramcharan** [comment]
Handling the null pointer exception should be a quick fix. 

But back to my initial question, do you get the same error / exception when using the Courgette example project?

**Comment by prashant-ramcharan** [comment]
@BalajiSingh You can now use Courgette version `5.8.1` which resolves the NPE.

**Comment by BalajiSingh** [comment]
@prashant-ramcharan  : First of all Thanks a lot for your quick support.

**Comment by BalajiSingh** [comment]
@prashant-ramcharan 👍 
Thanks for the info as part of the bug fix and new release. I will surely try and I will keep you updated on this new version.

Sorry couldn't reply back to your question as I was out of town for two days. But then today I  Just revisited on the issue that I raised previously  and also got to about the issue with  one collection which was not initialized properly as per jdk 1.8 ,and using Courgette it just throwing Nullpointer exception and with bit of more tweaking on Jre stuff it would report an issue on Optinal.java class.  But without Courgette things were working fine  Even the  stack trace was not very clear as part of root cause to debug and resolve it. But then just took a different  path of checking all the problems as shown in problems tab in Eclipse console and rectified these Collections initialization issues and then ran the suite then it started working.  

Thanks for the Fix also that would reply help me and others those are  working on parallel Testing using your Courgette.

Once agian thanks a lot Prashant.

**Comment by BalajiSingh** [comment]
I have one more query : its on the reporting part. Iam getting the reports as shown below 
![image](https://user-images.githubusercontent.com/17991839/103166531-e0207200-4848-11eb-91c5-620d54af3783.png)

But then i need reports like below , can you please advise me here as what needs to be done
![image](https://user-images.githubusercontent.com/17991839/103166559-49a08080-4849-11eb-85fd-bc0bd5f0c0b8.png)

**Comment by BalajiSingh** [comment]
Second Query : I need the reports to be generated in particular location but by default i uderstand ( after reading your Forum ) it places the report to "/build/<dir>" .
Can we change the reports path say for example i need reports to generated in 
"Automation_Report/Reports/ExtentReport.html"

![image](https://user-images.githubusercontent.com/17991839/103166669-74d79f80-484a-11eb-9bba-1d04125d50a2.png)

**Comment by BalajiSingh** [comment]
Third Query : Can we Integrate Allure reports ?

**Comment by BalajiSingh** [comment]
**I have used  the latest Release 5.8.1 and its working fine**

**Comment by prashant-ramcharan** [comment]
In response to your other queries:

1. Courgette uses the `ExtentSparkReporter` and this is the theme used in Extent Reports library.
2. Courgette will save your reports to any valid directory in your file system. Simply change the `reportTargetDir` in your runner.
3. There's no plans on integrating Allure reports at the moment.
