### ISSUE TITLE
Upgraded from 3.3.0 to the latest version and now getting OOME in Jenkins

### ISSUE THREAD

**Issue by neo81-83** [prashant-ramcharan/courgette-jvm#235]
Upgraded from 3.3.0 to the latest version and now getting OOME in Jenkins. [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project automation: Fatal error compiling: java.lang.OutOfMemoryError: SimpleFileObject <path of the class file>

Getting above error in Jenkins only, tried various heap settings but nothing seems to work. Locally things work good.

**Comment by prashant-ramcharan** [comment]
Your message shows a **compilation** error `Fatal error compiling: java.lang.OutOfMemoryError`

This does not appear to be related to Courgette as no tests have been run to raise the OOME.

Can you please provide the full stacktrace?

**Comment by neo81-83** [comment]
Never mind solved the issue by increasing the heap settings of maven-compiler plugin.
