### ISSUE TITLE
Cucumber

### ISSUE THREAD

**Issue by smartserega** [prashant-ramcharan/courgette-jvm#238]
Hello, sorry for bother you again. Have you solved this problem? I see it in your project too
https://recordit.co/A8UdYSFo7n

**Comment by smartserega** [comment]
Using Courgette i can pass only steps without paremeters, other way i recieved "io.cucumber.core.exception.CucumberException: .......However, the gherkin step has 0 arguments".
do you have same problem?

**Comment by prashant-ramcharan** [comment]
Hello, 

You need to **update your IntelliJ** to the latest version as the plugin is most likely out of date.

**Comment by smartserega** [comment]
Fantstic! You are riht again!
