### ISSUE TITLE
report

### ISSUE THREAD

**Issue by nealarmstronglumira** [prashant-ramcharan/courgette-jvm#24]
The report in the readme file looks really good, mine does not look like that
<img width="687" alt="screen shot 2018-02-02 at 3 20 56 pm" src="https://user-images.githubusercontent.com/28905671/35753209-c164f93a-082c-11e8-952b-0b12ace41fd6.png">

**Comment by prashant-ramcharan** [comment]
You looking at the cucumber report. 

Look in the the folder ../target/courgette-report.

And ensure you have the latest version of Courgette-JVM

**Comment by nealarmstronglumira** [comment]
👍  very nice work here. Thanks!
