### ISSUE TITLE
multi scenario

### ISSUE THREAD

**Issue by smartserega** [prashant-ramcharan/courgette-jvm#241]
Hello!
Now all fine Courgette is working ! Thank you!

Please let me know how to start Courgette with two or more tags (multi scenarios):

-ea -Dcucumber.tags="@tag1" - works correct (one scenario)

but
-ea -Dcucumber.tags="@tag1 and @tag2" (two or more scenarios)
-ea -Dcucumber.tags="@tag1,@tag2"
-ea -Dcucumber.tags="@tag1,@tag2
does not work at all.

**Comment by prashant-ramcharan** [comment]
If you want both tags to to be picked up (_i.e. you have scenarios having either tag_) then you have to use an `or` instead of `and`

````
-Dcucumber.tags="@tag1 or @tag2"
````

https://cucumber.io/docs/cucumber/api/#tags

**Comment by smartserega** [comment]
thank you.
