### ISSUE TITLE
breakpoints

### ISSUE THREAD

**Issue by smartserega** [prashant-ramcharan/courgette-jvm#243]
I have problem with breakpoints in debug mode. intellij does not stop on breakpoints, i am not able to debug code. When i dont using courgette breakpoints works. Do you have same problems with intellij  using courgette or it this is something specical?

**Comment by prashant-ramcharan** [comment]
When using the Courgette runner, you won't be able to debug the tests because the tests are run in a separate process (JVM).

You should continue use the Cucumber plugin / IDE to continue to debug tests.

**Comment by smartserega** [comment]
so i shoud have two runners - courgette runner to debug and old runner to debug tests?

may one theread solve this problem?

**Comment by prashant-ramcharan** [comment]
No, you would only need 1 Courgette runner.

May I ask, why do you need to debug Cucumber test using the runner? 

If you want to debug your Cucumber tests, you should use the Cucumber plugin in IntelliJ.

The Courgette runner runs all your tests in parallel but it wont allow you to debug individual tests running in parallel because there's no way to do this.

**Comment by smartserega** [comment]
When i start tests, i am starting runner. If some steps,metods (it is about java code) etd need to be debug i am using breakpoins. But Courgette runner avoid my breakpoints. And i can not understand how to debug my code. My idea about two runners looks like solution of this problem. I can use one runner for parallel test and second for debug.

About plugin, i already have Cucumber Java Plagin, but in does not help.

**Comment by prashant-ramcharan** [comment]
That's odd about the Cucumber Java Plugin. You should be able to put a break point in your Java code and right click the `feature file` and select `Debug`

<img width="576" alt="Screenshot 2021-01-20 at 09 50 33" src="https://user-images.githubusercontent.com/2563149/105157551-00201a00-5b05-11eb-8685-ee72e703dc40.png">


Yes, you can have a Cucumber runner if you like as this will be able to debug individual tests.

**Comment by smartserega** [comment]
oy.. thank you. This is new feature for me. Thank you again.
