### ISSUE TITLE
Passing tests are marked/logged as 'ignored' or 'skipped'

### ISSUE THREAD

**Issue by avanish-vaghela** [prashant-ramcharan/courgette-jvm#244]
Hi, 

Executing tests using JUnit marks the passing tests as either 'ignored' or 'skipped'. I initially encountered this issue while setting up a test framework since I was able to reproduce it using the example project: https://github.com/prashant-ramcharan/courgette-jvm-selenium.

**Courgette Cucumber report:** 
Courgette published your Cucumber Report to:
https://reports.cucumber.io/reports/22c0c467-2aea-41d1-901e-40b95177ce83

**IntelliJ IDEA Screenshot:** 
![IntelliJ-IDEA-tests-marked-as-skipped-or-ignored-2021-01-20 14_23_55-](https://user-images.githubusercontent.com/51115451/105188101-7172c380-5b2b-11eb-8555-67e6bf9d092d.png)

**Gradle report:**
[runChromeTestsUsingJUnit.zip](https://github.com/prashant-ramcharan/courgette-jvm-selenium/files/5843073/runChromeTestsUsingJUnit.zip)

Let me know if any further information is required.

Many thanks!

**Comment by prashant-ramcharan** [comment]
Hi @avanish-vaghela 

I fixed this in Courgette version `5.9.0` - please use this version.

**Comment by avanish-vaghela** [comment]
@prashant-ramcharan That's wonderful news. I just tried it and it seems to be working fine. Thank you again for this great utility.
