### ISSUE TITLE
Allure

### ISSUE THREAD

**Issue by smartserega** [prashant-ramcharan/courgette-jvm#246]
Hello, 
please, kindly, inform - may i use allure report with courgette or i am able to use only courgette report?

**Comment by prashant-ramcharan** [comment]
Hello,

You should be able to use Courgette with Allure without any extra setup.

I will provide an example project to demonstrate this.

**Comment by prashant-ramcharan** [comment]
Please see example here: https://github.com/prashant-ramcharan/courgette-jvm-allure-example
