### ISSUE TITLE
ThreadLocal hashmap is not working with Courgette plugin

### ISSUE THREAD

**Issue by PriyaMani328** [prashant-ramcharan/courgette-jvm#253]
For Parallel execution , I am using Courgette.class for cucumber tests.
I am maintaining test data in ThreadLocal Map and disturb it during the execution time using get() method.
@CourgetteBeforeAll - I am initialising the map as below
static ThreadLocal<Map<String, String>> testdatalist = new ThreadLocal<>(); and set the data
When it comes to scenario line, i am trying to get the test data using classname.testdatalist.get() method.
I am getting null pointer exception and when i debugged i see different thread id's.

If i use the same script with cucumber.class, then i see the same thread id used both during initialisation and while getting the data from the map in execution time and no null pointer exception occurs. 

Could you please help me?

**Comment by prashant-ramcharan** [comment]
Hi,

`Courgette hooks` will not allow you to initialise data for your tests. You need to use Cucumber hooks to initialise data for your tests.

`CourgetteBeforeAll` and `CourgetteAfterAll` hooks runs in a separate process and does not share the same JVM as the Cucumber tests. This is why you cannot share static variables to the tests.

Courgette hooks are there to allow for setting up external "things" to your tests. Cucumber hooks should still be used to setup data for your Cucumber tests.

**Comment by PriyaMani328** [comment]
Thanks for your quick response.

Cucumber hooks will execute before and after every scenarios but I want to
do the test data setup only once and remove it at end of the execution. So
I am looking for before class and after class annotations.

**Comment by prashant-ramcharan** [comment]
@PriyaMani328 As previously mentioned, you will not be able to share a static variable across different JVMs.

What you could potentially do is use a `CourgetteBeforeAll` hook to setup your test data and write this to a file and then use a Cucumber hook to read from this file.

**Courgette Hook**

_This will setup your data and write it to the build directory._
````java
// your Courgette runner

    @CourgetteBeforeAll
    public static void createTestData() throws IOException {
        ObjectMapper objectMapper = new ObjectMapper();

        HashMap<String, String> testData = new HashMap<>();
        testData.put("FirstName", "Courgette");
        testData.put("Surname", "JVM");

        objectMapper.writer().writeValue(new File("build/testdata.json"), testData);
    }

````

**Cucumber Hook**

_This will read from your test data file and will be available to all tests that are run in parallel_
````java
// your cucumber hook

    @Before
    public void before() throws IOException {
        ObjectMapper objectMapper = new ObjectMapper();

        HashMap testData = objectMapper.reader().readValue(new File("build/testdata.json"), HashMap.class);

        System.out.println(testData.entrySet());
    }

````

**Comment by prashant-ramcharan** [comment]
Closing issue as this is not possible using Courgette.

Please try workaround above.
