### ISSUE TITLE
tests order

### ISSUE THREAD

**Issue by smartserega** [prashant-ramcharan/courgette-jvm#255]
Hello, 

1. Do we have opportuniti to start tests in custom order? Us i uderstand tests starts is random order. 

2. Is any way to start one scenarion (or feature) in one thread and other scenarion (or feature) in second thread?

**Comment by prashant-ramcharan** [comment]
Hey @smartserega 

1. Tests are loaded using the Cucumber feature loader so there's no guaranteeing the order in which it is loaded.

2. If you use `CourgetteRunLevel.FEATURE` then each feature will run in its own thread.  Courgette **does not** run more than 1 feature / scenario per thread.
