### ISSUE TITLE
Error: Could not find or load main class io.cucumber.core.cli.Main

### ISSUE THREAD

**Issue by sharti** [prashant-ramcharan/courgette-jvm#256]
Hi Prashant,

I have been using latest version of cougrette that is 5.9.2 with Junit 4.13.1 along with Junit Jupiter and vintage version 5.7.0
Unfortunately, my cucumber tests are not being triggered it just throws
Error: Could not find or load main class io.cucumber.core.cli.Main
Caused by: java.lang.ClassNotFoundException: io.cucumber.core.cli.Main
Along with :
There were errors when running the test. Refer to the console for more information.
courgette.runtime.CourgetteTestErrorException: There were errors when running the test. Refer to the console for more information.
below is my testRunner:
@RunWith(Courgette.class)
@CourgetteOptions(

threads = 1,
runLevel = CourgetteRunLevel.SCENARIO,
rerunFailedScenarios = true,
rerunAttempts = 3,
showTestOutput = true,
reportTargetDir = "build",
classPath = {"build/libs/*", "build/classes/java/test"},
cucumberOptions = @CucumberOptions(
    features = "fne/lls/src/test/resources/com/flexnetls/automation/",
    glue={"com.flexnetls.automation.stepdefs"},
    plugin = {
        "pretty",
        "json:build/cucumber-report/cucumber.json",
        "html:build/cucumber-report/cucumber.html",
        "junit:build/cucumber-report/cucumber.xml"

    },
    monochrome = true
)
)
public class CucumberTestRunner {
@CourgetteBeforeAll
public static void setup() {
System.out.println("before all");
}
}
gradle dependencies, test and cucumber tasks are as below:
dependencies {

compile group: 'org.aspectj', name: 'aspectjweaver', version: '1.9.4'
compile group: 'io.github.prashant-ramcharan', name: 'courgette-jvm', version: '5.9.2'
testRuntime group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.7.0'
testRuntime group: 'org.junit.vintage', name: 'junit-vintage-engine', version: '5.7.0'
testImplementation group: 'junit', name: 'junit', version: '4.13.1'
testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.7.0'
testImplementation group: 'io.cucumber', name: 'cucumber-java8', version: '6.9.1'
testImplementation group: 'io.cucumber', name: 'cucumber-junit', version: '6.9.1'
}
test {
dependsOn copyLibs
doFirst {
// def cp = CollectionUtils.join(File.pathSeparator, classpath.getFiles())
// environment 'CLASSPATH', cp
// classpath = classpath.filter { false }
def weaver = configurations.compile.find { it.name.contains("aspectjweaver") }
systemProperties System.getProperties()
scanForTestClasses = false
if (System.getProperty('DEBUG', 'false') == 'true') {
jvmArgs '-Xdebug',
'-Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=*:9009'

        jvmArgs = jvmArgs << "-javaagent:${weaver}"
    } else {
        jvmArgs = jvmArgs << "-javaagent:${weaver}"
    }
}
useJUnitPlatform()
testLogging {
    events "PASSED", "SKIPPED", "FAILED"
}
testLogging.showStandardStreams = true
testLogging.exceptionFormat = 'full'

reports {
    junitXml.enabled = true
    html.enabled = true
}

afterSuite { desc, result ->
    result.exception?.printStackTrace()
    if (!desc.parent) {
        println "\nJunit Test result: ${result.resultType}"
        println "Junit Test summary: ${result.testCount} tests, " +
                "${result.successfulTestCount} succeeded, " +
                "${result.failedTestCount} failed, " +
                "${result.skippedTestCount} skipped"
    }
}
//exclude("**/*")
}
task cucumber {
dependsOn assemble, compileTestJava
doLast {
javaexec {
main = "io.cucumber.core.cli.Main"
classpath = configurations.cucumberRuntime + sourceSets.main.output + sourceSets.test.output
args = ['--plugin', 'pretty', '--glue', 'com.flexnetls.automation.stepdefs', 'src/test/resources/com/flexnetls/automation']
}
}

}

Any help is highly appreciated.

**Comment by sharti** [comment]
Adding on to the above issue, looks like the customPath has issue. I did try to compile and run the project https://github.com/prashant-ramcharan/courgette-jvm-classpath-example.git seeing the same issue.

**Comment by prashant-ramcharan** [comment]
@sharti 

Can you see all the jar files in `build/libs/` directory? 

With regards to the example project  - same question as above.

Also, try running the task `gradle runTest` in the example project.

**Comment by sharti** [comment]
@prashant-ramcharan , thanks for the reply!!

I did face that issue on windows, that is the reason I used classPath configuration. If i run just the runTest it works fine. However, i we do a clean build it fails with the Could not find or load main class io.cucumber.core.cli.Main error. 

However, the main issues what im after is the path if in case i have module project like as shown below :

![image](https://user-images.githubusercontent.com/47098239/107966472-e96cc600-6fd1-11eb-906b-131ad7e57c50.png)

in my case, what would be the classPath variable for jars and test class for instance, if i provide the full path it works fine.
classPath = {
      "E:/IdeaProjects/swmrunner/swm-common-e2etestsuite-runner/fne/lls/build/libs/*",
      "E:/IdeaProjects/swmrunner/swm-common-e2etestsuite-runner/fne/lls/build/classes/java/test"
    },
any suggestions here??

**Comment by prashant-ramcharan** [comment]
>However, i we do a clean build it fails with the Could not find or load main class io.cucumber.core.cli.Main error.

The jars would have to be copied to the location defined in your runner. This is why you need a `copyLibs` task that copies your project jar files. This gradle task has to **run first** before the build / test task. 

>in my case, what would be the classPath variable for jars and test class for instance, if i provide the full path it works fine.

You wouldn't need to specify an absolute path. If you running a gradle task from the `fne/lls` module then the runner would be looking for the jars and test classes in `fne/lls/build` directory.

Your Courgette runner should still point the build directory because you running the gradle task from the `lls` module:

````java
 classPath = {"build/libs/*", "build/classes/java/test"},
````

**Comment by sharti** [comment]
Yes, i did try with relative path like in my code i had it as 
`classPath = {
      "/build/libs/*",
      "/build/classes/java/test"
    },`
or
`classPath = {
      "fne/lls/build/libs/*",
      "fne/lls/build/classes/java/test"
    }`
in both the case i get the error execution error 
`Error: Could not find or load main class io.cucumber.core.cli.Main
Caused by: java.lang.ClassNotFoundException: io.cucumber.core.cli.Main
Error: Could not find or load main class io.cucumber.core.cli.Main
Caused by: java.lang.ClassNotFoundException: io.cucumber.core.cli.Main
before all
AfterAll

There were errors when running the test. Refer to the console for more information.
courgette.runtime.CourgetteTestErrorException: There were errors when running the test. Refer to the console for more information.
`
Im not seeing this issue on giving absolute path.

**Comment by prashant-ramcharan** [comment]
Are you able to provide a demo project for me to use?

**Comment by sharti** [comment]
il see if I can share the demo project (will have to check the company policies). Perhaps, a call would do?

**Comment by prashant-ramcharan** [comment]
I don't need your company project.. just need a demo project that can replicate your issue. You can even re-use the Courgette example project if you want.

**Comment by sharti** [comment]
[swm-common-e2etestsuite-runner.zip](https://github.com/prashant-ramcharan/courgette-jvm/files/5987534/swm-common-e2etestsuite-runner.zip)
Attaching the sample project
Also, another thing i would like to know is the beforeAll implementation. Not sure if i have missed anything in there, they seem to be executing after the scenario and not before scenario.

**Comment by prashant-ramcharan** [comment]
Just tried using your project and the runner works fine with the relative class path.

https://recordit.co/SDnVOOOBIt

Because you are using a multi module project, **you have to run the gradle task from the sub project / module.**

You have to run the gradle task from the `lls` project directory.

````cmd
cd fne\lls
gradle runFeatureFile
````

````gradle
task runFeatureFile(type: Test) {
    include '**/CucumberTestRunner.class'
    outputs.upToDateWhen { false }
}
````

````java
@RunWith(Courgette.class)
@CourgetteOptions(
        threads = 1,
        runLevel = CourgetteRunLevel.SCENARIO,
        rerunFailedScenarios = true,
        rerunAttempts = 3,
        showTestOutput = true,
        reportTargetDir = "build",
        classPath = {"build/libs/*", "build/classes/java/test"},
        cucumberOptions =
        @CucumberOptions(
                features = "src/test/resources/features",
                glue = {"com.flexnetls.automation.stepdefs"},
                plugin = {"pretty",
                        "json:build/cucumber-report/cucumber.json",
                        "html:build/cucumber-report/cucumber.html",
                        "junit:build/cucumber-report/cucumber.xml"
                },
                monochrome = true))
```

**Comment by sharti** [comment]
@prashant-ramcharan ,
I was actually running from the base directory using the command gradle :fne:lls:clean build 
This should also work isn't it? 

Also, even though i run the from /fne/lls/ directory the beforeAll statements are not executed am I missing anything?

**Comment by prashant-ramcharan** [comment]
@sharti 

Using `gradle :fne:lls:clean build`, this is unlikely to work because your test runner has relative paths. 

Gradle uses **multi-projects** so if you want to use relative paths, you have to run from the **sub project** (i.e. lls)


In your `Courgette hooks` you simply printing out to the console so you need to`showStandardStreams` in your `build.gradle` 


```gradle
tasks.withType(Test) {
  testLogging.showStandardStreams = true
}
```

**Comment by sharti** [comment]
> @sharti
> 
> Using `gradle :fne:lls:clean build` to run your tests is unlikely to work because your test runner has relative paths.
> 
> Gradle uses **multi-projects** so if you want to use relative paths, you have to run from the **sub project** (i.e. lls)
> 
> In your `Courgette hooks` you simply printing out to the console so you need to`showStandardStreams` in your `build.gradle`
> 
> ```groovy-gradle
> tasks.withType(Test) {
>   testLogging.showStandardStreams = true
> }
> ```

I had tried using testLogging.showStandardStreams = true option as suggested above. The printing happens after all the scenarios only. 
`tasks.withType(Test) {
    dependsOn copyLibs
    testLogging.showStandardStreams = true
    systemProperties = System.getProperties() as Map<String, ?>
    systemProperties.remove("java.endorsed.dirs")

}`

Output is as below:
`> Task :fne:lls:runFeatureFile
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Scenario: This is second test scenario [90m# src/test/resources/features/Test1.feature:6[0m
----------------This is second test scenario

    this is scenario name

tested 2
  [32mGiven [0m[32mthe user is a testers[0m          [90m# com.flexnetls.automation.stepdefs.sampleStepDef.<init>(sampleStepDef.java:23)[0m

1 Scenarios ([32m1 passed[0m)
1 Steps ([32m1 passed[0m)
0m1.373s
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Scenario: This is first test scenario [90m# src/test/resources/features/Test1.feature:3[0m
----------------This is first test scenario

    this is scenario name

hello test 1
  [32mGiven [0m[32mthe user is a tester[0m          [90m# com.flexnetls.automation.stepdefs.sampleStepDef.<init>(sampleStepDef.java:17)[0m

1 Scenarios ([32m1 passed[0m)
1 Steps ([32m1 passed[0m)
0m1.336s
before all
AfterAll
`

**Comment by prashant-ramcharan** [comment]
This is not a reflection of what actually happened. Courgette cannot control the way in which Gradle prints things to the console.

If you add this to your Courgette runner, you will notice the message in the console and no tests will run.

````java
 @CourgetteBeforeAll
    public static void setup() {
        System.out.println("before all - I will quit!!");
        System.exit(0);
    }
````

**Comment by sharti** [comment]
Ok, are you saying the execution actually happens before the scenario and the Gradle prints at the last?

**Comment by prashant-ramcharan** [comment]
Yes, that's correct. Gradle prints at the end but the execution would have happened in the Courgette hooks.

**Comment by sharti** [comment]
All right!! Thanks @prashant-ramcharan for timely response!! Much appreciated!!
