### ISSUE TITLE
1 test getting executed instead of parallel when thread is set to 20

### ISSUE THREAD

**Issue by neo81-83** [prashant-ramcharan/courgette-jvm#258]
Hello Ram,

I am using latest version and trying to execute a suite of 2000 scenarios with 25 threads. For the first 3 hrs. (approx.) the suite runs fine and I can see Jenkins console logs that the tests are getting executed in parallel BUT after some time the parallel execution stops and the tests run 1 by 1 leading to longer execution time.

I am using following maven-failsafe heap settings 
```
<argLine>-Xms32g -Xmx64g -XX:MaxPermSize=16g</argLine>
<reuseForks>false</reuseForks>
```
My Jenkins node has 128 GB RAM, also I have turned off HTML reporting both Courgette and Cucumber. What could be the problem?

**Comment by prashant-ramcharan** [comment]
Hello,

Do you have any other cucumber runners in your project or perhaps defined in your pom.xml?

**Comment by neo81-83** [comment]
No, i don't have any other runner but just one. Logs are huge and due to privacy concern can't share. When I see the Jenkins logs I can very well see only 1 scenario is getting executed at a time whilst 3 hrs. ago execution was happening in parallel. Memory/CPU during the execution of Jenkins node also looks to be ok, only 70% utilized.

**Comment by prashant-ramcharan** [comment]
I'm not able to reproduce this at all. You could try using a Java profiler when your tests are running in Jenkins to check if the Courgette process is still running and if threads are being created.

A tool such as VisualVM would be helpful for this (https://visualvm.github.io/)

**Comment by neo81-83** [comment]
Can you point me to the stable version of Courgette that's using initial version of Cucumber 5?

**Comment by prashant-ramcharan** [comment]
You can use Courgette version `4.4.0` which has Cucumber version `5.5.0`

**Comment by prashant-ramcharan** [comment]
Closing issue - please re-open if you can provide a project I can reproduce this with.
