### ISSUE TITLE
New Courgette report not displaying test names but showing count

### ISSUE THREAD

**Issue by bill2605** [prashant-ramcharan/courgette-jvm#259]
Hi,

After updating to the latest library,  I am not seeing the test names in the cucumber report.

However, the `Cucumber.xml` will have the test names and info:
![image](https://user-images.githubusercontent.com/2414120/109044916-fc9e2680-76a0-11eb-8fb8-cded541bce4a.png)

Now if we look at the Report:
![image](https://user-images.githubusercontent.com/2414120/109044422-62d67980-76a0-11eb-945e-d20cdc1c6d7c.png)

I am also noticing from running the tests in IntelliJ IDE that no tests are listed and the build fails as follow:
![image](https://user-images.githubusercontent.com/2414120/109044547-8699bf80-76a0-11eb-9603-aa202da818a9.png)

Let me know if I need to provide further information
Thanks again lad!

**Comment by prashant-ramcharan** [comment]
Hi @bill2605 

Thanks for reporting. 

Does this happen all the time.. on every run?

Can you please provide the following:

- Your Courgette runner
- Your `courgetteTestRunner` task you have defined in your `build.gradle`
- Your `cucumber.json` . You should have this in your `build` directory.

**Comment by bill2605** [comment]
Here you go @prashant-ramcharan 

[cucumber.json.log](https://github.com/prashant-ramcharan/courgette-jvm/files/6038621/cucumber.json.log)

****had to change the name to .log for upload purposes

Runner in build.gradle:
![image](https://user-images.githubusercontent.com/2414120/109060438-6b847b00-76b3-11eb-9d07-336ba025bd23.png)

CourgetteRunner:
![image](https://user-images.githubusercontent.com/2414120/109060537-822ad200-76b3-11eb-93b8-5ace49f26a36.png)

**Comment by prashant-ramcharan** [comment]
The `feature name` is empty in the `cucumber.json` so this is why it's not showing in the Courgette report.

In your feature file, I assume you did not set the feature name? 

If you set the feature name in your feature file, you should see this populated in the Courgette report.

<img width="1110" alt="Screenshot 2021-02-24 at 20 22 09" src="https://user-images.githubusercontent.com/2563149/109061189-3e998d80-76de-11eb-931b-b4cc73c3da0d.png">

**Comment by prashant-ramcharan** [comment]
In the next release, I will add a check that if the `feature name` is empty, I will use the `feature uri` instead.

**Comment by bill2605** [comment]
...Wow... I don't know *how* I missed this.. Terribly sry for wasting your time.

I just ran it with the name added to my feature file and it works...

Curious question if I may,

I'm running with `Scenario` flag so shouldn't the table say `Scenarios` instead of `Features`?

**Comment by prashant-ramcharan** [comment]
Thanks for highlight this though, it's still good to have a fallback in the Courgette report when there is no feature name. I will add this in the next release.

> I'm running with Scenario flag so shouldn't the table say Scenarios instead of Features?

This was changed a few releases back. 

There were users that had hundreds of scenarios in a single feature file so grouping those scenarios under its `feature name` made it easier to identify and navigate in the Courgette report.

**Comment by bill2605** [comment]
That makes perfect sense! Thanks again for the speedy reply.
I'll close ticket!
