### ISSUE TITLE
Getting NoSuchMethodError Error message

### ISSUE THREAD

**Issue by adrianlob** [prashant-ramcharan/courgette-jvm#26]
Getting the below error when executing the gradle tasks

<img width="964" alt="screen shot 2018-02-05 at 4 17 08 pm" src="https://user-images.githubusercontent.com/29546772/35831638-0dbfbf30-0a90-11e8-840b-bb21b59c63d0.png">

I have the following structure:

<img width="289" alt="screen shot 2018-02-05 at 4 11 27 pm" src="https://user-images.githubusercontent.com/29546772/35831486-7b164b40-0a8f-11e8-92bc-058a65a6b90b.png">

And my runnerClass is like this

<img width="525" alt="screen shot 2018-02-05 at 4 14 19 pm" src="https://user-images.githubusercontent.com/29546772/35831575-cb9ed1e0-0a8f-11e8-84f2-e6e66de79df6.png">

Thanks

**Comment by prashant-ramcharan** [comment]
This is a Cucumber exception. Courgette-JVM loads cucumber features using the standard Cucumber library.

Can you run **test.feature** on its own, using the standard Cucumber runner or from IntelliJ -> right click -> Run feature?

**Comment by adrianlob** [comment]
Yes, I don't have any problem running the test manually. 

<img width="1025" alt="screen shot 2018-02-05 at 4 31 43 pm" src="https://user-images.githubusercontent.com/29546772/35832271-4c0b51bc-0a92-11e8-874a-0339a6c7fced.png">

**Comment by prashant-ramcharan** [comment]
Can you refresh you gradle project and try again?

 Failing that, please zip the project or share a github location so that I can verify.

I'm unable to reproduce this.

**Comment by prashant-ramcharan** [comment]
And looking at your runner, it’s does not allign with your project structure.

Glue should be “cucumber.steps”

Tags should contain the tag that’s present in test.feature unless you tagged your feature with “@regression”

**Comment by adrianlob** [comment]
I resolved it, the problem was that I had additional dependencies of cucumber in my build.gradle  I just removed them and it works great!

Thanks for your support

**Comment by cfsavant** [comment]
adrianlob what did you do? I have the same issue.
