### ISSUE TITLE
Extent Report - Spark vs V3

### ISSUE THREAD

**Issue by jiteshk11** [prashant-ramcharan/courgette-jvm#260]
Hi @prashant-ramcharan , 

Does courgette also support V3 version of extent reports?

Currently I am getting only spark extent report, I saw in your documentation you have pasted screen shot of V3. 

Please let me know, thanks!

**Comment by prashant-ramcharan** [comment]
Hi @jiteshk11 

This is no longer supported in Courgette because the `ExtentHtmlReporter` is deprecated.
