### ISSUE TITLE
Seeing java.lang.OutOfMemoryError at Arrays

### ISSUE THREAD

**Issue by jiteshk11** [prashant-ramcharan/courgette-jvm#261]
Hi @prashant-ramcharan, 

I am seeing below error when I run more than 100 tests. It happens when 50% tests are failed.  I don't see this error when there is around 10% of failure. 

Gradle suite > Gradle test > com.inspire.brands.test.runners.Inpsire_Runner > parallelRun FAILED
BUILD FAILED in 36m 59s
    java.lang.OutOfMemoryError at Arrays.java:3745

I have tried setting up jvm heap size: -Dcourgette.vmoptions="-Xms1024m -Xmx6144m" 

Please advise.

**Comment by prashant-ramcharan** [comment]
Hi @jiteshk11 

1. What version of Courgette are you using?
2. Do you capture screenshots when your tests fails?

The size of Cucumber html reports are larger in recent releases so storing these in memory would use up a lot JVM memory. 

My advice would be to use one of the options below:

- Increase the java heap of the **Gradle process** - NOT the Courgette process

  Add a `gradle.properties` file and add the following:
  ````
  org.gradle.jvmargs=-Xmx6g

  # if you can go higher than 6gb that would be better
  ````

- Disable the Cucumber html reporting in your Courgette runner.
  ````java
       disableHtmlReport = {HtmlReport.CUCUMBER_HTML}
  ````

- Disable the Cucumber and Courgette html reporting in your Courgette runner.
  ````java
     disableHtmlReport = {HtmlReport.CUCUMBER_HTML, HtmlReport.COURGETTE_HTML}
  ````

**Comment by jiteshk11** [comment]
@prashant-ramcharan  Thanks for reply!

I am using 5.9.2 version. 
Yes, screenshot capture is enabled, is there a way I am turn it off in Courgette?

I am trying your suggestion on increasing heapsize for gradle. 

Thanks!

**Comment by prashant-ramcharan** [comment]
> Yes, screenshot capture is enabled, is there a way I am turn it off in Courgette?

Courgette wouldn't capture screenshots. You will have to disable capturing screenshots in your test suite. 

Perhaps use a runtime property that you can pass to your tests to decide whether to capture screenshots or not.

**Comment by prashant-ramcharan** [comment]
Closing issue - please try the suggestions noted above. 

Allocating more memory when running a lot of tests should help work around the Out of memory issue.
