### ISSUE TITLE
Feature files are taking too much time to load

### ISSUE THREAD

**Issue by KannanPandi** [prashant-ramcharan/courgette-jvm#262]
Hi Ram,

Recently i have updated my project from maven to gradle with courgette jar's , whenever i tried to open Feature file ,its keeps on loading ,most of the time i have to close the eclipse and reopen again ..  i am facing this issue all the time ... 
Is there any solution for this issue??

**Comment by prashant-ramcharan** [comment]
Hello,

Courgette would not influence the speed of opening feature files. 

Courgette is only invoked when the tests are run, not before this.

Have you tried reinstalling eclipse and the Cucumber plugin?

**Comment by KannanPandi** [comment]
Thanks Ram
