### ISSUE TITLE
need a stable version for courgette 

### ISSUE THREAD

**Issue by KannanPandi** [prashant-ramcharan/courgette-jvm#264]
Hi Ram,

Recent days we are seeing lot of issues in courgette Jar , due to that we need to update/change our framework. we are looking for a stable version of courgette .. if there any old version we can refer as a stable one , pls let us know so that we can start using that one . if it continues we have to switch to some other plugin 

awaiting for your response

**Comment by prashant-ramcharan** [comment]
Hello,

Please elaborate with working examples of the issues you face?

Why do you think the current version is not stable?

To assist further, please provided reproducible examples of all the issues you have. 

**Simply stating a version is not stable is not sufficient.**
