### ISSUE TITLE
Is it possible to find the current rerun attempt number?

### ISSUE THREAD

**Issue by HesterLyonsMaru** [prashant-ramcharan/courgette-jvm#266]
Hi, 

Not so much an issue as a question from me. I'm trying to set up a way to send a notification to Slack when a scenario fails, but only on the last rerun to avoid spamming the channel. I don't know if this is possible though! Is there some way to find out what rerun attempt the current scenario is on?

I'm running v. 5.5.0 at the moment but can upgrade to a newer version.

**Comment by prashant-ramcharan** [comment]
Hello,

Thanks for the question.

Currently, there's no way to know what re-run attempt is being executed. 

I think a Courgette and Slack integration (via a Slack Webhook) would be a really nice feature to have. 

This will enable you to subscribe to different Courgette events (one of which could be a `LAST_RERUN` event) that would get posted to a slack channel as Courgette executes the tests.

**Comment by HesterLyonsMaru** [comment]
Yes, that would be lovely. I know there are a lot of more heavyweight reporting and dashboarding tools out there, but all I really want is a quick notification if something goes wrong - the courgette reports are there to look at for everyone (we're posting them on our sharepoint). 

I am using this library to do the slack notifications, it's incredibly easy to set up (I mean, even I managed, and I'm by no means a developer, this is a sideline for me): https://github.com/webcerebrium/java-slack-notification

For the moment I will write the run number of a failed scenario to a small text file I think, and just delete it on success or notification. It's not the most elegant but it'll work!

**Comment by prashant-ramcharan** [comment]
@HesterLyonsMaru You can now use Courgette version `5.10.0` which includes Slack integration.

https://github.com/prashant-ramcharan/courgette-jvm#slack-integration

To subscribe to tests that fail after the last re-run you can use the `CourgetteEvent.TEST_FAILED` event.

**Comment by HesterLyonsMaru** [comment]
Hi @prashant-ramcharan , that's amazing! Thank you, I will implement this as soon as possible.
