### ISSUE TITLE
Need to integrate live execution status getting updated in report portal

### ISSUE THREAD

**Issue by KannanPandi** [prashant-ramcharan/courgette-jvm#268]
Hi Ram,

we are using courgette plugin with report portal integration in our framework , as of now the test execution is getting updated in report portal once the execution is completed .
Is there a way to integrate the live execution status getting updated in report portal??
ex.. if the execution is going on in jenkins , then on each test case completion it should get updated in report portal .. in my previous company we used that way.. so is it possible to configure the same thing in this courgette plugin

**Comment by jiteshk11** [comment]
I am also looking for it. It would be great it we can achieve it.

**Comment by jiteshk11** [comment]
Also, currently Courgette is setting setting tags as attribute-values, can we have attribute-key setup as well?

**Comment by prashant-ramcharan** [comment]
Currently the Courgette report portal plugin has limited functionality. It uses the import functionality to publish results to report portal. 

I will need to investigate how much work is required to fully integrate with report portal.

**Comment by jiteshk11** [comment]
thanks @prashant-ramcharan

**Comment by prashant-ramcharan** [comment]
This is now released in Courgette version `5.11.0` 

Tests will be published to report portal in real time as tests execute.
