### ISSUE TITLE
Need to disable report portal integration for local execution

### ISSUE THREAD

**Issue by KannanPandi** [prashant-ramcharan/courgette-jvm#271]
Hi Ram,

Is there a way to disable report portal integration by giving any condition for local execution .. as we are executing our test cases in jenkins with report portal integration , in local execution we want to disable the report portal integration to avoid the unwanted updates in report portal

**Comment by prashant-ramcharan** [comment]
Hello,

There's no way to conditionally disable the plugin.

If you want to disable the report portal integration when running locally then you should use a separate runner when running locally.  

You could create a `CourgetteLocalRunner` without specifying the `reportportal plugin` in the runner.
