### ISSUE TITLE
Courgette reports in Microsoft Sharepoint show blank pages on drill-down

### ISSUE THREAD

**Issue by HesterLyonsMaru** [prashant-ramcharan/courgette-jvm#272]
Hi, 

This may be a very niche use of courgette, but I publish my reports to our Sharepoint so that everyone can have a look at them. There are some issues with their display on sharepoint though. The pie chart doesn't show, and when clicking on a failed scenario it shows an empty popup. When I open these reports from my local (synced) drive, they don't show this behaviour. 

Front page of report:
![image](https://user-images.githubusercontent.com/50143667/112295352-bcc06400-8c8b-11eb-80ff-138b7a105efa.png)

Click on failed scenario: 
![image](https://user-images.githubusercontent.com/50143667/112295640-ff823c00-8c8b-11eb-80a0-8b719eeb472f.png)

Thank you for looking into this :-)

**Comment by prashant-ramcharan** [comment]
Hello,

This would suggest your browser is unable to load the Javascript files. 

If you open the browser console, do you see any errors?

**Comment by HesterLyonsMaru** [comment]
Hi, there are a few samesite cookie errors, but I am wondering if this is relevant: 

![image](https://user-images.githubusercontent.com/50143667/112502670-2b7fe900-8d82-11eb-8f94-801f01623e04.png)

There's also this. I'm wondering if this is driven by security policies:

![image](https://user-images.githubusercontent.com/50143667/112503233-a812c780-8d82-11eb-894a-4bc54e302186.png)

And then quite a few of these:

![image](https://user-images.githubusercontent.com/50143667/112503554-ec05cc80-8d82-11eb-981e-585cfdc4e695.png)

**Comment by prashant-ramcharan** [comment]
What browser are you using and does the report open fine if you open it from a non sharepoint / synced folder?

You shouldn't see any console errors when opening the Courgette report.

**Comment by HesterLyonsMaru** [comment]
I was using Firefox. I have looked again on Chrome, and I think this is simply an issue with Sharepoint not allowing scripts at all. Everything opens fine if I use my local synced folder. Happy to close the issue. 
![image](https://user-images.githubusercontent.com/50143667/112510499-62a5c880-8d89-11eb-9550-d2977aa21bcd.png)
