### ISSUE TITLE
Separate JVM process per Feature file?

### ISSUE THREAD

**Issue by pagmoro** [prashant-ramcharan/courgette-jvm#276]
Hi Prashant,

I was looking at this old thread - https://github.com/prashant-ramcharan/courgette-jvm/issues/75 and was wondering if you still have the ability to run a separate JVM process per feature file? From the latest documentation it looks like you only support different threads.

Thank you

**Comment by prashant-ramcharan** [comment]
Hi @pagmoro 

Courgette has always created a **separate JVM process** for each feature / scenario and each JVM process will start a single thread.

Hope this helps.

**Comment by pagmoro** [comment]
That is great , so when we specify threads = 5 in Courgette options , it is
actually 5 different processes?

**Comment by prashant-ramcharan** [comment]
Yes, that's correct. 

Each "thread" defined in the Courgette runner would effectively create a separate JVM process.

**Comment by pagmoro** [comment]
Thank you - just to be clear - If we have 20 feature files , there would be
20 separate jvm processes in total (For Feature level option) , but at any
given time there would be 5 running in parallel.
As and when the process finishes , it would create new processes capped to
5 at a time?

Thanks

**Comment by prashant-ramcharan** [comment]
Yes, that's exactly right.

You'd only ever have `X` number of running processes at any one time. 

`X (JVM processes)` = `threads (value defined in your Courgette runner)`

If you have `20 feature files` and you set the `threads to 3` in your runner, only 3 processes would run at a time until all features are run.
