### ISSUE TITLE
classpath not working as expected 5.9.2

### ISSUE THREAD

**Issue by pagmoro** [prashant-ramcharan/courgette-jvm#277]
Hi,
 
    classPath = { "build/package/common/lib/*" , "build/resources/test" , "build/classes/java" }

(1) I am assuming above supports more than 2 paths?
(2) In my case , the libraries in the lib/* seem to be loaded and available , but anything in the second/third path - does not seem to work.

I am using a multi-module gradle project , with StepDef classes defined under gradle "test" sourceSet which go into "build/classes/java" but are not available in the jars in lib. If I move my classes from "test" to "main" , then the jar under lib now includes the StepDef classes (because test code doesn't get included in build jars)  and thus works , which indicates that it is not picking up classes from the second and third path. Any idea?

Thanks

**Comment by prashant-ramcharan** [comment]
Hello,

1. Yes, it supports more than [2 paths](https://github.com/prashant-ramcharan/courgette-jvm/blob/master/src/main/java/courgette/runtime/CourgetteFeatureRunner.java#L100)
2. Can you please provide an example project?

**Comment by prashant-ramcharan** [comment]
Closing inactive issue.
