### ISSUE TITLE
Rerunning Entire Feature file, not just failed scenarios

### ISSUE THREAD

**Issue by rockwig** [prashant-ramcharan/courgette-jvm#278]
Just recently upgraded to the latest release (5.11.0 from 3.3.0), and I'm seeing a changed behavior in the following configuration:

`runLevel = CourgetteRunLevel.FEATURE,
rerunFailedScenarios = true,`

Previously, if a test would fail in a feature file, once the thread was done, it would just rerun the failed test. Now it looks like it reruns ALL the tests in the feature file, regardless of if the test passed or failed.

**Comment by prashant-ramcharan** [comment]
This was changed a few releases back. 

`runLevel = CourgetteRunLevel.FEATURE, rerunFailedScenarios = true` caused the results of all `non failed` scenarios to be overwritten when there's a re-run.

This essentially means that we loose the results for all the `passed` scenarios in the Cucumber  and Courgette reports.

By re-running the entire feature, we retain the results for all scenarios in the feature. 

You could use `CourgetteRunLevel.SCENARIO` if you need to run failed scenarios only.

Hope this helps!

**Comment by rockwig** [comment]
You might want to clarify the documentation around the rerun logic stating something to the effect of it will rerun the feature or scenario that failed, depending on the run level.  

The issue that I have with running via 'SCENARIO' is that is seems the each scenario ends up being its own self contained instance. Meaning if I set something in a '@before' hook, it gets reset with EVERY scenario. When running via FEATURE, this reset only happens when it moves to the next feature file. I'm going to try moving things around to see if I can get the Scenarios to work for my needs. 

It's not a big deal when set to Features in my case, because I don't have many feature files, just that one of them is rather long.

**Comment by prashant-ramcharan** [comment]
Thanks - I've updated the documentation to clarify this.
