### ISSUE TITLE
Override some properties with environment variables 

### ISSUE THREAD

**Issue by alexsyd** [prashant-ramcharan/courgette-jvm#28]
We need to change how many VMs are started from Docker environment in our project. Also we need to control memory options of started VMS. I already made necessary changes here:
https://github.com/alexsyd/courgette-jvm/commit/4e945cfa56d9af43c07d7492bc21ef9675c6e650
could you please merge them in your project?

**Comment by prashant-ramcharan** [comment]
I've made a few comments to your PR.

Overriding the Courgette options was previously requested so I pushed these changes to version 1.5.0 which is now released.

Please refer to README for usage instructions.

**Comment by masar** [comment]
@prashant-ramcharan What about -Xmx -xms params? This is very useful thing.

**Comment by prashant-ramcharan** [comment]
@alexsyd @masar This is now released in version 1.5.1

````java
-Dcourgette.vmoptions="-Xms256m -Xmx512m"
````

**Comment by alexsyd** [comment]
Thanks a lot!
