### ISSUE TITLE
After adding courgette dependency and runner in Junit project , getting Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

### ISSUE THREAD

**Issue by poojaghosh47** [prashant-ramcharan/courgette-jvm#282]
Hi Prashant,

I am integrating courgette with junit project and trying to run with mvn command .

Before courgette integration i successfully ran test with mvn command. But not after courgette integration getting below snapshot 👍 

Running com.test.TestRunner
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@61dc03ce
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.004 sec

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

**Comment by prashant-ramcharan** [comment]
Hi @poojaghosh47 

It looks like you trying to run JUnit tests but your maven surefire plugin us configured to TestNG?

**Comment by poojaghosh47** [comment]
Hi Prashant,

i tried to add surefire plugin then and able to run feature , provided include path for test runner as well.

My test script is taking too much time to run even after 2 threads 
Could you please suggest what should i do?

It should take 50 minutes in single thread, now it took 3 hours even with two threads in jenkins and local

**Comment by prashant-ramcharan** [comment]
Hello,

Can you please share your `pom.xml` ?

**Comment by prashant-ramcharan** [comment]
Closing inactive issue.
