### ISSUE TITLE
Trouble with report-attacments

### ISSUE THREAD

**Issue by vgt1337** [prashant-ramcharan/courgette-jvm#283]
Good day, Prashant! Can you help me with add attachment in allure report right in failed step not in TearDown methods? 
![image](https://user-images.githubusercontent.com/54508354/123715144-5b0e2800-d880-11eb-9f38-4bab19740f5e.png)
You wrote "Each feature / scenario is run using the Cucumber CLI and because of this JUnit is not notified off the result whilst the tests are being executed." - is it fixed?

**Comment by prashant-ramcharan** [comment]
Hi @vgt1337 

Did you try using the `AfterStep` cucumber hook? 

You can add something like this:

````java
    @AfterStep
    public void afterStep(Scenario scenario) {
        if (scenario.isFailed()) {
            // take screenshot here
        }
    }
````

> You wrote "Each feature / scenario is run using the Cucumber CLI and because of this JUnit is not notified off the result whilst the tests are being executed." - is it fixed?

JUnit is currently notified of the result **after all** tests are run.

**Comment by vgt1337** [comment]
Yes, this way also added attachments in  TearDown method 
![image](https://user-images.githubusercontent.com/54508354/123863471-51dd9380-d932-11eb-8a69-ae04c6df4333.png)

**Comment by prashant-ramcharan** [comment]
You will have to embed the screenshot in the step definition although I **would not recommend** this approach.

````java
    @Given("step will fail sometimes")
    public void stepWithFailure() {

         if (scenario.isFailed()) {
            scenario.attach(...);
        }
    }
`````

It's unlikely you will know when a step will fail so it's best to capture the (failed) state of your application (i.e. image attachment) in a hook.

Courgette uses the [allure-cucumber6-jvm](https://github.com/allure-framework/allure-java/tree/master/allure-cucumber6-jvm) plugin so all allure report features are defined in this plugin.
