### ISSUE TITLE
Courgette Reports: For test runs with a lot of tests (several hundred), experiencing issues with test case modals loading after clicked on

### ISSUE THREAD

**Issue by chmccue** [prashant-ramcharan/courgette-jvm#286]
Courgette Reports: For test runs with a lot of tests (several hundred), clicking on a test case to view it seems to consistently encounter loading issues when opening the modal.

1. Run suite with several hundred tests to generate courgette report.
2. When viewing the courgette report, click on any scenario/test case to open the modal and view the step details.

Issue: I am consistently encountering an issue for some scenarios where the modal gets stuck in an endless loading state and doesn't appear, and I have to refresh the page to get away from the black tint that appears.

Details:
- Courgette Version: 5.9.1
- Running in parallel, usually up to 15 threads.
- Rerun scenario on fail: on

Let me know if I can provide any other details. Unfortunately I can't include a screen shot because I can't share the report details.

**Comment by chmccue** [comment]
Update: I also tried this with Courgette Version 5.11.0 (latest) and same issue was occurring for me. No errors found in Dev Tools > Console or Network tabs.

**Comment by prashant-ramcharan** [comment]
Hi @chmccue 

1. How many features and scenario are run?
2. On average, how long is each scenario (i.e number of steps) ?
3. Are you saving any screenshots in steps?
4. What is the size of the Courgette html file in MB ?

**Comment by chmccue** [comment]
Hi @prashant-ramcharan 

1. How many features and scenario are run?
Around 500.

2. On average, how long is each scenario (i.e number of steps) ?
This varies as the tests are very broad, but several scenarios have 10-20 steps, and some have even more depending on the e2e need.

3. Are you saving any screenshots in steps?
Yes a screen shot is saved only on failure during the teardown.

4. What is the size of the Courgette html file in MB ?
The ones I have checked with the issue are approximately 6-15MB in size, depending on the number of fails (which will have more screen shots). Also if I have higher rate of failure, then size will likely increase due to the inclusion of more screen shots.


Proposal for consideration: instead of having the scenario steps load in a modal, have them expand/collapse directly under the scenario title. Similar to how you have it structured for feature files to expand/collapse and display the scenario titles.

Feature file
|_ Scenario title
    |_ Scenario step details
|_ Scenario title
    |_ Scenario step details

**Comment by prashant-ramcharan** [comment]
Thanks for the info. 

I will consider moving the step details within the main table.

**Comment by prashant-ramcharan** [comment]
@chmccue

>  Unfortunately I can't include a screen shot because I can't share the report details.

Can you provide another Courgette html report (_one without sensitive information_) for me to debug further?

**Comment by prashant-ramcharan** [comment]
I ran 500+ scenarios with 100 failures including screenshots on failure and they open without any issue.

View report here: [Courgette Report - 500 Scenarios.zip](https://github.com/prashant-ramcharan/courgette-jvm/files/7023982/Courgette.Report.-.500.Scenarios.zip) (_36 mb unzipped_)

**Comment by chmccue** [comment]
Hi @prashant-ramcharan apologies on the late reply. Unfortunately I'm not able to share a report that has the modal loading behavior, as I am unable to remove the sensitive materials in them.

I looked at the one you shared to compare to my failing report and one noticeable difference is that your report runs rather quickly (under 20 minutes with 15 parallel threads) while my report takes significantly longer, around 2-3 hours with 10-15 parallel threads. So it may be due to the larger complexity of the tests I am running.

I'm looking into breaking up my test run into smaller test runs, which I think may alleviate the issue. Also the extent reports do load without error for these time consuming test runs, so I am able to use them as a backup when necessary.

Thank you so much for looking into this further, it is greatly appreciated.
