### ISSUE TITLE
Scenarios run in sequential manner

### ISSUE THREAD

**Issue by aravindkesavarapu** [prashant-ramcharan/courgette-jvm#287]
Hi @prashant-ramcharan,

Actually I have written almost 150 testcases for an web application. Some of test cases are dependent on other test cases. Some times the dependent test case executing prior than other(i have observed that these test cases are running in alphabetical order).

Is there any configuration to run scenarios in sequential manner?

**Comment by prashant-ramcharan** [comment]
Hi @aravindkesavarapu 

The short answer: No, there's no configuration to run scenarios in a sequential manner.

> Some of test cases are dependent on other test cases

This is usually an anti pattern and should be avoided. 

Also, if you choose to use `CourgetteRunLevel.SCENARIO` there would be no guarantee that the _dependant_ scenario gets run first.

If you choose to use `CourgetteRunLevel.FEATURE` then  you could be in a situation where:

Scenario 1: PASSES
Scenario 2 (_dependant on Scenario 1_):  FAILS
Scenario 3 (_dependant on Scenario 1_):  PASSES

If you have `rerunFailedScenarios` enabled then Scenario 2 will never be able to pass in it's own right.

You may be better off using a Cucumber runner to run features in sequence.
