### ISSUE TITLE
line break not added in courgette reports for scenario.log()

### ISSUE THREAD

**Issue by arkham02** [prashant-ramcharan/courgette-jvm#289]
if we use scenario.log("statement1") and scenario.log("statement2") in step definition:
in the courgette report its shown as statement1statement2

it should be
statement1
statement2

new line is not added. whereas the new line is maintained in other extent and cucumber-reports
![image](https://user-images.githubusercontent.com/46395565/130017782-22212e0d-e3aa-4ece-8d70-8534b74bfe4f.png)

**Comment by prashant-ramcharan** [comment]
Thanks, I will fix this issue.

**Comment by prashant-ramcharan** [comment]
@arkham02 This is now fixed in version `5.12.0`

**Comment by arkham02** [comment]
Thanks a ton !

**Comment by aravindkesavarapu** [comment]
Thanks @prashant-ramcharan 

I am using `<br>` tag to break the lines in courgette html report.


Now I will change the version of courgette

**Comment by aravindkesavarapu** [comment]
> @arkham02 This is now fixed in version `5.12.0`


Thanks @prashant-ramcharan

I am using `<br>` tag to break the lines in courgette html report.

Now I will change the version of courgette
