### ISSUE TITLE
No data send to ReportPortal

### ISSUE THREAD

**Issue by ansonliao** [prashant-ramcharan/courgette-jvm#291]
Hi Ram, 
I would like to send the testing data to the ReportPortal, the tests are completed, but no data send to the ReportPortal.
By the sam configuration of `reportportal.properties` in others projects can send the data to the ReportPortal.

The `reportportal.properties` is:
```properties
rp.endpoint = https://demo.reportportal.io

#rp.uuid = uuid_v4

rp.apitoken = uuid_v4

rp.project = ansonliao_personal

rp.launch = ansonliao_TEST_EXAMPLE
```

Could you help to advise how to solve the problem?

Thanks.

**Comment by prashant-ramcharan** [comment]
Hi @ansonliao 

Are you trying to send data to the **demo report portal server** or is it one of your own (_hosted_) report portal servers?

You should see error messages in the console. Try searching the console for `Courgette Report Portal Service`

**Comment by ansonliao** [comment]
Hi @prashant-ramcharan ,
I tried to bot of `demo report portal server` and my company's private report portal service (so I can't display it public).

Actually, the Intellij console has no error output with the `Courgette Report Portal Service`, that's my confusing issue, otherwise I can provide some error log here to check.

**Comment by prashant-ramcharan** [comment]
I assume you already have this in your Courgette runner and the spelling of `reportportal` is correct?

````java
@CourgetteOptions(
      ...  
      plugin = { "reportportal" },
      cucumberOptions = @CucumberOptions(
      // cucumber options here
      )
)
````

**Comment by prashant-ramcharan** [comment]
And the data is sent fine to your companies report portal server?

**Comment by ansonliao** [comment]
Hi @prashant-ramcharan 
1. My Courgette runner snippet as below, I added the report portal plugin to the `@CourgetteOptions`.
2. No data send to my company's private report portal service as well.

![image](https://user-images.githubusercontent.com/6060224/132565991-c37cf469-2255-4e34-87d4-65e619362a82.png)

**Comment by prashant-ramcharan** [comment]
@ansonliao Just tried on `https://demo.reportportal.io` and it worked.

<img width="1431" alt="Screenshot 2021-09-08 at 20 14 40" src="https://user-images.githubusercontent.com/2563149/132571149-12f5679d-43ba-4496-b602-586b72d4f2e4.png">

**Comment by prashant-ramcharan** [comment]
What version of Courgette are you using?

**Comment by ansonliao** [comment]
Hi @prashant-ramcharan 
My Courgette version is 5.12.0
`implementation('io.github.prashant-ramcharan:courgette-jvm:5.12.0')`

**Comment by prashant-ramcharan** [comment]
@ansonliao I suggest try adding your `reportportal.properties` to `src/test/resources`  in the example project: https://github.com/prashant-ramcharan/courgette-jvm-example

Please provide a Github link or project if you want me to look into this further for you.

**Comment by ansonliao** [comment]
Hi @prashant-ramcharan , I will update you when I upload my project to GitHub.
Thanks.

**Comment by ansonliao** [comment]
Hi @prashant-ramcharan 
I tried the code in another Mac machine without any code change (just udpated the reportportal.properties), it's working to send the data to the reportport (I am now using the https://demo.reporportal.io),
I will try the machine which keep out of work before and keep the update to you.
