### ISSUE TITLE
Unable to download courgette-jvm on gradle project

### ISSUE THREAD

**Issue by srilakshmishankar** [prashant-ramcharan/courgette-jvm#292]
`testCompile "io.github.prashant-ramcharan:courgette-jvm:5.12.0"`

This on a gradle project using JDK 11 is giving below error:

```
Could not find guice-5.0.1-no_aop.jar (com.google.inject:guice:5.0.1).
Searched in the following locations:
    https://repo.maven.apache.org/maven2/com/google/inject/guice/5.0.1/guice-5.0.1-no_aop.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

How can i get courgette-jvm to download.

More info:
I am trying to use this on a test framework built using serenity, spring, cucumber-java, junit. 

Also reported here:
https://stackoverflow.com/questions/69134571/courgette-jvm-not-able-to-download-on-jdk-11-project?noredirect=1#comment122242003_69134571

**Comment by prashant-ramcharan** [comment]
This is all you should need in your `build.gradle`

````gradle
repositories {
    mavenCentral()
}

dependencies {
    testCompile 'io.github.prashant-ramcharan:courgette-jvm:5.12.0'
}

````

**Comment by prashant-ramcharan** [comment]
You might have other issues with your `build.gradle` because Courgette does not include `com.google.inject:guice:5.0.1`  as per your error above.

Please refer to the Cougette with Gradle example project: https://github.com/prashant-ramcharan/courgette-jvm-example

**Comment by srilakshmishankar** [comment]
@prashant-ramcharan Thanks for reply. I get error from com.google.inject:guice:5.0.1 only when I try to install courgette-jvm. Is this compatible with serenity project? Mine is a serenity project.

**Comment by prashant-ramcharan** [comment]
> Is this compatible with serenity project? Mine is a serenity project.

No, Courgette is not compatible with Serenity.

See my comment here: https://github.com/prashant-ramcharan/courgette-jvm/issues/32#issuecomment-375096999
