### ISSUE TITLE
Report pass and fail trends

### ISSUE THREAD

**Issue by vasanths1** [prashant-ramcharan/courgette-jvm#293]
Hi,

Is there a way I can create a pass and failure trend report? This should include all the previous runs. I am using GCP to run the tests.

Thanks
Sobi

**Comment by prashant-ramcharan** [comment]
Hi,

You could use the `JUnit XML reports` for pass and failure trends by archiving the test report in your build pipeline for each run.  

This can be included in your Courgette runner using:

````java
cucumberOptions = @CucumberOptions( plugin =  "junit:cucumber.xml" )
````


 Unfortunately, Courgette does not persist report history to produce pass and failures trends.

**Comment by vasanths1** [comment]
This will be a good feature to have. Thank You and I will close this.
