### ISSUE TITLE
Test Runner issues

### ISSUE THREAD

**Issue by ugeshkadiyala** [prashant-ramcharan/courgette-jvm#295]
Hi,
Once I start the execution using Courgette test runner, I cant stop the test case in the middle of the run (Even if i click on stop it still continues to execute) and the other thing i cant see the scenarios which one is currently executing.

If there are steps for above two issues please let me know

Regards,
Ugesh Kadiyala

**Comment by prashant-ramcharan** [comment]
Hello,

Are you running the tests using Maven, Gradle or from the test runner within your IDE?

I assume you running from the IDE so in response to your questions..

1. The tests should stop running once the main JVM is killed (_i.e. once you stop the maven or gradle process_). It could be that you have orphaned JVM processes.

2. You will not be able to see the current scenario that is running in your IDE as tests are run in separate processes. You should still see the console output as tests are running in parallel and the final statuses of each tests when all tests are complete.

**Comment by prashant-ramcharan** [comment]
Closing issue - please reopen if required.
