### ISSUE TITLE
courgette ReportPortal plugin is used, Autoanalyze is not happening with logs added in the report portal. Any insights??

### ISSUE THREAD

**Issue by ssowmya85** [prashant-ramcharan/courgette-jvm#300]

**Comment by prashant-ramcharan** [comment]
1. What version of report portal server are you running?
2. Is auto analysis turned on in [settings](https://reportportal.io/docs/Auto-Analysis-of-launches%3Eswitch-on-off-automatic-analysis-)?
3. Have you manually analysed results to start with?  https://reportportal.io/docs/Auto-Analysis-of-launches%3Ecreate-an-analytical-base-in-the-elasticsearch
4. Have you tried removing and regenerating the elastic search index?

**Comment by prashant-ramcharan** [comment]
Closing inactive issue.
