### ISSUE TITLE
Courgette Reports (courgette-jvm Version 5.12.0 and 6.0.0): HTML formatting no longer being recognized when adding custom logging to report

### ISSUE THREAD

**Issue by chmccue** [prashant-ramcharan/courgette-jvm#301]
In courgette-jvm 5.12.0 and 6.0.0, the Courgette HTML reports are no longer recognizing custom log HTML formatting.

As of courgette-jvm 5.11.0, the HTML formatting was working as expected.

To reproduce:
use currentScenario.log to write directly to the HTML report.

`eg: currentScenario.log("this <br> should <br> be on separate <br> lines");`

 See screen shots.
<img width="789" alt="Screen Shot 2021-12-13 at 1 34 04 PM" src="https://user-images.githubusercontent.com/1563080/145893346-a13c1205-bf2f-4bf5-b254-d7a03147d770.png">
<img width="796" alt="Screen Shot 2021-12-13 at 1 07 19 PM" src="https://user-images.githubusercontent.com/1563080/145893366-fc713e36-a800-418f-8477-6b1364f03557.png">

**Comment by prashant-ramcharan** [comment]
Thanks, I will release a fix for this.

**Comment by prashant-ramcharan** [comment]
This is now fixed in Courgette `6.1.0`
