### ISSUE TITLE
Cucumber pico-container is not identified When Allure Reporting is eabled

### ISSUE THREAD

**Issue by MadhuQAAutomation** [prashant-ramcharan/courgette-jvm#304]
Hi Prashant -  I am tryin to generate Allure Report in my Gradle project using Courgette JVM. I have used cucumber pico-container for Test/Scenario Context. 
When I enable the Allure Report by configuring the plugin in Runner File and when I run the project from command line, I am getting the exception that it is unable to find the method :

![image](https://user-images.githubusercontent.com/93340435/147867707-7c697763-d3a6-41cc-9373-3534631da95f.png)

However when I remove the Allure Plugin configuration from the runner class, I am able to run the code without any exception.

Can you help?

**Comment by prashant-ramcharan** [comment]
Hi, can you share your `build.gradle` file?

**Comment by MadhuQAAutomation** [comment]
Hi- Issue is resolved. It was due  proxy because of which dependencies were not downloaded.
