### ISSUE TITLE
Request: Create slack event with test summary notification at the end of the run?

### ISSUE THREAD

**Issue by mateiQA** [prashant-ramcharan/courgette-jvm#307]
Is it possible to create an event that will post a summary to slack? If running a lot of tests, having each start/pass/fail/finished at an individual test level feels kind of 'spam'-ish

Example summary:
Test run finished: 1000 tests passed, 10 failed, 15 passed after re-run

More stuff could be added like start timestamp, finish timestamp, total time running, etc if this sounds interesting

Thanks @prashant-ramcharan for all the dedication and involvement!

**Comment by prashant-ramcharan** [comment]
Sounds sensible to me and a useful feature to have. 

I will create a `TEST_SUMMARY` Courgette Slack event.

**Comment by vsan6545** [comment]
Something similar we been also looking for our native apps.

**Comment by prashant-ramcharan** [comment]
This is now released in Courgette `6.3.0`

<img width="651" alt="Screenshot 2022-01-20 at 20 50 49" src="https://user-images.githubusercontent.com/2563149/150421269-c2eeb51f-e164-4699-9d0a-31c1ab705ebf.png">
