### ISSUE TITLE
cucumber report rewriting

### ISSUE THREAD

**Issue by DmitryMaretsky** [prashant-ramcharan/courgette-jvm#31]
Hi,
I want to use cucumber report, but courgette rewrite all cucumber reports by scenario or feature. Can i set to not rewrite it or it's impossible?
Why i want to use cucumber report? Because they have a screenshots and steps in report.

**Thanks for your answer**

**Comment by prashant-ramcharan** [comment]
Hi, I don't understand the question, what do you mean by cucumber report re-writing? 

If your runner has this plugin then the Cucumber report will be created once.

````java
 plugin = {
                        "pretty",
                        "json:target/cucumber-report/cucumber.json",
                        "html:target/cucumber-report/cucumber.html"}
````

Courgette-JVM report is separate from Cucumber report. 

By default, you will get the Courgette report and if you add the plugin above, the Cucumber report will be created as well (with steps and screenshots etc..)

**Comment by DmitryMaretsky** [comment]
About option: I have it, ty.

`what do you mean by cucumber report re-writing?`
For example: I want run 2 feature files. I run it. When the first feature file execute i can see it in report.js (cucumber-report) after that the second one will start to executing and report.js doesn't have a history about first feature file executing

**Comment by prashant-ramcharan** [comment]
The complete cucumber report is only generated after all features or scenerios are finish running. (i.e all threads are complete)

**Comment by DmitryMaretsky** [comment]
Hm, yesterday and at this morning there was no report. But now everything is ok. 
Sorry for that and thank you.
