### ISSUE TITLE
Running appium test thru courgette runner with mvn command doesn't display appium log 

### ISSUE THREAD

**Issue by vsan6545** [prashant-ramcharan/courgette-jvm#311]
**====== Running thru mvn command  WITH courgette runner (runner name is AndroidTestRunner) =====**

![Screen Shot 2022-02-04 at 10 31 50 PM](https://user-images.githubusercontent.com/96882739/152628746-7c3e279e-d7fe-4ba8-9556-234dde5e51a0.png)

**====== Running thru mvn command WITHOUT courgette runner (runner name is DebugRunner) =====**

![Screen Shot 2022-02-04 at 4 37 36 PM](https://user-images.githubusercontent.com/96882739/152628605-ef77c63e-125d-4c30-8849-ea6b7ecb7042.png)

**Comment by prashant-ramcharan** [comment]
Did you try?  

````java
mvn test -X
````
