### ISSUE TITLE
How to pass mobileDevice list along with mvn command

### ISSUE THREAD

**Issue by vsan6545** [prashant-ramcharan/courgette-jvm#312]
Hi @prashant-ramcharan How do you pass mobileDevice list using mvn command

I tried using this and it doesn't work

mvn clean test -X -Drunner.name=IOSTestRunner.java -DAndroidOrIOS="IOS" -DBuild="DEV" -Dcourgette.threads=1 -Dcucumber.tags="@LoginWithCustomerUser" **_-Dcourgette.mobileDevice={"Iphone 13 Max","Iphone 12 Max", "Iphone 11 Max"}_**

**Comment by prashant-ramcharan** [comment]
At the moment you can only define the mobile devices in the Courgette runner. 

I will make this configurable in the next release so that mobile devices can also be passed at runtime.

**Comment by vsan6545** [comment]
Thanks much @prashant-ramcharan , you Rock..

**Comment by prashant-ramcharan** [comment]
This is now released in Courgette `6.4.0`

https://github.com/prashant-ramcharan/courgette-jvm#pass-mobile-devices-at-runtime
