### ISSUE TITLE
Provision to make parallel testing - True/False

### ISSUE THREAD

**Issue by madhu29071984** [prashant-ramcharan/courgette-jvm#313]
Hi Prashant- I have been using courgette jvm in my project for couple of years. I know it's basically support parallel testing. Is there any option that this library can be used for sequential test execution as well.

**Comment by prashant-ramcharan** [comment]
Hi @madhu29071984 ,

Using `threads=1` and `CourgetteRunLevel.FEATURE` in your Courgette runner will run each feature sequentially.
