### ISSUE TITLE
ReportPortal Filters Not Working

### ISSUE THREAD

**Issue by jiteshk11** [prashant-ramcharan/courgette-jvm#314]
Hi @prashant-ramcharan , 

Thanks for pushing new changes for reportportal. It really help to see test results in more organized way (similar to what we have in feature/scenarios). 

However, I notice that filters stoped working for me. If I click on Passed , failed link for any launch it shows be below:

![image](https://user-images.githubusercontent.com/4682186/154712387-6371acf4-7205-4e4d-ba11-5d76d51ef54a.png)
![image](https://user-images.githubusercontent.com/4682186/154712722-d18b72ff-26d0-400b-ab32-caf1aaae0834.png)

However, filters were working fine before. 

I checked the filters created by reportportal in url, its same. Shouldn't there be new filters generated to accommodate your changes?
Please advise if I am missing any thing. 

Thanks,

**Comment by prashant-ramcharan** [comment]
Hi, I will investigate this further.

**Comment by jiteshk11** [comment]
Hi @prashant-ramcharan , Is there any update in this?
Thanks

**Comment by prashant-ramcharan** [comment]
Hi @jiteshk11 , 

Yes, I've found the cause of the issue and will release a fix.

**Comment by prashant-ramcharan** [comment]
This is now fixed in Courgette `6.4.0`

**Comment by jiteshk11** [comment]
Thanks @prashant-ramcharan . I will try it and let you know.

**Comment by jiteshk11** [comment]
Perfect, works fine. Thanks again @prashant-ramcharan
