### ISSUE TITLE
Unable to run the test runner from command line using Maven build tool

### ISSUE THREAD

**Issue by venkata-qe** [prashant-ramcharan/courgette-jvm#315]
OS:  MacOS
Maven home: 3.8.4/
Java version: 1.8.0_292, vendor: AdoptOpenJDK

Error
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project hsbc-selenium-restassured: No tests were executed!  (Set -DfailIfNoTests=false to ignore this error.) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project hsbc-selenium-restassured: No tests were executed!  (Set -DfailIfNoTests=false to ignore this error.)

**Comment by prashant-ramcharan** [comment]
Have you tried the example project? https://github.com/prashant-ramcharan/courgette-jvm-maven-example

To assist further, please provide more details about your current project setup or provide an example project for me to debug.

**Comment by prashant-ramcharan** [comment]
Closing issue - please refer to example project as a guide to setup your maven project.
