### ISSUE TITLE
Is it compatible with Serenity BDD?

### ISSUE THREAD

**Issue by ingjuanfg** [prashant-ramcharan/courgette-jvm#32]
Hi, what i want to do is run several scenarios of one feature at the same time (parallel) and with Courgette i can do that.

But i create my automated test with Serenity BDD framework. What i want to know is if COURGETTE and SERENITY are compatible. And that questions is because Courgette generate its own reports but i need the report of Serenity runing scenarios parallel.

I hope that you can help me. Thanks.

**Comment by prashant-ramcharan** [comment]
Hello,

Short answer is, no.

Courgette runner is extended from Cucumber, much like Serenity BDD runner **CucumberWithSerenity** extends Cucumber.

````java
@RunWith(CucumberWithSerenity.class)
````

When you use the CucumberWithSerenity test runner, you get the benefits of Serenity BDD reporting where as when you use the Courgette test runner, you get the benefits or parallelism and Cucumber reports.

There's no way for Courgette to aggregate the reports generated by Serenity BDD during parallel test execution.

_Note. I will be enriching the Courgette report in future, with test failures and screenshot etc.._
