### ISSUE TITLE
Passed Scenario count not changed after re-run scenario passed

### ISSUE THREAD

**Issue by SundarHubTest** [prashant-ramcharan/courgette-jvm#325]
Hi @prashant-ramcharan 

I have used the below config in runner.
        threads = 4,
        rerunAttempts = 2,
        runLevel = CourgetteRunLevel.SCENARIO,
        rerunFailedScenarios = true,

On successful execution, I have got a courgette-report/index.html as
Total Scenario: 27, Passed Scenario: 24, Failed Scenario: 3, Re-run Scenario: 3

But the reality is: 2 more test case got passed on re-run. so I was expected the report should show the below count:
Total Scenario: 27, Passed Scenario: 26, Failed Scenario: 1, Re-run Scenario: 3

can you please help me to resolve the above issue.

**Comment by prashant-ramcharan** [comment]
HI @SundarHubTest 

Can you please share the Cucumber and Courgette reports for me to investigate further?

**Comment by prashant-ramcharan** [comment]
Closing inactive issue
