### ISSUE TITLE
can we use courgette-jvm library to run rest assured api test in parallel 

### ISSUE THREAD

**Issue by LearningPur** [prashant-ramcharan/courgette-jvm#327]
Hi @prashant-ramcharan if you remember we are using your library for all out platform Web, Android and iOS automation and it works like a charm.

We want to integrate your library with our Rest Assured api test with parallel execution, is it possible ? 

Thanks

**Comment by prashant-ramcharan** [comment]
Hello,

Yes, you can! 

The general rule is that if your Cucumber tests can pass independently. _(i.e. theres not shard state / dependencies between tests_) then you will be able run the tests in parallel with Courgette.

**Comment by LearningPur** [comment]
Thanks @prashant-ramcharan I will give it a try and let you know. 

Thanks for capturing automation market for all platform not only Browser based but also Android, iOS apps and API test as well. 

Kudos to your all hard work and giving this awesome library to the community 

Appriciated
