### ISSUE TITLE
When the thread count is provided as 1 to run the cucumber tests sequentially, Corrupted STDOUT by directly writing to native stream in forked JVM 1 is displayed 

### ISSUE THREAD

**Issue by MadhuQAAutomation** [prashant-ramcharan/courgette-jvm#328]
@prashant-ramcharan - As suggested before, I tried to provide the thread count as 1 in the cucumber Runner class and executed my test in Maven. While running the tests through command line with mvn verify command, test is executed and passed, however the logs and other statements are not printed in the command window and a warning message is displayed as :
[WARNING] Corrupted STDOUT by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file C:\***\****\****\target\surefire-reports\2022-04-06T14-51-22_681-jvmRun1.dumpstream
**target\surefire-reports**
![image](https://user-images.githubusercontent.com/93340435/162010717-b96b7e8a-b61b-44c7-bcf9-295245f0aa34.png)
**Content of the dump file :**
![image](https://user-images.githubusercontent.com/93340435/162009110-7a4ab8bb-5de9-4045-a89c-79f483ef5fbd.png)

I tried with the below combinations to see if there is any issue with these dependencies. 

**Combinations :**

Maven Version : Maven 3.8.4
JAVA Version : 8, Junit : 4.12, 4.13, 5.8.2, Surefire : 3.0.0-M3,3.0.0-M5, 2.22.2, 3.0.0-M6(latest release)
JAVA Version : 11, Junit : 4.12, 4.13, Surefire : 3.0.0-M3,3.0.0-M5, 2.22.2, 3.0.0-M6(latest release)

However when I created a normal Test Runner file (not Courgette), and ran the test, it got executed.
![image](https://user-images.githubusercontent.com/93340435/162011733-44bcc5c4-5d7f-4061-ab91-ee5c83bf7908.png)

**Note :** 
This is happening only for Maven. I tried in gradle and there is no such issue observed. I was able to run the feature files sequentially by providing the thread =1 in the test runner file.

**Comment by MadhuQAAutomation** [comment]
But when i see the below JIRA, it has been fixed in Surefire 2.22.2 and 3.0.0-M3
https://issues.apache.org/jira/browse/SUREFIRE-1614

**Comment by prashant-ramcharan** [comment]
As this error is coming from the surefire plugin, please raise a separate issue in that project if required.

This error should would effect the way Courgette runs the tests.
