### ISSUE TITLE
Rerun report shows as all tests failed when they passed after rerun

### ISSUE THREAD

**Issue by sobi-ki** [prashant-ramcharan/courgette-jvm#329]
I had two scenarios and they both passed after rerun. The problem is with the report it shows that all the tests failed. 

I am using prashant-ramcharan:courgette-jvm 6.4.1 and I can confirm this was not the case with version 5.9.2

![image](https://user-images.githubusercontent.com/100700250/167804094-e1ca332e-5632-4986-a35e-32c6a80c6d57.png)

**Comment by prashant-ramcharan** [comment]
Thanks @sobi-ki  I'll take a look.

**Comment by prashant-ramcharan** [comment]
@sobi-ki This is now fixed in version `6.4.2`

**Comment by sobi-ki** [comment]
Thanks @prashant-ramcharan
