### ISSUE TITLE
No feature information in hooks

### ISSUE THREAD

**Issue by clicman** [prashant-ramcharan/courgette-jvm#33]
In classic cucumber runner, I can access current Feature object via Scenario instance in a @before hook.
With courgette the `Scenario.reporter` field is null
I want to get current feature name and its lang iso code at runtime. Is it possible to implement?

**Comment by prashant-ramcharan** [comment]
**Scenario.reporter** is a private field, so this value is not accessible anyway: [refer to Cucumber code here](https://github.com/cucumber/cucumber-jvm/blob/d59989766e8c55495de73e3ee454b6b5385aaa49/core/src/main/java/cucumber/runtime/ScenarioImpl.java#L19)

Are you using reflection to access this?

What you need to use is:

````java
    @Before
    public void before(Scenario scenario) {
        scenario.getName(); // This will print the scenario name

        scenario.getId(); // This will print the "feature name; scenario name; id"
    }
````

_Note: Courgette does not change any of Cucumber's source code_

**Comment by clicman** [comment]
Yes, I'm using reflection. There is the only way to access feature lang iso code.

**Comment by prashant-ramcharan** [comment]
Courgette re-creates its own runtime options for each feature / scenario so this is why Cucumber's runtime options (reporter) is null. We do not have access to the JUnit report when running in a multi-threaded session.

Why don't you write a custom library that reads the feature file and extract the ISO code? This can be put into an after hook?
````cucumber
# language: fr
````


If you need additional properties, then you can then use this:
 
````java
final String language = "fr";
 
final String isoCode = I18n.getAll().stream().map(I18n::getIsoCode).filter(dialect -> dialect.equalsIgnoreCase(language)).findFirst().orElseThrow(() -> new RuntimeException("Unable to find ISO code using this language"));
 
I18n.getAll().stream().filter(t -> t.getIsoCode().equalsIgnoreCase(isoCode)).findFirst().get();
````
 
This will give you access to this.
 
![screen shot 2018-03-29 at 13 57 20](https://user-images.githubusercontent.com/2563149/38090013-336376cc-3359-11e8-8d40-5da02ed29d1b.png)

**Comment by clicman** [comment]
Because I need to know language before scenario execution. 
As I can see it is possible to pass via system property to cli execution. Will you accept such PR?

Отправлено с iPhone

**Comment by prashant-ramcharan** [comment]
The CLI will only  **[List keywords for in a particular language](https://cucumber.io/docs/reference/jvm)** and **exit**. It will not tell you the ISO code for a feature file.

Passing  --i18n system property to Courgette or the Cucumber CLI will simply exit the JVM, it will not continue with any test execution.

Please look [here](https://github.com/cucumber/cucumber-jvm/blob/v1.2.5/core/src/main/java/cucumber/runtime/RuntimeOptions.java#L116-L118)

**Comment by clicman** [comment]
No. Just put it as system property passed to startup command

Отправлено с iPhone

**Comment by PrashantRiverIsland** [comment]
I understand what you mean now.

This functionality already exists. Courgette passes in all system properties to the CLI by default.

The important step is to import the system properties from the gradle task. Without this, the JVM will not be aware of the property.

````gradle
task runTest(type: Test) {
   systemProperties = System.getProperties() // this ensures all provided system props are available to the JVM

   include '**/CourgetteRunner.class'

   outputs.upToDateWhen { false }
}
````

````gradle
gradle runTest -Dname=foo
````
System.getProperty(“name”) will be available to Courgette which then passes it to the CLI.

**Comment by clicman** [comment]
Yes, but it isn't possible to determine which feature runs for the current scenario from outside. 
And the idea to pass it on cli command build.

**Comment by clicman** [comment]
@kosteman FYI

**Comment by prashant-ramcharan** [comment]
Courgette-JVM does not have it own CLI. 

You cannot use this from the command line like you would do with Cucumber. This does not exist!

Courgette simply uses Cucumber CLI. So whatever system property you provide to Courgette at runtime is passed to Cucumber CLI.

There’s no way around this, unfortunately.

**Comment by clicman** [comment]
Could I try to implement it and send you PR?

**Comment by prashant-ramcharan** [comment]
Sure

**Comment by prashant-ramcharan** [comment]
But just passing a system property as you previously described already exists by default and it’s not the solution to your issue.

**Comment by prashant-ramcharan** [comment]
Please write a test as well. Thanks

**Comment by clicman** [comment]
https://github.com/prashant-ramcharan/courgette-jvm/pull/35

**Comment by clicman** [comment]
Thank you for example, but filename limitation doesn't satisfy our requirements. So I'll think more about it.

**Comment by prashant-ramcharan** [comment]
Ok sure 👍 

If we explicitly set **custom system properties** from Courgette then we be this enforcing rules to all users.

By that I mean, if I were to specify -DfeatureName or -DfeatureIsoCode with a value of my own, then Courgette will ignore my value and use the one specified in the library.

At present, Courgette only accepts **user provided system properties.** It does not, and should not set its own custom system properties from within the library.

I'll close this issue for now.

**Comment by PrashantRiverIsland** [comment]
Hi @clicman 

I've upgraded Courgette-JVM to 2.0.0. 

This now uses Cucumber-JVM 2.4.0 and Gherkin 5. With this, the scenario object is updated.

So you can get the feature info using Gherkin including the **language**

````java
    private Feature getFeature(Scenario scenario) throws FileNotFoundException {
        Parser<GherkinDocument> parser = new Parser<>(new AstBuilder());

        TokenMatcher matcher = new TokenMatcher();

        return parser.parse(new FileReader(scenario.getUri()), matcher).getFeature();
    }
````

**Comment by prashant-ramcharan** [comment]
Hi @clicman 

I've upgraded Courgette-JVM to 2.0.0. 

This now uses Cucumber-JVM 2.4.0 and Gherkin 5. With this, the scenario object is updated.

So you can get the feature info using Gherkin including the **language**

````java
    private Feature getFeature(Scenario scenario) throws FileNotFoundException {
        Parser<GherkinDocument> parser = new Parser<>(new AstBuilder());

        TokenMatcher matcher = new TokenMatcher();

        return parser.parse(new FileReader(scenario.getUri()), matcher).getFeature();
    }
````

**Comment by clicman** [comment]
great! Thank you!
Better approach to access feature is like in: https://github.com/sbtqa/qa-utils/blob/master/src/main/java/ru/sbtqa/tag/qautils/cucumber/CucumberUtils.java
