### ISSUE TITLE
Getting "The filename or extension is too long" error in Azure CMD.

### ISSUE THREAD

**Issue by bhaskarJhaPS** [prashant-ramcharan/courgette-jvm#338]
I followed the instructions given in [https://github.com/prashant-ramcharan/courgette-jvm-classpath-example](url). It is working fine in my local machine. But It is still failing in Azure CMD with error **java.io.IOException: Cannot run program "java": CreateProcess error=206, The filename or extension is too long
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048).**

The yaml that I am using is:
<img width="402" alt="yamlFile" src="https://user-images.githubusercontent.com/107022008/176416047-f4d6ded8-e6d8-4a32-9df4-a5dc380736a1.PNG">

The runner file that I am using is: 
<img width="542" alt="runnerFile" src="https://user-images.githubusercontent.com/107022008/176416093-b9f9db61-99c2-461f-afac-86a12f55e0f0.PNG">

The error that I am getting is:  
<img width="704" alt="CLI_error" src="https://user-images.githubusercontent.com/107022008/176416155-70faea25-dd6b-4123-942d-f97e4e1aa3cb.PNG">

Any suggestions?

**Comment by prashant-ramcharan** [comment]
I'm not sure tbh. 

Can you try manually overriding the Java classpath system property?

````mvn
mvn verify -Djava.class.path=
````

_Courgette will use the custom classpath anyway so you can this value is ignored /  removed_

**Comment by bhaskarJhaPS** [comment]
I tried the above suggestion. But the issue still persists.

**Comment by sobi-ki** [comment]
@bhaskarJhaPS 
please try adding the following. This is only if you are running on a Windows-based machine


<dependency>
    <groupId>gradle.plugin.ua.eshepelyuk</groupId>
    <artifactId>ManifestClasspath</artifactId>
    <version>1.0.0</version>
</dependency>

**Comment by bhaskarJhaPS** [comment]
@sobi-ki I couldn't able to find the maven plugin for the same.

**Comment by prashant-ramcharan** [comment]
@bhaskarJhaPS Did you try any running other projects (_that uses Courgette and the classPath option_) to see if it runs successfully on Azure CMD ?

**Comment by sobi-ki** [comment]
Hi @bhaskarJhaPS here is the plugin 

<dependency>
    <groupId>gradle.plugin.ua.eshepelyuk</groupId>
    <artifactId>ManifestClasspath</artifactId>
    <version>1.0.0</version>
</dependency>

**Comment by sobi-ki** [comment]
@bhaskarJhaPS Maven plugin 

`
<dependency>
    <groupId>gradle.plugin.ua.eshepelyuk</groupId>
    <artifactId>ManifestClasspath</artifactId>
    <version>1.0.0</version>
</dependency>
`

**Comment by prashant-ramcharan** [comment]
Closing issue. Please re-open if there are any new updates.
