### ISSUE TITLE
Is there a way to retrieve the new test log filename?

### ISSUE THREAD

**Issue by mateiQA** [prashant-ramcharan/courgette-jvm#339]
I noticed that you can now set testOutput to file which will generate a .log file inside the report folder, is there any way I can retrieve that filename/content of the log so that I can attach it to the allure report in the hook in case the test passed/failed?
I see that the filename method is private

Something like the method below which is private
```
private String testOutputFilename(String prefix) {
            return prefix +
                    Arrays.stream(runnerArgs.get(null).get(0).split(File.separator)).reduce((x, y) -> y)
                            .get()
                            .replace(".feature", "")
                            .replace(":", "_line_")
                    + "_" + courgetteProperties.getSessionId() + ".log";
        }
```

**Comment by prashant-ramcharan** [comment]
No, you wont be able to access the Courgette `testOutputFilename`(_even if made public_)  from any Cucumber hook. 

You could get the feature file name from the `Scenario` object within the Cucumber hook and then traverse the `test-output` directory to find your matching filename (using regex perhaps?).

**Comment by prashant-ramcharan** [comment]
Courgette uses a `ProcessBuilder` that only allows one instance of a `redirect` for subprocess output. 

The redirected output can be `console` **or** `file` but not both.
