### ISSUE TITLE
Gradle not running tests

### ISSUE THREAD

**Issue by DzmitryIlyin** [prashant-ramcharan/courgette-jvm#340]
Hi,
I'm trying to attach courgette to existing test framework, it's gradle based, project is multi-module with following structure

--Module A
-----main
---build.gradle
--Module B
-----main
------testng
-------FeatureSuite
---build.gradle
-build.gradle

I've tried to follow example from https://github.com/prashant-ramcharan/courgette-jvm-example/blob/master/build.gradle

task runFeaturesUsingTestNG(type: Test) {
    useTestNG()
    include '**/testng/FeatureSuite.class'
    outputs.upToDateWhen { false }
}

but when I'm running that task gradle is not not running any tests. Also tried to update classpath with
classpath = sourceSets.main.output + sourceSets.main.runtimeClasspath
and still no luck.

Should I update anything else or what am i missing, could you help with that ?

**Comment by prashant-ramcharan** [comment]
Hi,

In the **root level** `build.gradle` you could apply the project dependancies to all sub projects

````gradle
subprojects {
    apply plugin: 'java'

    dependencies {
        testImplementation 'io.github.prashant-ramcharan:courgette-jvm:6.5.1'
       // all other deps here
    }
}
````

In **Module B** add the `runFeaturesUsingTestNG` task
````gradle
repositories {
    mavenCentral()
}

task runFeaturesUsingTestNG(type: Test) {
  useTestNG()
  include '**/testng/FeatureSuite.class'
  outputs.upToDateWhen { false }
}
`````

Then in the root level of the project,  you can run the tests in `ModuleB` by specifying the module and task name like:

````gradle
./gradlew moduleb:runScenariosUsingTestNG
````

**Comment by DzmitryIlyin** [comment]
@prashant-ramcharan thanks for the reply! I've tried your option and unfortunately it didn' worked. But i've found a fix, issue is that my FeatureSuite is not in /test package but in /main, so I've just added this in build.gradle where runFeaturesUsingTestNG task defined:

`sourceSets {
    main {
        java {
            srcDirs = ['src/main/java']
        }
    }
    test {
        java {
            srcDirs = ["src/main/java"]
            include '**/*CIRunner.java'
        }
    }
}`
