### ISSUE TITLE
Integrate paralell execution with appium 

### ISSUE THREAD

**Issue by jairomendezonetec** [prashant-ramcharan/courgette-jvm#345]
hi, 

I am trying to integrate CourgettePlugin.MOBILE_DEVICE_ALLOCATOR, but i don't understand how i can do it. 

I am using the latest version. 

Where do I have to create a pool of devices based on mobileDevice (UDID, name...)?

And by the other hand, when I include mobileDevice in my runner, this word is in red and it is not recognized.
![image](https://user-images.githubusercontent.com/46560990/183083893-a15f97dc-83f4-4c76-8ca8-7975a4ee971d.png)

Can you help me? 

Thanks!

**Comment by prashant-ramcharan** [comment]
Hi @jairomendezonetec 

It appears that you are using an older Courgette version, please confirm what version you are using?

Looking at your runner, `showTestOutput = true` is deprecated in the latest version which suggests you using an older version.

**Comment by prashant-ramcharan** [comment]
Please refer to the example projects as a reference: 

https://github.com/prashant-ramcharan/courgette-jvm-appium-ios

https://github.com/prashant-ramcharan/courgette-jvm-appium-android

**Comment by jairomendezonetec** [comment]
Exactly, I put de latest version, and the errors disappear. 

Another question, Where are the devices configured (UDID, device name, port..) ? I can see the devices in the runner, but no the information about them

Thanks a lot
