### ISSUE TITLE
Report only show the latest feature

### ISSUE THREAD

**Issue by jairomendezonetec** [prashant-ramcharan/courgette-jvm#347]
Good morning, 

I am having problems with the cucumber report. 

When I execute some differents features, the final cucumber report only contains the latest feature, 

I have the version 6.5.1

Thanks a lot

**Comment by prashant-ramcharan** [comment]
Hi,

Can you please provide more information?

1. How many tests are you expecting to see in the report?
2. Do you get the same result when running Cucumber directly?
3. Does the Courgette report show more than one feature?
4. Can you provide the Cucumber `json`  and `html` reports (if possible) ?
5. Is this repeatable and do you get the same result when using the Courgette example project ?  https://github.com/prashant-ramcharan/courgette-jvm-example

**Comment by prashant-ramcharan** [comment]
Hi,

Looking at the console logs, I can see that Courgette was not able to create the Cucumber reports.

````
[Courgette Runner] There was an unexpected error processing the individual Cucumber report files and Courgette was unable to create any reports for this test run.
````

This usually happens when you have an issues with your tests / setup etc..  

Can you ensure that all your tests pass and that there are no errors to see if Courgette is able to create the Cucumber reports?

**Comment by jairomendezonetec** [comment]
This is another example, where both test are passing, 

![image](https://user-images.githubusercontent.com/46560990/183854060-168353b7-666a-4ede-b8d8-9635b31064dd.png)

Runner is this: 
![image](https://user-images.githubusercontent.com/46560990/183854212-73b613b0-85bc-405a-8b0f-de567a7906d0.png)

**Comment by jairomendezonetec** [comment]
In the version 5.11.0, with the same tests, i can see the report correctly, and the report is published also

**Comment by prashant-ramcharan** [comment]
Yes this is because all tests passed!

**Comment by jairomendezonetec** [comment]
But before with version 5.11.0, Courguette generated always reports.

**Comment by prashant-ramcharan** [comment]
Please provide a project so that I can reproduce this?

**Comment by prashant-ramcharan** [comment]
No problem @jairomendezonetec 👍  Glad its working!
