### ISSUE TITLE
Update Lombok of transitive dependency

### ISSUE THREAD

**Issue by unexist** [prashant-ramcharan/courgette-jvm#348]
Hey,

can you please consider overriding Lombok of your dependency com.aventstack:extentreports?

There are issues with Lombok <1.18.20 and [JEP396](https://openjdk.org/jeps/396) and the latest version of extentreports still relies on 1.18.12. (https://github.com/extent-framework/extentreports-java/issues/360)

I am not a Gradle user and I wonder why this doesn't compile for me, otherwise I'd send a PR:

https://github.com/prashant-ramcharan/courgette-jvm/compare/master...unexist:courgette-jvm:master

A working Maven version inside of my project can be found here:

https://github.com/unexist/showcase-acceptance-testing-quarkus/commit/74f657f1dd03e27e6c371b7c87c8a8fba817abdc

**Comment by prashant-ramcharan** [comment]
Hello,

As Lombok is not a direct dependency on Courgette my preference would be to wait for Extent Reports to upgrade its Lombok dependency.  I will then upgrade the Extent Reports dependency within Courgette.

I think using your current work around of excluding the transitive dependency for Extent Reports might be the best for the time being.

**Comment by unexist** [comment]
Hey,

thanks for looking into this and understandable. (y) 

I am using the override for Lombok in my project anyway, just wanted to avoid other people stumbling upon this.
