### ISSUE TITLE
Courgette Hooks

### ISSUE THREAD

**Issue by MadhuQAAutomation** [prashant-ramcharan/courgette-jvm#349]
Hi Prashant -  I am using Courgette Test Runner for executing our project in parallel. We have have set of feature files(environment setup related) that are to be executed before any of the other feature files/actual test begin in parallel. Is this achievable using courgette  Hooks?

**Comment by prashant-ramcharan** [comment]
Hello,

Yes, you can run setup code using Courgette hooks but you cannot run a `Cucumber feature file` within a Courgette hook.

You need to call the Java code that does the environment setup in a Courgette hook.

**Comment by MadhuQAAutomation** [comment]
Ok. Thank you!
