### ISSUE TITLE
CourgetteRunInfo missing inside @CourgetteAfterAll

### ISSUE THREAD

**Issue by kamil1014** [prashant-ramcharan/courgette-jvm#352]
Hi, 

I want to read some stats about tests after execution and in doc there is CourgetteRunInfo class to do that.
But inside my project this class is missing i have only CourgetteRunnerInfo which does not have static methods or fields.
I use latest version

Thanks!

**Comment by prashant-ramcharan** [comment]
Hi,

If you navigate (click) the `CourgetteRunnerInfo` class from your IDE what methods do you see in this class?

**Comment by kamil1014** [comment]
Thanks, it was IntelliJ problem with importing new version. Now it works as expected!
