### ISSUE TITLE
Scenario Outline have same name in the xml report (with not identifiers)

### ISSUE THREAD

**Issue by albertolopez55** [prashant-ramcharan/courgette-jvm#353]
Hello Ramcharan
Using the CLI (With no courgette), when i execute an Scenario Outline (with multiple data), in the XML report, the scenario name are shown like this
Scenario Test 1
Scenario Test 2
Scenario Test 3

Using Courgette, the scenarios are displayed in the XML only like this:
Scenario Test
Scenario Test
Scenario Test

This is causing that we have different numbers displayed in Bamboo. Because the Courgette Report and the HTML report do count the executions of the Scenarios Oulines. In the example i gave you, the reports count "3"
But bamboo, when reads the XML, they only count "1" because it does not count the repeat scenarios (same name). 
Do you think is feasible to include the number of the iteration of the scenario outline? like this:
Scenario Test 1
Scenario Test 2
Scenario Test 3

Tks

**Comment by prashant-ramcharan** [comment]
Hi, I should be able to include the iteration in the xml report. I will add this to the next release.

**Comment by albertolopez55** [comment]
Tks for your support!

**Comment by prashant-ramcharan** [comment]
This is now released in Courgette `6.7.0`
