### ISSUE TITLE
Change Courgette html report to include count of scenarios when using feature run level

### ISSUE THREAD

**Issue by Kannan0893** [prashant-ramcharan/courgette-jvm#355]
Hello ,

we have around 2000+ automated UI test cases, when we tried to run with multiple threads, then we are seeing logout failures 
in same feature if we trigger with multiple thread then we are seeing logout failures , we tried with scenario level
is there a way to avoid this logout failure when we are running in multiple treads ? is there way to organize the threads to avoid this logout failures ?
 
if we try with feature level ,then we are getting report as feature level count . ex. we have 2000 test cases with 10 features . then the feature level report giving count as 10 .. Is there a way to change the report alone for the total test case count even if we execute with feature level ??

please suggest us some solution for this issue 

Thanks,
Kannan P

**Comment by prashant-ramcharan** [comment]
Hello,

Using `CourgetteRunLevel.SCENARIO` means you have to write loosely coupled tests where each scenario / test can pass independently of any other scenario / test.  This is best practice and should be followed whenever possible.

As your tests depend on application state (_the user must be logged in / out etc_), using `CourgetteRunLevel.SCENARIO` will never work, so using `CourgetteRunLevel.FEATURE` would be your only option as you figured out.

I think updating the report makes sense and having a `Total count of executed tests` is better than just counting the number of `features`. This will also make it consistent between feature level and scenario level reports.

I will update the Courgette html report.

**Comment by Kannan0893** [comment]
Thanks for the quick response @prashant-ramcharan .. please let me know if you found any work around or changes will support our use case 

Thanks,
Kannan P

**Comment by Kannan0893** [comment]
Hi @prashant-ramcharan ..did u get a chance to check on this ?

**Comment by prashant-ramcharan** [comment]
Hi @Kannan0893 , unfortunately I've not had much time to progress on this.

**Comment by prashant-ramcharan** [comment]
@Kannan0893 this change is now released in Courgette `6.9.1`

**Comment by Kannan0893** [comment]
Thanks a lot @prashant-ramcharan ... let me execute the test cases and get back to you if we have any concerns
