### ISSUE TITLE
Wiremock and Courgette - Report not getting generated

### ISSUE THREAD

**Issue by SundarHubTest** [prashant-ramcharan/courgette-jvm#357]
Hi Prashant,
In need of your help to resolve below two issues:
1. Do i have any option to run a step after the feature instead of scenario.
2. Courgette report is not getting genarted ( even on successfull execution ) due to error "[Courgette Runner] There was an unexpected error processing the individual Cucumber report files and Courgette was unable to create any reports for this test run." When i have the pom.xml with below dependencies :

> <dependency>
            <groupId>com.github.tomakehurst</groupId>
            <artifactId>wiremock</artifactId>
            <version>2.27.2</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.httpcomponents.client5</groupId>
                    <artifactId>httpclient5</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by prashant-ramcharan** [comment]
Hello,

You need the `jackson` dependency. Trying adding this to your `pom.xml`

````
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.13.3</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.13.3</version>
        </dependency>
````

**Comment by SundarHubTest** [comment]
Added the above depedency and still facing same issue. 
When i execute the test I noticed the below 
![image](https://user-images.githubusercontent.com/96912101/198473448-701ca80b-53e5-4f22-9ff9-22cb75c3b859.png)
when test execution is getting complete, the "courgette-report" folder is become blank.
![image](https://user-images.githubusercontent.com/96912101/198473985-1a204295-6bf7-4e2c-8242-7d8dfd8e2c94.png)

**Comment by prashant-ramcharan** [comment]
Can you run `mvn dependency:tree` and provide the output?

From the `External Libraries` menu in your IDE, expand the `Courgette` library and expand `courgette -> runtime -> utils`

If you look at the class `JacksonUtils` and see any issues with this class such as missing deps (_code in red_) then this would suggest you missing the Jackson dependency.

**Comment by SundarHubTest** [comment]
Yes, after I updated my pom as below. I able to see report get generated successfully. I hope the issue might have occured due to version incompatability between wiremock and courgette jackson. Thank you
> <dependency>
            <groupId>com.github.tomakehurst</groupId>
            <artifactId>wiremock</artifactId>
            <version>2.27.2</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-databind</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-annotations</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.httpcomponents.client5</groupId>
                    <artifactId>httpclient5</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
  <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.13.3</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.13.3</version>
        </dependency>
