### ISSUE TITLE
Scenarios within feature files are being run twice when running features in parallel

### ISSUE THREAD

**Issue by niagara1983** [prashant-ramcharan/courgette-jvm#36]
Hi, I need help understanding what I am doing wrong with my setup. 
So I have 2 feature files. Each file contains 1 scenario. When I try to run the features in parallel (using 2 threads), first 2 browsers that opened up run the scenario in feature 1 (twice) followed by scenario 1 in feature 2. So basically the scenarios are executed 4 times. 

attached is my build.gradle
[build.gradle.zip](https://github.com/prashant-ramcharan/courgette-jvm/files/1862450/build.gradle.zip)

here is  Feature suite
` 
import courgette.api.CourgetteOptions;
import courgette.api.CourgetteRunLevel;
import courgette.api.junit.Courgette;
import cucumber.api.CucumberOptions;
import org.junit.runner.RunWith;

@RunWith(Courgette.class)
@CourgetteOptions(
        threads = 2,
        runLevel = CourgetteRunLevel.FEATURE,
//        rerunFailedScenarios = true,
        showTestOutput = true,
        cucumberOptions = @CucumberOptions(
                features = "src/cucumber/resources/features/reporting",
                glue = "src/cucumber/resources",
                tags = {"@regression"},
                plugin = {
                        "pretty",
                        "json:target/cucumber-report/cucumber.json",
                        "html:target/cucumber-report/cucumber.html"},
                strict = true
        ))
public class FeatureSuite {
}
`

**Comment by prashant-ramcharan** [comment]
Hi,

I've updated your build.gradle file: [build-updated.gradle.zip](https://github.com/prashant-ramcharan/courgette-jvm/files/1863305/build-updated.gradle.zip)

**Issues**
1. Remove all references to "**info.cukes:cucumber-core:1.2.5**". Courgette already provides these dependencies.


2.  This line needs to be **removed**
_Refer to the [README](https://github.com/prashant-ramcharan/courgette-jvm/blob/master/README.md) thats shows you how to provide cucumber options at runtime_

````gradle
"cucumber.options"   : System.getProperty("cucumber.options")
````

3. Your "glue" in your test runner is not correct. This must to be a **package name** and not a folder path.
````java
glue = "src/cucumber/resources",

// should refer to a package name containing your Cucumber step defs
glue = "com.yourcompany.cucumber.steps,
````
Take a look at [Courgette-JVM Example](https://github.com/prashant-ramcharan/courgette-jvm-example)

**Comment by prashant-ramcharan** [comment]
On a separate note, take a look at [WebDriver Binary Downloader](https://github.com/prashant-ramcharan/webdriver-binary-downloader) to manage your driver binaries instead of handling them in your build.gradle.

Just a suggestion 👍

**Comment by niagara1983** [comment]
Hi prashant-ramcharan ,
I applied your changes - see attached screenshot, now I am getting this 
`
> Task :runFeatures
Exception in thread "main" java.lang.IllegalArgumentException: Not a file or directory: /XXX/XXXX/Automation/cucumber/ui-automation/steps
        at cucumber.runtime.io.FileResourceIterator$FileIterator.<init>(FileResourceIterator.java:54)
        at cucumber.runtime.io.FileResourceIterator.<init>(FileResourceIterator.java:20)
        at cucumber.runtime.io.FileResourceIterable.iterator(FileResourceIterable.java:19)
        at cucumber.runtime.groovy.GroovyBackend.loadGlue(GroovyBackend.java:69)
        at cucumber.runtime.Runtime.<init>(Runtime.java:92)
        at cucumber.runtime.Runtime.<init>(Runtime.java:70)
        at cucumber.runtime.Runtime.<init>(Runtime.java:66)
        at cucumber.api.cli.Main.run(Main.java:35)
`

See attached file for the project structure and the changes i made in the runner (based on your suggestion). I am not sure why it is expecting the step definition folder to be in the root folder. 
<img width="1364" alt="screen shot 2018-03-30 at 12 03 21 pm" src="https://user-images.githubusercontent.com/8509354/38142498-ebc43454-3412-11e8-95fb-13e6ff0cb645.png">

By the way, I will definitely look into using WebDriver Binary Downloader  :-) 
Thanks a lot for your help on this.

**Comment by prashant-ramcharan** [comment]
Ah, you using groovy backend. 

So change the glue back to using a PATH

In your case: **src/test/java/steps**

**Comment by niagara1983** [comment]
I am back with my original issue where each scenario is being executed twice :-(

**Comment by prashant-ramcharan** [comment]
Please share your project (on Github preferably) for me to take a look.

**Comment by niagara1983** [comment]
I implemented [Courgette-JVM Example](https://github.com/prashant-ramcharan/courgette-jvm-example) using geb + cucumberJVM, please see https://github.com/niagara1983/ui-automation

**Comment by prashant-ramcharan** [comment]
I took a look and there was an issue with your **project structure**. Courgette was running the tests and Cucumber groovy was running the tests.

I fixed the project structure for you [here](https://github.com/niagara1983/ui-automation/pull/1)

This should be working as expected now.

**Comment by niagara1983** [comment]
Thanks a lot  prashant-ramcharan! the example  is working. I had to make a minor change to the feature runner to include env.groovy path in the glue to get it working with my project. So it looks like this `glue = {"src/test/groovy/steps", "src/test/groovy/env/env.groovy"},`. Thanks for your help on this. Maybe you could reference the example project I made for this in case someone using geb runs into a similar issue.

**Comment by pushprajsingh05** [comment]
Hi @prashant-ramcharan 

Do you mind looking at my pom.xml below. I don't why it is running tests twice? I have already commented Runner class per your suggestion above.

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.demo.automation</groupId>
	<artifactId>demo-automation-tests</artifactId>
	<version>1.0-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>demo Serenity project using Cucumber and WebDriver</name>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<serenity.version>2.0.40</serenity.version>
		<serenity.cucumber.version>1.9.31</serenity.cucumber.version>
		<webdriver.driver>firefox</webdriver.driver>
		<forkCount>thread.count</forkCount>
	</properties>
	<repositories>
		<repository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>central</id>
			<name>bintray</name>
			<url>http://jcenter.bintray.com</url>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>central</id>
			<name>bintray-plugins</name>
			<url>http://jcenter.bintray.com</url>
		</pluginRepository>
	</pluginRepositories>
	<dependencies>
		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20090211</version>
		</dependency>
		<dependency>
			<groupId>com.jayway.jsonpath</groupId>
			<artifactId>json-path</artifactId>
			<version>2.4.0</version>
		</dependency>
		<dependency>
			<groupId>net.minidev</groupId>
			<artifactId>json-smart</artifactId>
			<version>2.3</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-core</artifactId>
			<version>${serenity.version}</version>
			<scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>com.aventstack</groupId>
			<artifactId>extentreports-cucumber2-adapter</artifactId>
			<version>1.0.0</version>
		</dependency>
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-cucumber</artifactId>
			<version>${serenity.cucumber.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.17</version>
		</dependency>

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>1.7.7</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-junit</artifactId>
			<version>1.0.23</version>
		</dependency>
	</dependencies>
	<profiles>
		<profile>
			<id>default</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<build>
				<plugins>
					<plugin>
						<artifactId>maven-antrun-plugin</artifactId>
						<version>1.8</version>
						<executions>
							<execution>
								<phase>test</phase>
								<goals>
									<goal>run</goal>
								</goals>
								<configuration>
									<target name="env_setup">
										<delete>
											<fileset dir="${project.build.outputDirectory}"
												includes="*.json" />
										</delete>
										<copy file="src/main/resources/qa.json"
											tofile="${project.build.outputDirectory}/env.json" />
									</target>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>qa</id>
			<build>
				<plugins>
					<plugin>
						<artifactId>maven-antrun-plugin</artifactId>
						<version>1.8</version>
						<executions>
							<execution>
								<phase>test</phase>
								<goals>
									<goal>run</goal>
								</goals>
								<configuration>
									<target name="env_setup">
										
										<delete>
											<fileset dir="${project.build.outputDirectory}"
												includes="*.json" />
										</delete>
										<copy file="src/main/resources/qa.json"
											tofile="${project.build.outputDirectory}/env.json" />
										
									</target>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>stage</id>
			<build>
				<plugins>
					<plugin>
						<artifactId>maven-antrun-plugin</artifactId>
						<version>1.8</version>
						<executions>
							<execution>
								<phase>test</phase>
								<goals>
									<goal>run</goal>
								</goals>
								<configuration>
									<target name="env_setup">
										
										<delete>
											<fileset dir="${project.build.outputDirectory}"
												includes="*.json" />
										</delete>
										<copy file="src/main/resources/stage.json"
											tofile="${project.build.outputDirectory}/env.json" />
										
									</target>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>prod</id>
			<build>
				<plugins>
					<plugin>
						<artifactId>maven-antrun-plugin</artifactId>
						<version>1.8</version>
						<executions>
							<execution>
								<phase>test</phase>
								<goals>
									<goal>run</goal>
								</goals>
								<configuration>
									<target name="env_setup">
										
										<delete>
											<fileset dir="${project.build.outputDirectory}"
												includes="*.json" />
										</delete>
										<copy file="src/main/resources/prod.json"
											tofile="${project.build.outputDirectory}/env.json" />
										
									</target>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.0.0-M3</version>
				<configuration>
					<skip>true</skip>
				</configuration>
			</plugin>

			<plugin>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>2.20</version>
				<configuration>
					<systemPropertyVariables>
						<webdriver.base.url>${webdriver.base.url}</webdriver.base.url>
					</systemPropertyVariables>
					

					
					<forkCount>${thread.count}</forkCount>
					<reuseForks>true</reuseForks>
					<includes>
						<include>**/Parallel*IT.class</include>
					</includes>
					<perCoreThreadCount>true</perCoreThreadCount>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>com.github.temyers</groupId>
				<artifactId>cucumber-jvm-parallel-plugin</artifactId>
				<version>4.2.0</version>
				<executions>
					<execution>
						<id>generateRunners</id>
						<phase>generate-test-sources</phase>
						<goals>
							<goal>generateRunners</goal>
						</goals>
						<configuration>
							
							
							<glue>
								<package>com.demo.automation.steps</package>
							</glue>
							<featuresDirectory>src/test/resources/features</featuresDirectory>
							
							<cucumberOutputDir>target</cucumberOutputDir>
							<format>json,html</format>
							
							<parallelScheme>FEATURE</parallelScheme>
							<customVmTemplate>src/test/resources/cucumber-serenity-runner.vm</customVmTemplate>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.0</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>net.serenity-bdd.maven.plugins</groupId>
				<artifactId>serenity-maven-plugin</artifactId>
				<version>${serenity.version}</version>
				<executions>
					<execution>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>

Thanks
