### ISSUE TITLE
Not able to use courgette-jvm

### ISSUE THREAD

**Issue by martinmineo** [prashant-ramcharan/courgette-jvm#362]
I'm not being able to use it. I'm getting the same error I'm getting when using [the example you provided](https://github.com/prashant-ramcharan/courgette-jvm-maven-example)

I'm using the Java version:
> openjdk version "18.0.2.1" 2022-08-18
OpenJDK Runtime Environment (build 18.0.2.1+1-1)
OpenJDK 64-Bit Server VM (build 18.0.2.1+1-1, mixed mode, sharing)

And this is the error I'm getting

>[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.468 s
[INFO] Finished at: 2022-11-07T09:05:49-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project courgette-jvm-example: Fatal error compiling: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0x6588b715) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x6588b715 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

If I add the Lombok dependency, I'm getting a different error, but I shouldn't be adding it as a dependency

Could you please help me?
Thanks

**Comment by prashant-ramcharan** [comment]
Courgette does not have a direct dependency to Lombok and you would not need to add it in your `pom`

1. Are you running from the command line or IDE?
2. What other versions of Java do you have installed on your machine?
3. Do you see the same issue when running the project on a different machine?
4. Can you provide the debug log using `mvn test -X` ?

**Comment by martinmineo** [comment]
Never mind. I was able to make it work and it works amazingly!!
