### ISSUE TITLE
Is it possible to use the same browser to run the next test?

### ISSUE THREAD

**Issue by sobi-ki** [prashant-ramcharan/courgette-jvm#365]
Hi @prashant-ramcharan ,

Is there an easy way to use the same browser for each feature? If you have an example that would be great.

Thank you

**Comment by prashant-ramcharan** [comment]
Hello,

If you using `runLevel = CourgetteRunLevel.FEATURE` then you can re-use the same browser for each feature but you cannot use the same browser for multiple features at the same time for obvious reasons.

When using `runLevel = CourgetteRunLevel.SCENARIO` then each scenario will have to use its own browser.

**Comment by sobi-ki** [comment]
Thank you for your response.
