### ISSUE TITLE
Cucumber HTML report not generated when cucumber options is overridden

### ISSUE THREAD

**Issue by MadhuQAAutomation** [prashant-ramcharan/courgette-jvm#368]
Hi @prashant-ramcharan - Cucumber HTML report is not generated when we run the test from command line by overriding the plugin -
mvn test -Dcourgette.threads=1 -Dcourgette.runLevel=FEATURE -Dcourgette.rerunFailedScenarios=false -Dcucumber.plugin="json:reports/cucumber/json/cucumber.json"

When we run the below command without overriding the plugin tag , then the cucumber HTML report is created

mvn test -Dcourgette.threads=1 -Dcourgette.runLevel=FEATURE -Dcourgette.rerunFailedScenarios=false"

Can you let me know if any config is missing for this behavior.

Thanks!

**Comment by MadhuQAAutomation** [comment]
@prashant-ramcharan - Hi - Can you provide an update on this issue?

**Comment by prashant-ramcharan** [comment]
You are overriding the `cucumber.plugin` and **only specifying the json plugin** and as a result you will not get a html report.

Have you tried this? 

_This will create a `json` and `html` cucumber report in the `reports` directory_

````java
-Dcucumber.plugin="json:reports/cucumber/json/cucumber.json,html:reports/cucumber/html/cucumber.html"
````

**Comment by MadhuQAAutomation** [comment]
It worked ..Thanks!!
