### ISSUE TITLE
Cucumber 2.0+ support

### ISSUE THREAD

**Issue by serzhshakur** [prashant-ramcharan/courgette-jvm#37]
Hello,

do you have plans to support Cucumber 2.0?

**Comment by andrcuns** [comment]
We could use this as well, if You need any help, don't hesitate to ask!

**Comment by prashant-ramcharan** [comment]
[UPDATE]: This isn't as much work as previously thought so will release soon!

**Comment by prashant-ramcharan** [comment]
This is now released.
