### ISSUE TITLE
Cucumber reports are not uploaded

### ISSUE THREAD

**Issue by martinmineo** [prashant-ramcharan/courgette-jvm#370]
When I execute a suite with several tests (around 150 tests) I notice that the individual reports are uploaded to Cucumber (one report per Cucumber example) but the final report is not uploaded.
Even thought I get this message 

```
─────────────────────────────────────────────────────────────────────────
Report published at: 2023-01-27T14:48:50.583954Z

Courgette published your Cucumber Report to:
https://reports.cucumber.io/reports/e86b5381-c96f-44e2-a699-0df4dabd4635
─────────────────────────────────────────────────────────────────────────
```

![Screenshot 2023-01-27 at 12 04 11](https://user-images.githubusercontent.com/11985773/215118453-9a0e3583-3a0c-4fe7-9e59-30c7578e3b1e.png)

**Comment by prashant-ramcharan** [comment]
Hi,

>  I notice that the individual reports are uploaded to Cucumber (one report per Cucumber example) 

How do you know that individual reports are published for each example?  _Courgette does not publish individual reports._

Does the Cucumber html report open fine locally .. from your reports directory?

**Comment by martinmineo** [comment]
From what I was able to see, the reports for the examples are generated and published into Cucumber's reports. Maybe it's not something done by Courgette and I'm confused here.

To answer your question, yes. The Cucumber HTML report opens fine. This file is 22.6 MB. Is it possible that this file is too big?

**Comment by prashant-ramcharan** [comment]
I dont think it's the file size. If the report opens fine locally this would suggest the report data is not corrupted and _should_ upload without issues.

1. Do you have any other Cucumber or Courgette runners in your project?
2. Does this happen on every run or just randomly?

**Comment by martinmineo** [comment]
1. No, only one Courgette runner.
2. It only happens when I run several tests or one single test with several Cucumber examples

**Comment by prashant-ramcharan** [comment]
Do you have or can provide any demo project to replicate this? 

Does the Courgette example project also fail for you?

https://github.com/prashant-ramcharan/courgette-jvm-example/

_This project also has a test with multiple Cucumber examples_

**Comment by prashant-ramcharan** [comment]
Closing inactive issue
