### ISSUE TITLE
Courgette report not generated

### ISSUE THREAD

**Issue by sobi-ki** [prashant-ramcharan/courgette-jvm#376]
Hi,

I see an issue where the courgette report is no longer being generated. I can confirm the Cucumber report get generated without a problem. However, I see a courgette report generated when there are a couple of Scenarios.

For examples:
3 Scenario - courgette report gets generated. A cucumber report is generated

30 Scenario - No  courgette report. A Cucumber report is generated.

Please note sometimes the report is generated without any issues.

The report used to work without issue and started to play up in the last few weeks. I am on dep 6.8.0

I am using Git Actions, I don't see anything for courgette inside the folder. I have also logged this with Git.

Any guidance will be appreciated.

Thanks

**Comment by prashant-ramcharan** [comment]
Hello,

Do you see any Courgette exceptions in the console at the end of the run? You would normally see a message showing that Courgette was unable to create the report.

Have you tried using a different Courgette run level ? (Feature / Scenario)

Have you tried lowering the Courgette `threads` to rule out any memory issues?

Does this only happen on CI builds?  I assume the report is always generated when running locally or when using another CI tool?

**Comment by sobi-ki** [comment]
Hi, 

After looking at the Git logs, it seems the code is reaching the max heap memory. I will take a look at that and fix it.
Thanks for that help.
