### ISSUE TITLE
Can i edit Courgette Test Runner?

### ISSUE THREAD

**Issue by fatahillahardhi** [prashant-ramcharan/courgette-jvm#378]
Hello Prashant I want to ask (again).

Can I edit Courgette Test Runner annotation like this?
Example:
```
@RunWith(Courgette.class)
@CourgetteOptions(
        threads = env("thread_num"),
        runLevel = CourgetteRunLevel.SCENARIO,
        rerunFailedScenarios = true,
        rerunAttempts = env("rerun_attempts"),
        randomThreadDelay =  env("randomDelay"),
        reportTargetDir = "build",
```
the objectives that I can change thread/others using env because I will try Courgette in Gitlab.
Also, I want change in mobileDevices too, for example:

```
mobileDevice = {
                env("Device 1"),
                env("Device 2"),
        },
```
because I don't want the devices to be visible to others except certain people.

if that's not possible, can I use variables instead of env? Thank you

**Comment by prashant-ramcharan** [comment]
Hello,

In your Courgette runner, you can specify any random value and override these values at runtime.

In GitLab you would just need to specify system properties at runtime, for example:

````java
-Dcourgette.threads=2 -Dcourgette.rerunAttempts=2 -Dcourgette.mobileDevice="device1, device2"
````

**Comment by fatahillahardhi** [comment]
Ok that's very helpfull, thank you Prashant!
