### ISSUE TITLE
Run on Appium 2

### ISSUE THREAD

**Issue by fatahillahardhi** [prashant-ramcharan/courgette-jvm#385]
is it possible to run on Appium 2? I tried to run and adjust the capabilities, when running in parallel (in this case I use 2 threads and simulators) there's a problem in WDA and it takes a long time to run (stuck in appium). 

Error messages show `xcodebuild failed with code 65` but when I change to the newest WDA, it cannot run and fails in Appium. When I run with 1 thread, there's no problem, and it can run normally.

I hope there's a solution for this. thank you!

**Comment by prashant-ramcharan** [comment]
Hi, looking at the xcuitest  / appium 2 spec, it doesn't seem to deviate from the current approach of using `wdaLocalPort`

https://appium.github.io/appium-xcuitest-driver/4.34/parallel-tests/

I'm not sure if using a prebuilt webdriver agent (`usePrebuiltWDA`) would make it run faster on an iOS simulator.
