### ISSUE TITLE
How to embed a URL in the courgette report as URL instead of just String?

### ISSUE THREAD

**Issue by bhala-ki** [prashant-ramcharan/courgette-jvm#387]
I would like to embed a URL in the report in the after Hooks. Neither of the below works:
 scenario.log("URL OF TEST IS: "+ pageHelpers.getCurrentUrl());
(OR)        
scenario.attach(pageHelpers.getCurrentUrl(), "URL", "URL OF TEST IS: ");

**Comment by bhala-ki** [comment]
Resolved it by the following which works absolutely fine:
String currentUrl = "<a href=" + driver.getCurrentUrl() + ">" + driver.getCurrentUrl() + "</a>";

Any other alternatives are also appreciable!

**Comment by prashant-ramcharan** [comment]
Hi, 

Yes, adding valid `html` when using `scenario.log` is the only way to do it.
