### ISSUE TITLE
How fix java.lang.ClassNotFoundException: Files\Git\cmd;;/

### ISSUE THREAD

**Issue by BAMTIUIP** [prashant-ramcharan/courgette-jvm#389]
![IMG_20230926_203608](https://github.com/prashant-ramcharan/courgette-jvm/assets/36363375/851dadbb-1063-462c-a5ee-1792e64d5a0e)
How fix this?

**Comment by prashant-ramcharan** [comment]
This does not seem related to this library.

Please try checking your project dependancies or resetting your IDE cache etc..

**Comment by BAMTIUIP** [comment]
This appears when I connect your plugin to a project in gradle.

**Comment by prashant-ramcharan** [comment]
I'm unable to reproduce this. Please share a project demonstrating the issue and I'll take a look.
