### ISSUE TITLE
JUnit Progress?

### ISSUE THREAD

**Issue by babruce** [prashant-ramcharan/courgette-jvm#4]
Hi Prashant,

I am wondering how much progress you've made integrating courgette-jvm with JUnit notifier, if you have any plans to tackle it at all?
I'm looking to use your tool but am lacking for a summary view with more detail than the feature level view that is already included. Before I begin looking at solutions, I was curious which avenues you may have already explored.
Thanks for your hard work!

**Comment by PrashantRiverIsland** [comment]
Hi @babruce 

I did look into this a while back, but did not have much success.

Courgette-JVM uses the Cucumber CLI and therefore the main entry for each feature / scenario is the CLI and **not** JUnit. This makes it difficult to relay the result back to the parent runner when running in parallel.

In addition to the Courgette-JVM report, you can still access the Cucumber HTML and JSON reports. These reports have more detail about passed / failed steps etc..

Note: I will be enhancing the Courgette-JVM report in the future to include more details about step failures etc..

**Comment by prashant-ramcharan** [comment]
Hi @babruce

I did look into this a while back, but did not have much success.

Courgette-JVM uses the Cucumber CLI and therefore the main entry for each feature / scenario is the CLI and not JUnit. This makes it difficult to relay the result back to the parent runner when running in parallel.

In addition to the Courgette-JVM report, you can still access the Cucumber HTML and JSON reports. These reports have more detail about passed / failed steps etc..

Note: I will be enhancing the Courgette-JVM report in the future to include more details about step failures etc..
