### ISSUE TITLE
Report output get only show all failed 

### ISSUE THREAD

**Issue by sobi-ki** [prashant-ramcharan/courgette-jvm#402]
Hey,

I hope you are doing well.

I have a question regarding the event question.

https://github.com/prashant-ramcharan/courgette-jvm?tab=readme-ov-file#event-subscription

Given the below scenario: 
`I want to output all the failed scenarios within Slack when I run a set of tests.`

Currently, I do see a printout when a test fails, but it does not show a list of failures at the end of the run.

Do we currently have an option to show a list of failed tests on Slack? 

Thanks

**Comment by prashant-ramcharan** [comment]
Hi, currently there's no option to output a list of failed tests in Slack. 

You can use `TEST_RUN_SUMMARY` to get an overview of the number of failed tests but this does not show the a list of failed tests.
