### ISSUE TITLE
Courgette report index.html is not generated properly

### ISSUE THREAD

**Issue by gayathri1305** [prashant-ramcharan/courgette-jvm#406]
Hi My automation test folder is coming under another folder. If I give reportTargetDir ="build", it is not generating report properly. Reason is build folder is generated project root repo and inside the automation test folder also. So when writing the report file, it was throwing java.io.FileNotFoundException: build/courgette-report/data/report.ndjson (No such file or directory). Can you help me  on this?

 **project-root
│
└── functional-tests
    ├── src
       └── test
           ├── java
           │   └── cucumber
           │       └── CucumberRunnerE2ETest
          └── resources**

**Comment by gayathri1305** [comment]
package cucumber;

import courgette.api.*;
import courgette.api.junit.Courgette;
import org.junit.runner.RunWith;

@RunWith(Courgette.class)
@CourgetteOptions(
        threads = 5,
        runLevel = CourgetteRunLevel.SCENARIO,
        rerunFailedScenarios = true,
        testOutput = CourgetteTestOutput.CONSOLE,
        plugin = CourgettePlugin.EXTENT_REPORTS,
       // reportTargetDir = ,
        cucumberOptions = @CucumberOptions(
                features = "functional-tests/src/test/java/cucumber/features/testFeature.feature",
                glue = "cucumber.steps",
                tags = {"@all"},
                plugin = {"pretty",
                        "json:functional-tests/report/cucumber-report/cucumber.json",
                        "html:functional-tests/report/cucumber-report/cucumber.html"},
                publish = false
        ))

public class CucumberRunnerE2ETest {
        @CourgetteBeforeAll
        public static void setUp() {
               String reportTargetDir= System.getProperty("user.dir") + "/functional-tests/report";
                System.out.println("************** : "+ reportTargetDir);
                System.setProperty("courgette.api.reportTargetDir",  reportTargetDir );

        }
}

**Comment by prashant-ramcharan** [comment]
Hello,

You cannot provide a path in the way that you have as it will not be available to the runner.

You also don't need to provide an absolute path. 

Have you tried:

````java
@RunWith(Courgette.class)
@CourgetteOptions(
        reportTargetDir= "functional-tests/report",
 )
public class Runner {
}
````

You can also provide this at runtime using:

````java
-Dcourgette.reportTargetDir="functional-tests/report"
`````

**Comment by gayathri1305** [comment]
Hi Prasanth, I tried both way. But I am facing issue in both way. It is not generating the index.html file in courgette-report folder. It was throwing filenotfound exception (it is searching report.json and report.ndjson in courgette-report  folder). 
<img width="332" alt="Screenshot 2024-05-06 at 11 16 42 AM" src="https://github.com/prashant-ramcharan/courgette-jvm/assets/91124628/6c1dbd70-4587-4988-b5af-88f11d3ecd68">

**Comment by prashant-ramcharan** [comment]
Hi, could you provide a project I can reproduce this with? Thanks.

**Comment by prashant-ramcharan** [comment]
Closing inactive issue
