### ISSUE TITLE
Courgette-JVM report generation fails on 6.14.0

### ISSUE THREAD

**Issue by sobi-ki** [prashant-ramcharan/courgette-jvm#410]
Hi,

After updating version from 6.13.0 to 6.14.0 the report generation fails when there are more failures. 

The report gets generated when there is less tests to run. When we have greater number e.g 100 plus the report fails.

**Comment by sobi-ki** [comment]
When I reverted to back to 6.13.0 report works as expected.

**Comment by prashant-ramcharan** [comment]
I reimplemented the reporting processing in version `6.15.0` , could you try this version?
