### ISSUE TITLE
Request - Share state between threads

### ISSUE THREAD

**Issue by FranciscoAAR** [prashant-ramcharan/courgette-jvm#413]
Hi, Prashant. I hope you're doing well.

Currently, sharing state between threads can be quite challenging because all threads run isolated from each other. Do you think it is possible to include a capability similar to Java’s ConcurrentHashMap to serve as a place to post a given variable or value visible to all running threads? This would greatly simplify some aspects of my testing.

Thank you very much for considering this request.

**Comment by prashant-ramcharan** [comment]
Hello, not sure if this would be in scope of this library. 

The issue with sharing context between tests is that they are non deterministic. There's no guarantee to the order in which tests start / complete etc.. so you may find issues with race conditions and asserting the wrong thing etc.. 

However you can implement this yourself to try out:

````java
    @CourgetteBeforeAll
    public static void setUp() {
       // start an in-memory database or any other type of persistence.
      inMemoryDB.create()
      inMemoryDB.save('XYZ', 123)
    }

    @CourgetteAfterAll
    public static void tearDown() {
      inMemoryDB.close()
    }
````

````java
    @When("I retrieve the shared data for XYZ")
    public void retrieve_data() {
        var sharedDataFromDB = inMemoryDB.get('XYZ');
        assertEquals(sharedDataFromDB, 123);
    }
````
