### ISSUE TITLE
Courgette rerun failed scenarios when rerunAttempts is 0

### ISSUE THREAD

**Issue by cucumberRetryChart** [prashant-ramcharan/courgette-jvm#420]
version: io.github.prashant-ramcharan:courgette-jvm:6.14.0

Having this configuration:
    threads = 1,
    runLevel = CourgetteRunLevel.SCENARIO,
    testOutput = CourgetteTestOutput.CONSOLE,
    rerunFailedScenarios = true,
    rerunAttempts = 0,

i am expecting to not re run failed scenarios because the option rerunAttempts is cero,... 
I think it re-runs the scenarios because option rerunFailedScenarios is marked as true,,, but if the option rerunAttempts is cero, i think it must not re-run.

![image](https://github.com/user-attachments/assets/a8486540-ee33-4317-ab84-f1b4a36f1c72)

**Comment by prashant-ramcharan** [comment]
Thanks, I will take a look.

**Comment by prashant-ramcharan** [comment]
This is now resolved in Courgette version `6.18.0`
