### ISSUE TITLE
Can you explain how to handle webdriver, test data in parallel mode?

### ISSUE THREAD

**Issue by iam500** [prashant-ramcharan/courgette-jvm#47]
I have a junit cucumber selenium setup which is running single threadedly. If I use this jvm, how would i need to handle  webdriver, test data(csv) files for parallel execution like threadlocal etc

**Comment by prashant-ramcharan** [comment]
Hi,

Take a look at the [Courgette-JVM Example](https://github.com/prashant-ramcharan/courgette-jvm-example) project.

This shows exactly how to use this library alongside Selenium.

Unless there are restrictions to the resources you trying to access, you wouldn't have an issue running your tests in parallel.

The library simply allows you to run all your features / scenarios **independently** of one another as each tests is executed in a separate JVM. You will not need to add any extra logic to your code.

**Comment by iam500** [comment]
Ok. I am seeing Missing artifact io.github.prashant-ramcharan:courgette-jvm:pom:2.2.1 when i add the dependency.

**Comment by prashant-ramcharan** [comment]
You need to refresh your project dependancies.

_will courgette run different test cases in parallel mode?_  -- Yes, each test case will run independently in parallel.
