### ISSUE TITLE
Parallel vs Sequential? Also, Dynamic Threadcount?

### ISSUE THREAD

**Issue by sgupta304** [prashant-ramcharan/courgette-jvm#51]
Hi,
I have two questions.

1.) Is it possible to easily set if you want a run to be parallel vs sequential?
2.) How can I dynamically set the threadcount?

Thanks,
Sahil

**Comment by prashant-ramcharan** [comment]
Hello,

1. Yes, simply set threads to 1.
````java
@CourgetteOptions(
        threads = 1,
        ....
)
````

2. You pass a system property at runtime.

````gradle
-Dcourgette.threads=2
````

**Comment by sgupta304** [comment]
Hmm...How would I be able to base the thread count based on the number of scenarios/features?

Also, Would your framework work with JUnit5? https://junit.org/junit5/docs/current/user-guide/

**Comment by prashant-ramcharan** [comment]
It doesn't matter whether you provide a thread count that exceeds the number of scenarios / features you have.

Courgette optimizes the thread count based on actual number of features or scenarios to run before execution.

**Example:**
You have 5 features to run in parallel, and you specify the thread count as 10, Courgette automatically sets the thread count to 5.

Does that answer your question?

________

Cucumber does not currently support JUnit 5 so neither will Courgette until then.
https://github.com/cucumber/cucumber-jvm/issues/1149

**Comment by sgupta304** [comment]
Perfect! Thank you so much for answering my questions!
