### ISSUE TITLE
Add to Maven Central

### ISSUE THREAD

**Issue by delrey1** [prashant-ramcharan/courgette-jvm#57]
Aware that it is on Jcenter, but we are trying to use it on an environment which does not have access to Jcenter, only maven central

Would it be possible to have this added to Maven Central? 

Info to do so here:
* https://blog.idrsolutions.com/2015/06/how-to-upload-your-java-artifact-to-maven-central/
* https://maven.apache.org/repository/guide-central-repository-upload.html

Love the project and the work you've done - But would be amazing if this could be on there

**Comment by prashant-ramcharan** [comment]
Sure, will look into adding it to MC.

**Comment by prashant-ramcharan** [comment]
Latest version is now on [Maven Central](http://search.maven.org/#artifactdetails%7Cio.github.prashant-ramcharan%7Ccourgette-jvm%7C2.4.0%7C)

**Comment by delrey1** [comment]
Thank you!!
