### ISSUE TITLE
Running at scenario level ignores tags; Duplicate features running

### ISSUE THREAD

**Issue by rselias** [prashant-ramcharan/courgette-jvm#59]
Hi, I'm running into an odd issue with JUnit tests. I'm using the following runner:

```
@RunWith(Courgette.class) 

@CourgetteOptions(
		threads = 2,
		runLevel = CourgetteRunLevel.FEATURE,
		rerunFailedScenarios = false,
		showTestOutput = true,
		reportTargetDir = "output",
		cucumberOptions = @CucumberOptions(
				features ="classpath:features",
				glue ={"com.cmp.site1.stepDefinitions","com.cmp.site2.stepDefinitions", "com.cmp.site3.stepDefinitions"},
				plugin = { "rerun:target/rerunSmoke.txt", "pretty", "html:target/cucumber-html-report", 
				"json:output/cucumber-report/cucumber.json"},
				tags = {"@Current"},
				monochrome = true,
				dryRun = false,
				strict = true
		))
public class ParallelFeaturesTest {
}
```

If runLevel is CourgetteRunLevel.FEATURE as shown, this runs the single feature tagged Current as it should. If it is changed to CourgetteRunLevel.SCENARIO, then it runs every scenario in the project regardless of tags. Tagging at the feature level or the scenario level makes no difference. Is this intended?

This is probably a separate issue, but when running features, it is running each feature once for each feature file. So if only one feature is tagged, it runs once. If two features are tagged, each runs twice for a total of four features. If six are tagged, each runs six times for a total of 36 features. I can't easily check if it's working the same for scenarios without the ability to run only a specific tag.

I have looked at the other issues involving duplicate tests, but as far as I can tell none of those solutions apply. I'm using Maven, have removed the included dependencies, there are no references to the Current tag anywhere else in the project, and I am not overriding any properties via the command line.

Thank you!

**Comment by prashant-ramcharan** [comment]
That sounds strange and I have'nt seen this behaviour before. 

Unfortunately, I wont be able to investigate without seeing your setup - features, tags, code etc...

Regarding your second issue, how many scenarios are there in each feature file? If you tag at a feature level and that feature has 6 scenarios then it would in fact run 36 scenarios across 6 features.

If you can reproduce this and upload to GitHub or somewhere similar, I will look into it further.

What does the cucumber and courgette reports indicate in terms of what features / scenarios ran?

**Comment by rselias** [comment]
Here's a [demonstration](https://github.com/rselias/Courgette-Duplicates-Demo-Project) of the issue.

The courgette report shows each feature/scenario running one time for each tag it finds. If it finds three tagged items, it will run every tagged item three times, or every scenario three times if running at a scenario level. It doesn't seem to matter if the tags are at a feature or scenario level - using only one or the other made no difference.

The actual project has a varied number of scenarios per feature, and uses feature-level tags for tests of different sites and scenario-level tags to specify smoke/regression/known bugs. Using only scenario-level tags would be possible, but a pain.

**Comment by prashant-ramcharan** [comment]
Seems to be an issue when using the classpath declaration.

Courgette will load your features into the classpath anyway so remove the **classpath** declaration and update the feature path in your runner to:

````java
features ="src/test/resources/features",
````

Because you tagging at both the feature level scenario level, you will have to be specific about the tags uou wish to run otherwise Cucumber will not know which tags to load at runtime.

If you only want to run tests tagged with "@current", then change your runner to:

````java
tags = {"@Current and not @Isolated"}
````

Take a look at [Tag Expressions](https://docs.cucumber.io/cucumber/api/#tag-expressions)

You runner should look like this:

````java
@RunWith(Courgette.class)
@CourgetteOptions(
		threads = 2,
		runLevel = CourgetteRunLevel.FEATURE,
		rerunFailedScenarios = false,
		showTestOutput = true,
		reportTargetDir = "output",
		cucumberOptions = @CucumberOptions(
				features ="src/test/resources/features",
				glue ={"com.cmp.site1.stepDefinitions"},
				plugin = { "rerun:target/rerunSmoke.txt", "pretty", "html:target/cucumber-html-report", 
				"json:output/cucumber-report/cucumber.json"},
				tags = {"@Current and not @Isolated"},
				monochrome = true,
				dryRun = false,
				strict = true
		))
public class ParallelFeaturesTest {
}
````

**Comment by rselias** [comment]
Working fine now. Thanks!
