### ISSUE TITLE
IncompatibleClassChangeError: Implementing class error thrown

### ISSUE THREAD

**Issue by puthuk** [prashant-ramcharan/courgette-jvm#60]
Hi,
Im getting below error when using Courgette

> java.lang.IncompatibleClassChangeError: Implementing class
> 
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
> 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at cucumber.runtime.io.ResourceLoaderClassFinder.loadClass(ResourceLoaderClassFinder.java:38)
> 	at cucumber.runtime.io.ResourceLoaderClassFinder.getDescendants(ResourceLoaderClassFinder.java:26)
> 	at cucumber.runtime.Reflections.instantiateSubclasses(Reflections.java:28)
> 	at cucumber.runtime.Runtime.loadBackends(Runtime.java:99)
> 	at cucumber.runtime.Runtime.<init>(Runtime.java:66)
> 	at courgette.runtime.CourgetteFeatureLoader.createRuntime(CourgetteFeatureLoader.java:60)
> 	at courgette.runtime.CourgetteFeatureLoader.<init>(CourgetteFeatureLoader.java:30)
> 	at courgette.api.junit.Courgette.<init>(Courgette.java:36)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
> 	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
> 	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
> 	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
> 	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
> 	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
> 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
> 	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
> 	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
> 	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

Below is the feature runner class
import courgette.api.CourgetteOptions;
import courgette.api.CourgetteRunLevel;
import courgette.api.junit.Courgette;
import cucumber.api.CucumberOptions;
import org.junit.runner.RunWith;

```
@RunWith(Courgette.class)
@CourgetteOptions(
        threads = 3,
        runLevel = CourgetteRunLevel.SCENARIO,
        rerunFailedScenarios = true,
        showTestOutput = true,
        reportTargetDir = "results/reports",
        cucumberOptions = @CucumberOptions(
                features = "src/test/features/"
                , tags = {""~@blocked"}
                , format = {"pretty", "html:results/reports/html", "json:results/reports/json/cucumber.json"}
        )
)

public class ScenarioRunner {
}
```

Gradle snippet:
    ```
testCompile 'io.github.prashant-ramcharan:courgette-jvm:2.4.0'
    testCompile 'io.github.prashant-ramcharan:webdriver-binary-downloader:1.2.2'
```

I think Im missing something very obvious :( 
Please help.

**Comment by prashant-ramcharan** [comment]
Looks like your feature files are not in your classpath.

Are your cucumber features in:

src/test/features/
_or_
src/test/**resources**/features/

**Comment by puthuk** [comment]
Ah, found the issue. I had added a dependancy for cucumber in my build.gradle
    ```
compile 'info.cukes:cucumber-core:1.2.5'
    compile 'info.cukes:cucumber-java:1.2.5'
```
Removed them since it already comes with Courgette and now it does not throw exception.

But I have another concern now.
I've given the threads count as 3 with CourgetteRunLevel as SCENARIO, and invoked the cucumber run task. But it does not create run 3 scenarios in parallel. Isn't that how it is supposed to work?
Or is there any other setting I'm missing?

**Comment by prashant-ramcharan** [comment]
Yes, tat is how it supposed to work.

How many test are running in parallel?

Take a look at the example projects:

https://github.com/prashant-ramcharan/courgette-jvm-example
https://github.com/prashant-ramcharan/courgette-jvm-selenium

**Comment by puthuk** [comment]
Currently only one test instance is running now.
Im having a selenium grid to which I'm forwarding the requests. So each one of my 3 threads should create separate requests to the grid which it does not.

**Comment by prashant-ramcharan** [comment]
This is likely an issue with your test setup. I won’t be able to advise any further without you seeing your code. 

Perhaps try recreating the issue with the courgette example project?

**Comment by prashant-ramcharan** [comment]
Inactive issue - closing.
