### ISSUE TITLE
each scenario runs twice courgette-jvm

### ISSUE THREAD

**Issue by umesh9690** [prashant-ramcharan/courgette-jvm#62]
apply plugin: 'groovy'
apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'maven'

buildscript {
    repositories {
        mavenCentral()
    }

}

sourceSets {
    main {
        java {
            srcDirs = ['src/acceptance_test_framework']
        }
        resources {}
    }

    test {
        java {
            srcDirs = ['src/acceptance_tests']
        }
        resources {}
    }
}

repositories {
    mavenCentral()
    jcenter()
}

dependencies {

    compile 'io.github.prashant-ramcharan:courgette-jvm:2.4.0'

    compile group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '2.41.0'
    compile group: 'io.rest-assured', name: 'rest-assured', version: '3.1.0'
    compile group: 'com.googlecode.json-simple', name: 'json-simple', version: '1.1'

}
tasks.withType(Test) {
    systemProperties = System.getProperties()
}

// JUnit
task regressionSuite(type: Test) {
    include 'ScenarioSuite.class'

    outputs.upToDateWhen { false }
}

**Comment by prashant-ramcharan** [comment]
remove this from your build.gradle

````gradle
test {
    java {
        srcDirs = ['src/acceptance_tests']
    }
    resources {}
}
````

**Comment by prashant-ramcharan** [comment]
did this resolve your issue @umesh9690 ?

**Comment by umesh9690** [comment]
not really 
BUILD SUCCESSFUL in 0s
1 actionable task: 1 up-to-date
11:09:51 AM: Task execution finished 'regressionSuite'.

**Comment by prashant-ramcharan** [comment]
for me to investigate further, share your project or replicate issue with https://github.com/prashant-ramcharan/courgette-jvm-example

**Comment by umesh9690** [comment]
@prashant-ramcharan please find project with issue  https://github.com/umesh9690/SampleTest

**Comment by prashant-ramcharan** [comment]
Your project structure is not correct and no features can be loaded into the classpath.

Try doing this:

1. Move the _acceptance_tests_ directory to **src/test/java**

2. Move your _features_ to **src/test/resources**

3. Update the Courgette runner 

````java
                features = "src/test/resources/features"
````

**Comment by umesh9690** [comment]
@prashant-ramcharan the project structure is kept like this intentional. more over to handle this Source set is been changes accordingly.    test {
        java {
            srcDirs = ['src/acceptance_tests']
        }
        resources {
            srcDirs = ['src/acceptance_tests/features']
        }
    }

Normal Junit TestRunner works fine with this...

**Comment by prashant-ramcharan** [comment]
then update the gradle task -- include the wildcard 

_**/ScenarioSuite.class_
 
````java
task regressionSuite(type: Test) {
    include '**/ScenarioSuite.class'

    outputs.upToDateWhen { false }
}
````

**Comment by umesh9690** [comment]
Trouble is not to identify TestRunner Class. Automation suit can identify the test runner using SourceSet config. However while running the test with courgette scenarios are running twice. 
Note: Test is running correctly with JUnit Runner

**Comment by prashant-ramcharan** [comment]
I'm unable to replicate and your project in one of these:

https://github.com/prashant-ramcharan/courgette-jvm-example
https://github.com/prashant-ramcharan/courgette-jvm-selenium

What does the Courgette report show?

**Comment by PrashantRiverIsland** [comment]
@umesh9690 

Use **forward slashes** in your feature path.

In your courgette runner change the feature path to:

````java
                features = "src/acceptance_tests/features",
````

**Comment by prashant-ramcharan** [comment]
When the runtime is created, your features files are not loaded in the classpath and **Courgette expects this**.

Basically, Courgette loads **ALL** features / scenarios found in **src/acceptance_tests/features**. 

This is related to the way your project is structured.

If you move your features to **src/test/resources** or if you mark your feature folder as resources folder it should work fine!

**Comment by prashant-ramcharan** [comment]
Inactive issue - closing. 

@umesh9690  please reopen if you can replicate this issue with the example projects.
