### ISSUE TITLE
Failed Assertions are not marking the scenario step as failed when put within try/catch block.

### ISSUE THREAD

**Issue by whaque81** [prashant-ramcharan/courgette-jvm#65]
I want my tests to continue even when the assertion fails so that rest of them could be validated. So I put them within the try/catch block as shown below:

try {
	Assert.assertEquals(actualProjectName.toLowerCase(), projectName.toLowerCase(), "Verifying project approver on projects page "+"Actual: "+actualProjectName+"|| Expected: "+projectName);	
		}
catch(AssertionError e) {
	logger.error("Failed to verify project name");
	e.printStackTrace(); }

BUT the Courgette-JVM report shows as the step as Passed, even when there is a failure.

**Comment by prashant-ramcharan** [comment]
I'm not quite sure I follow. 

You suppressing the test failure by catching the AssertionError.  How would **Cucumber** know the step failed? This step will not be flagged as a failure because you handling the failure in a try / catch block.

If you were to use the standard Cucumber runner, you will see the same outcome. You can also refer to the result in cucumber.json which will show the step passed.

Courgette-JVM report simply uses the data that Cucumber writes to cucumber.json.

**Comment by whaque81** [comment]
Putting assertions in try/catch block was the only option as I want my cucumber test to continue even when 1 validation/assertion fails. I was hoping your framework would mark the assertion as failed and move on to the next one BUT it is exiting from the test thus skipping rest of the steps in the test. Any ideas?

**Comment by ross-luscombe** [comment]
Have you considered using soft assertions from AssertJ?

http://joel-costigliola.github.io/assertj/core/api/org/assertj/core/api/SoftAssertions.html

**Comment by prashant-ramcharan** [comment]
This is not how Cucumber works (_or designed to work_). If a step fails, all steps following that step will be skipped.

Courgette-JVM does not decide the result of each step. It simply uses the Cucumber library to run the scenario. Cucumber decides the result of each step.

The data that Courgette uses to create its report comes from the Cucumber report.

Why do you need to add an assertion? If all you doing is logging a message when 2 things are not equal, then you could just use an if statement?

````java
 if(actualProjectName.toLowerCase() != projectName.toLowerCase()) {
     logger.error("Failed to verify project name");
}
````

**Comment by whaque81** [comment]
Thanks Prashant...

**Comment by whaque81** [comment]
Can you add this feature in your framework? Ability to pass Cucumber Options from pom.xml instead of TestRunner class?

**Comment by prashant-ramcharan** [comment]
This is already implemented. You can override Courgette options and Cucumber options using System properties.

In your pom.xml, simply set the system properties.
https://maven.apache.org/surefire/maven-surefire-plugin/examples/system-properties.html

````
mvn test -Dcucumber.tags="@regression, not @bug" -Dcucumber.glue="steps, hooks"
````
