### ISSUE TITLE
Odd duration in JSON report

### ISSUE THREAD

**Issue by rselias** [prashant-ramcharan/courgette-jvm#67]
The duration of steps in the JSON report is being reported as numbers on the order of 1e8 to 1e10. The sum of all the steps is 2,148,534,163,031. The test took 573 seconds. I don't see any relationship between those numbers. If those are nanoseconds then that's 36 minutes, almost four times as long as it actually took.

I'm not sure what format are the duration numbers are supposed to be in. I don't see any obvious transformations to get a meaningful number. Am I missing something, or have I run into a bug?

**Comment by prashant-ramcharan** [comment]
All json reports are generated by the Cucumber library and not Courgette.

Courgette simply parses the json data and then creates the Courgette html report.

_Note. Cucumber does use nanoseconds in the result._
https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/cucumber/api/Result.java#L51

**Comment by rselias** [comment]
Figured out the issue. Thanks!
