### ISSUE TITLE
Is there a way to run code inside the Junit or TestNG class

### ISSUE THREAD

**Issue by Balhindi** [prashant-ramcharan/courgette-jvm#71]
Hello Again,

I had a question and was wondering if there was a way to run some code before the first @before method in cucumber inside the the Junit or TestNG class.

Let me know if possible. 

Thank you.

**Comment by prashant-ramcharan** [comment]
With the Junit runner, no you cannot.

With the TestNG runner, you can do something like this:
````java
public class TestSuite extends TestNGCourgette {

    @BeforeClass
    public void beforeTestSuite() {
        System.out.println("I will start my server once!");
    }
}
````

**Comment by Balhindi** [comment]
Thanks a bunch again. Hope, you have a great day.

**Comment by Balhindi** [comment]
Hey Sorry, 

one more question. If I run this from Command line, the before Suite does not run, but if I run the class fro the IDE it runs. 

Any idea to make sure it runs from Command line?

**Comment by prashant-ramcharan** [comment]
what makes you think it does not run? Did you run it with Gradle?

Try verifying with this assert. Your tests should fail if it gets run.

````java
public class TestSuite extends TestNGCourgette {

    @BeforeClass
    public void beforeTestSuite() {
        assertTrue(false);
    }
}
````

**Comment by Balhindi** [comment]
So sorry. 

I was doing a System.out.println("hello"); 

But I was not seeing it inside the console while running so I thought it wasn't going through the method in the BeforeClass.

Thank you again.
