### ISSUE TITLE
TestNG enhancements

### ISSUE THREAD

**Issue by whaque81** [prashant-ramcharan/courgette-jvm#76]
Hi Ram,

Are you making enhancements for TestNG? When is the new version getting rolled out?

-W

**Comment by prashant-ramcharan** [comment]
Hello,

Which TestNG enhancements are you referring to? 

Cucumber v4?

**Comment by whaque81** [comment]
You made some enhancements to the reporting, right? But I couldn't find any after upgrading to the new version 2.4.3. I am using TestNG instead of Junit.

**Comment by prashant-ramcharan** [comment]
Version 2.4.3 added support for **Junit** xml reports.

The Courgette html report was unchanged in version 2.4.3

**Comment by whaque81** [comment]
thanks for the info...
