### ISSUE TITLE
Is there an easy way to capture at runtime a test step info?

### ISSUE THREAD

**Issue by niagara1983** [prashant-ramcharan/courgette-jvm#77]
Is there an easy way to capture at runtime a test step info right before/after its execution? Basically the use case here is to save the test step info (name, keyword, result, embeddings etc.) in a DB as well as the scenario info at runtime. 
Can this be done using a beforeStep/AfterStep hook & somehow use the courgette Step class to retrieve the info?

**Comment by prashant-ramcharan** [comment]
Unfortunately, there's no easy way to return **step level** information.

However, you can easily access the scenario level information by passing the scenario to the before / after hook.

````java
    @Before
    public void before(Scenario scenario) {
        scenario.getName();
        scenario.getStatus()
        ...
    }
````

Your only option to access step level information would be to read and process the data  (_name, keyword, result, embeddings etc._)  from the cucumber.json once all tests are complete.

**Comment by niagara1983** [comment]
Thanks Prashant! I am able to access the scenario level information but I did not want to take the route of processing the cucumber.json file if there was a way to get the step level info at runtime. Thanks for your reply.
