### ISSUE TITLE
Maven surefire plugin is not notified about the result

### ISSUE THREAD

**Issue by gpapadakis** [prashant-ramcharan/courgette-jvm#8]
Running the tests from maven surefire plugin the plugin is not updated with the result (such as the JUnit notifier) with output:
`Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:integration-test (integration-test-singlethreaded) on project qa-automation-web: Execution integration-test-singlethreaded of goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:integration-test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?`

Is there any way to pass exit status to maven surefire?

**Comment by PrashantRiverIsland** [comment]
Courgette-JVM calls System.exit to mark the build as successful or not.

Each thread uses the Cucumber CLI which in turn calls System.exit on that thread (the result of which is returned back to Courgette)

The surefire plugin [http://maven.apache.org/surefire/maven-surefire-plugin/faq.html](url) states that:

_**Surefire does not support tests or any referenced libraries calling System.exit() at any time.**_

**Comment by prashant-ramcharan** [comment]
Courgette-JVM calls System.exit to mark the build as successful or not.

Each thread uses the Cucumber CLI which in turn calls System.exit on that thread (the result of which is returned back to Courgette)

The surefire plugin http://maven.apache.org/surefire/maven-surefire-plugin/faq.html states that:

**_Surefire does not support tests or any referenced libraries calling System.exit() at any time._**

**Comment by prashant-ramcharan** [comment]
Unfortunately, this is a limitation of the surefire plugin.
