### ISSUE TITLE
Screenshot for failed step - Help Needed

### ISSUE THREAD

**Issue by pbehl80** [prashant-ramcharan/courgette-jvm#82]
I have the following code in the step definition file which is failing at the assertion point. 
wt.waitUntilElementIsVisible(searchbtn.getBy());
	searchbtn.ClickButtonUsingJavascript();
	Assert.assertTrue(fordlink.isDisplayed());

I am expecting the report builder class would generate an embedded screenshot for the failed step. It is only throwing the exception and not generating any screenshot. Is there a way we can introduce the screenshot for these failed steps(or may be on demand as well). My images folder is also empty.

Can you please help here..

**Comment by prashant-ramcharan** [comment]
Add this is to your step def:

````java
    @After
    public void after(Scenario scenario) {
        if (scenario.isFailed()) {
            scenario.write("Scenario failed so capturing a screenshot");

            TakesScreenshot screenshot = (TakesScreenshot) driver;
            scenario.embed(screenshot.getScreenshotAs(OutputType.BYTES), "image/png");
        }
    }
````
