### ISSUE TITLE
Issue while running test runner

### ISSUE THREAD

**Issue by khuddusgithub5** [prashant-ramcharan/courgette-jvm#83]
java.lang.NoSuchMethodError: cucumber.runtime.Runtime.getEventBus()Lcucumber/runner/EventBus;
	at courgette.runtime.CourgetteFeatureLoader.<init>(CourgetteFeatureLoader.java:31).

This error populating when trying to run cucumber with Courgette options

**Comment by khuddusgithub5** [comment]
@prashant-ramcharan  Please help in resolving this error.

**Comment by prashant-ramcharan** [comment]
1. Did you refresh the project dependancies?
2. Do you have any other references to Cucumber in your build.gradle or POM xml?
3. Do you get the same error when using the standard Cucumber runner?

**Comment by prashant-ramcharan** [comment]
Remove all references to info.cukes:cucumber-java:1.2.4 as this is what's conflicting.

Simply use the courgette-jvm dependancy only.

**Comment by prashant-ramcharan** [comment]
@khuddusgithub5 Is your issue now resolved?

**Comment by prashant-ramcharan** [comment]
Closing issue as no further response.
