### ISSUE TITLE
JunitReporter Issue while running Test Runner

### ISSUE THREAD

**Issue by khuddusgithub5** [prashant-ramcharan/courgette-jvm#85]
Hi,

I am getting below error message.

java.lang.NoSuchMethodError: cucumber.runtime.junit.JUnitReporter.<init>(Lgherkin/formatter/Reporter;Lgherkin/formatter/Formatter;ZLcucumber/runtime/junit/JUnitOptions;).

Please suggest what changes do I need to do?

**Comment by prashant-ramcharan** [comment]
Looks like Cucumber is not in your classpath or you are using an incorrect version.

What Cucumber version is in your build.gradle or POM.xml?

**Comment by khuddusgithub5** [comment]
I am using following cucumber packages after commenting info.cukes 
compile("junit:junit:4.11")
testCompile 'io.github.prashant-ramcharan:courgette-jvm:1.4.3'
testCompile group: 'io.cucumber', name: 'cucumber-junit', version: '2.0.0

**Comment by prashant-ramcharan** [comment]
Please share a project on github which can reproduce this for me to investigate further.

**Comment by prashant-ramcharan** [comment]
Please try using Courgette version 3.0.0 which was just released.
