### ISSUE TITLE
Getting NoSuchMethodError like 

### ISSUE THREAD

**Issue by cfsavant** [prashant-ramcharan/courgette-jvm#90]
Location of features
![image](https://user-images.githubusercontent.com/40282480/49635214-4a44f080-f9bc-11e8-9afc-799fba177426.png)

Location of steps which is PageActions.groovy
![image](https://user-images.githubusercontent.com/40282480/49635265-719bbd80-f9bc-11e8-8a0d-8bbcbb63e4e6.png)

My Junit test class
![image](https://user-images.githubusercontent.com/40282480/49635298-87a97e00-f9bc-11e8-86c7-7ff9cb2485d3.png)

build.gradle entries
dependencies {
compile 'io.github.prashant-ramcharan:courgette-jvm:3.0.0'
}
tasks.withType(Test) {
    systemProperties = System.getProperties()
}

// JUnit
task regressionSuite(type: Test) {
    include '**/ChromeTest.class'

    outputs.upToDateWhen { false }
}

**Comment by prashant-ramcharan** [comment]
Inactive issue.
