### ISSUE TITLE
DataTable is not getting compiled when use the testCompile ('io.github.prashant-ramcharan:courgette-jvm:3.0.0') 

### ISSUE THREAD

**Issue by karthees1985** [prashant-ramcharan/courgette-jvm#91]
DataTable is not getting compiled when use the testCompile ('io.github.prashant-ramcharan:courgette-jvm:3.0.0')

**Comment by prashant-ramcharan** [comment]
Perhaps try refreshing your project dependancies.

The datatable compiles fine in the example project here: https://github.com/prashant-ramcharan/courgette-jvm-example

**Comment by prashant-ramcharan** [comment]
Inactive issue.
