### ISSUE TITLE
How to not close browser instance thread feature file will executed?

### ISSUE THREAD

**Issue by entmoiseev** [prashant-ramcharan/courgette-jvm#97]
I have  runLevel = CourgetteRunLevel.FEATURE,
and 2 thread and using Geb, gradle. And try to run 3 feature files. 
I have opened 2 browser instance. And when the first feature is finished - then browser is closed and open new browser. 
But how I can continue feature into this browser without closing browser and open a new thread ? 
Thanks

**Comment by prashant-ramcharan** [comment]
Hello,

Every feature / scenario is executed in a new thread so you cannot share a single browser instance between threads. 

So if you using a before hook to open a browser, every feature / scenario will have the same hook which will open a new browser in the invoked thread.

Courgette does not allow you to share state between tests, so static variables and shared resources etc.. are always destroyed when the thread ends.

You can however use [Courgette Callbacks](https://github.com/prashant-ramcharan/courgette-jvm#callbacks) in the Courgette runner which will execute before or after the test run. You could use this to connect to a remote driver hub for example.

**Comment by entmoiseev** [comment]
Thank you for your answer
