### ISSUE TITLE
@CourgetteAfterAll runs before all scenarios

### ISSUE THREAD

**Issue by ubobur95** [prashant-ramcharan/courgette-jvm#98]
Runner--------------------
@Test
@CourgetteOptions(
        threads = 4,
        runLevel = CourgetteRunLevel.SCENARIO,
        rerunFailedScenarios = true,
        showTestOutput = true,
        reportTargetDir = "target",
        cucumberOptions = @CucumberOptions(
                plugin = {
                        "pretty",
                        "html:target/cucumber-report/cucumber.html",
                        "json:target/cucumber-report/cucumber.json"
                },
                features = "src/test/resources/features",
                glue = "steps",
                tags = {"@smoke"},
                monochrome = true,
                strict = true
        ))
public class CourgetteRunner extends TestNGCourgette {
    
    @CourgetteBeforeAll
    public static void setUp() {
        System.out.println("START _______________");
        DeviceManager.startDeviceHub();

    }
    
    @CourgetteAfterAll
    public static void tearDown() {
        System.out.println("END _______________");
        DeviceManager.endDeviceHub();
    }
}

Output-------------------
START _______________
END _______________
before hook
before hook
before hook
before hook

**Comment by prashant-ramcharan** [comment]
Courgette callbacks are used in JUnit runners.

As you are using the TestNGCourgette runner, you can use the standard BeforeClass and AfterClass TestNG annotations in your runner.

````java
public class TestSuite extends TestNGCourgette {

    @BeforeClass
    public void beforeTestSuite() {
        System.out.println("START _______________"); 
    }

    @AfterClass
    public void afterTestSuite() {
        System.out.println("END _______________");
    }
}
````

**Comment by ubobur95** [comment]
Oh, alright. Thank you
