### ISSUE TITLE
How to exclude cucumber.java8 dependency?

### ISSUE THREAD

**Issue by HesterLyons** [prashant-ramcharan/courgette-jvm#99]
Hi, I'm using this repository and it is excellent, thank you. I have a simple issue - in our setup, we are using the 'old style' step definitions, not lambda expressions. However, because Courgette is prepackaged with the cucumber.java8 dependency, every time we re-import the Gradle project that dependency is added and Cucumber begins to generate lambda snippets. While it is easy to manually remove the dependency I am wondering if there is some way for me to exclude it from Courgette, either by building a local .jar file with the dependency removed, or by some other way? I guess I could create my own branch but then we wouldn't be getting the updates, so I'd like to avoid that?

**Comment by prashant-ramcharan** [comment]
Try this:

````gradle
    testCompile ('io.github.prashant-ramcharan:courgette-jvm:3.1.0'){
        exclude group: 'io.cucumber', module: 'cucumber-java8'
    }
````

**Comment by HesterLyons** [comment]
Thank you so much, that did the trick.
